export const SAVE_KEY = 'mx-idle-save-v1';
// Kept intentionally light so the first gear unlocks can be reached in one short session.
export const PROVISIONAL_FIRST_SLICE_XP_CURVE = (level: number) => Math.round(15 + Math.max(0, level - 1) * 2);
export const PROVISIONAL_FIRST_SLICE_COMBAT_VALUES = { wolfHp: 70, wolfInterval: 3000, wolfAccuracy: 160, wolfMaxHit: 10, wolfMeleeEvasion: 120, respawn: 3000, gold: 8 } as const;
export const STAGES = [
  { name: 'Outcrop', density: 1, qty: 1, xp: 1 },
  { name: 'Shallow Vein', density: .78, qty: 1.25, xp: 1.4 },
  { name: 'Main Vein', density: .58, qty: 1.6, xp: 2 },
  { name: 'Deep Seam', density: .38, qty: 2.2, xp: 3 },
  { name: 'Core', density: .2, qty: 3.2, xp: 4.5 },
] as const;
export const RESISTANCES = { Slash: 12, Stab: 18, Crush: 14, Pierce: 24, Puncture: 20, Air: 0, Fire: -5, Water: 8, Earth: -8 } as const;
export const ITEMS = {
  pickaxe: { name: 'Worn Pickaxe', icon: 'pick', category: 'Equipment', desc: 'A battered starter tool. Mining Power 6.' },
  hammer: { name: 'Worn Smithing Hammer', icon: 'hammer', category: 'Equipment', desc: 'Forge Power 5 · Strike time 2.20s.' },
  ore: { name: 'Copper Ore', icon: 'ore', category: 'Materials', desc: 'Raw copper from the Copper Vein. Smelt 2 into 1 Copper Ingot.' },
  ingot: { name: 'Copper Ingot', icon: 'ingot', category: 'Materials', desc: 'A warm, workable copper bar.' },
  sword: { name: 'Copper Sword', icon: 'sword', category: 'Equipment', desc: '1H Melee · Slash / Stab · Power 18 · Accuracy +84 · 2.40s · Crit +1 pp.' },
  helm: { name: 'Copper Helm', icon: 'helm', category: 'Equipment', desc: 'T1 Heavy · +2% physical resistance · +5/+6/+2 evasion.' },
  plate: { name: 'Copper Plate Armor', icon: 'armor', category: 'Equipment', desc: 'Heavy chest and leg protection.' },
  gloves: { name: 'Copper Gauntlets', icon: 'gloves', category: 'Equipment', desc: 'Copper hand protection.' },
  greaves: { name: 'Copper Greaves', icon: 'greaves', category: 'Equipment', desc: 'Copper leg protection.' },
  shield: { name: 'Copper Shield', icon: 'shield', category: 'Equipment', desc: 'One-handed melee off-hand.' },
  trophy: { name: 'Beast Trophy', icon: 'trophy', category: 'Combat Loot', desc: 'T1 offering · Offering Value 5.' },
} as const;
export type ItemId = keyof typeof ITEMS;
export type SkillId = 'Mining' | 'Smithing' | 'Attack' | 'Defence' | 'Hitpoints';
export type Activity = 'mining' | 'smelting' | 'forging' | 'combat' | null;
export type RecipeId = 'sword' | 'helm' | 'plate' | 'gloves' | 'greaves' | 'shield';
export type SaveState = {
  version: 1; savedAt: number; rng: number; page: string; activity: Activity;
  skills: Record<SkillId, { xp: number; level: number }>; bank: Partial<Record<ItemId, number>>;
  gold: number; equipped: { tool: boolean; hammer: boolean; weapon: ItemId | null; offhand: ItemId | null; head: ItemId | null; armor: ItemId | null; hands: ItemId | null; feet: ItemId | null };
  mining: { stage: number; density: number; timer: number; cycles: number; strikes: number; sessionOre: number; sessionXp: number };
  smithing: { mode: 'smelting' | 'forging'; recipe: RecipeId; timer: number; warm: boolean; produced: number; work: number; heat: number; reserved: number; reheat: boolean; message: string };
  combat: { stance: 'Slash' | 'Stab'; playerHp: number; wolfHp: number; playerTimer: number; enemyTimer: number; seq: number; bleed: number; bleedTicks: number; bleedTimer: number; kills: number; xp: number; gold: number; trophies: number; elapsed: number; respawn: number; log: string[] };
  objectives: { dismissed: boolean; firstCycle: boolean; firstIngot: boolean; sword: boolean; helm: boolean; victory: boolean };
  settings: { muted: boolean; volume: number; reducedMotion: boolean | null };
  lastEvent: string; lastSaved: number;
};
const emptySkills = (): SaveState['skills'] => ({ Mining: { xp: 0, level: 1 }, Smithing: { xp: 0, level: 1 }, Attack: { xp: 0, level: 1 }, Defence: { xp: 0, level: 1 }, Hitpoints: { xp: 0, level: 1 } });
export function freshState(now = Date.now()): SaveState { return { version: 1, savedAt: now, lastSaved: now, rng: 19790321, page: 'Mining', activity: null, skills: emptySkills(), bank: { pickaxe: 1, hammer: 1 }, gold: 0, equipped: { tool: true, hammer: false, weapon: null, offhand: null, head: null, armor: null, hands: null, feet: null }, mining: { stage: 0, density: 36, timer: 2400, cycles: 0, strikes: 0, sessionOre: 0, sessionXp: 0 }, smithing: { mode: 'smelting', recipe: 'sword', timer: 0, warm: false, produced: 0, work: 0, heat: 100, reserved: 0, reheat: false, message: '' }, combat: { stance: 'Slash', playerHp: 100, wolfHp: PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfHp, playerTimer: 2400, enemyTimer: PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfInterval, seq: 0, bleed: 0, bleedTicks: 0, bleedTimer: 0, kills: 0, xp: 0, gold: 0, trophies: 0, elapsed: 0, respawn: 0, log: [] }, objectives: { dismissed: false, firstCycle: false, firstIngot: false, sword: false, helm: false, victory: false }, settings: { muted: false, volume: .35, reducedMotion: null }, lastEvent: '' }; }
export function stageDensity(stage: number) { return Math.ceil(36 * STAGES[stage].density); }
export function stageStrikes(stage: number, power = 6) { return Math.ceil(stageDensity(stage) / power); }
export function nextStage(stage: number) { return (stage + 1) % STAGES.length; }
export function hitChance(accuracy: number, evasion: number) { const ratio = accuracy < evasion ? .5 * accuracy / evasion : 1 - .5 * evasion / accuracy; return Math.max(.05, Math.min(.95, ratio)); }
export function damageAfterResistance(raw: number, resistance: number) { return Math.max(1, Math.floor(raw * (1 - Math.max(-25, Math.min(75, resistance)) / 100))); }
export function xpForLevel(level: number) { return PROVISIONAL_FIRST_SLICE_XP_CURVE(level); }
export function maxHitpoints(level: number) { return 90 + level * 10; }
function rand(s: SaveState) { let x = s.rng | 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; s.rng = x >>> 0; return s.rng / 4294967296; }
function addXp(s: SaveState, skill: SkillId, amount: number) { if (amount <= 0) return; const before = s.skills[skill].level; s.skills[skill].xp += amount; while (s.skills[skill].level < 100 && s.skills[skill].xp >= xpForLevel(s.skills[skill].level)) { s.skills[skill].xp -= xpForLevel(s.skills[skill].level); s.skills[skill].level++; } if (s.skills[skill].level > before) { s.lastEvent = `${skill} reached level ${s.skills[skill].level}`; s.combat.log = [`${skill} reached level ${s.skills[skill].level}.`, ...s.combat.log].slice(0, 8); } }
function gain(s: SaveState, item: ItemId, n: number) { if (n > 0) s.bank[item] = (s.bank[item] ?? 0) + n; }
function consume(s: SaveState, item: ItemId, n: number) { if ((s.bank[item] ?? 0) < n) return false; s.bank[item] = (s.bank[item] ?? 0) - n; if (!s.bank[item]) delete s.bank[item]; return true; }
export function startActivity(s: SaveState, activity: Exclude<Activity, null>) { if (activity === 'smelting' && (s.bank.ore ?? 0) < 2) { s.smithing.message = 'Not enough Copper Ore'; return; } if (activity === 'forging' && !s.smithing.reserved && (s.bank.ingot ?? 0) < RECIPES[s.smithing.recipe].ingots) { s.smithing.message = 'Not enough Copper Ingots'; return; } if (activity === 'combat' && (s.equipped.weapon !== 'sword' || !(s.equipped.head || s.equipped.armor || s.equipped.hands || s.equipped.feet))) { s.lastEvent = 'Equip a melee weapon and one armor piece to begin'; return; } if (s.activity && s.activity !== activity) { if (s.activity === 'smelting') { s.smithing.warm = false; s.smithing.timer = 0; } if (s.activity === 'forging') s.smithing.timer = 0; } s.activity = activity; if (activity === 'mining') { s.page = 'Mining'; s.mining.timer = s.mining.timer || 2400; } if (activity === 'smelting') { s.page = 'Smithing'; s.smithing.mode = 'smelting'; s.smithing.warm = false; s.smithing.timer = 3040; s.smithing.message = ''; } if (activity === 'forging') { s.page = 'Smithing'; s.smithing.mode = 'forging'; s.smithing.message = ''; if (!s.smithing.reserved) { const recipe = RECIPES[s.smithing.recipe]; if (!consume(s, 'ingot', recipe.ingots)) { s.activity = null; s.smithing.message = 'Not enough Copper Ingots'; return; } s.smithing.reserved = recipe.ingots; s.smithing.work = Math.round(28 * recipe.work); s.smithing.heat = 100; s.smithing.reheat = false; s.smithing.timer = 2200; } else s.smithing.timer ||= 2200; } if (activity === 'combat') { s.page = 'Combat'; if (s.combat.playerHp <= 0) s.combat.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.combat.playerTimer ||= 2400; s.combat.enemyTimer ||= 3000; } }
export function stopActivity(s: SaveState) { if (s.activity === 'smelting') { s.smithing.warm = false; s.smithing.timer = 0; } if (s.activity === 'forging') s.smithing.timer = 0; if (s.activity === 'mining') s.mining.timer ||= 2400; s.activity = null; }
export const RECIPES: Record<RecipeId, { name: string; ingots: number; work: number; unlock: number; slot: string }> = { sword: { name: 'Copper Sword', ingots: 4, work: 1.1, unlock: 1, slot: 'Weapon' }, helm: { name: 'Copper Helm', ingots: 3, work: .9, unlock: 5, slot: 'Head' }, plate: { name: 'Copper Plate Armor', ingots: 12, work: 3.15, unlock: 5, slot: 'Armor' }, gloves: { name: 'Copper Gauntlets', ingots: 2, work: .7, unlock: 3, slot: 'Hands' }, greaves: { name: 'Copper Greaves', ingots: 2, work: .75, unlock: 3, slot: 'Feet' }, shield: { name: 'Copper Shield', ingots: 5, work: 1.25, unlock: 5, slot: 'Off-hand' } };
export const recipeItem = (id: RecipeId): ItemId => id;
function miningHit(s: SaveState) { const m = s.mining, st = STAGES[m.stage]; m.density = Math.max(0, m.density - 6); m.strikes++; s.lastEvent = 'Mining strike'; if (m.density <= 0) { const firstOre = !s.bank.ore; const raw = st.qty; const q = Math.floor(raw) + (rand(s) < raw % 1 ? 1 : 0); gain(s, 'ore', q); m.sessionOre += q; const xp = 6 * st.xp; addXp(s, 'Mining', xp); m.sessionXp += xp; s.lastEvent = firstOre ? 'Smithing unlocked' : m.stage === 4 ? 'Copper Core completed' : `${st.name} exposed`; m.stage = nextStage(m.stage); m.density = stageDensity(m.stage); if (m.stage === 0) { m.cycles++; s.objectives.firstCycle = true; s.lastEvent = 'Copper Core completed'; } } }
function smelt(s: SaveState) { const sm = s.smithing; if (!consume(s, 'ore', 2)) { s.activity = null; sm.timer = 0; sm.message = 'Not enough Copper Ore'; return; } gain(s, 'ingot', 1); sm.produced++; addXp(s, 'Smithing', 7); s.objectives.firstIngot = true; s.lastEvent = 'Copper Ingot smelted'; sm.timer = 3000; if ((s.bank.ore ?? 0) < 2) { s.activity = null; sm.message = 'Not enough Copper Ore'; } }
function forgeStrike(s: SaveState) { const sm = s.smithing; const power = 5; if (sm.heat < 25) { sm.reheat = true; sm.timer = 2000; return; } sm.work = Math.max(0, sm.work - power); sm.heat -= 10; s.lastEvent = 'Hammer strike'; addXp(s, 'Smithing', 2); if (sm.work <= 0) { const id = sm.recipe, item = recipeItem(id); gain(s, item, 1); sm.reserved = 0; sm.produced++; sm.message = `${RECIPES[id].name} forged`; s.lastEvent = sm.message; if (id === 'sword') s.objectives.sword = true; if (id === 'helm') s.objectives.helm = true; if (s.objectives.sword && s.objectives.helm) s.lastEvent = 'Broken Road unlocked'; s.activity = null; sm.timer = 0; } else sm.timer = 2200; }
function playerAttack(s: SaveState) { const c = s.combat; const accuracy = 100 + s.skills.Attack.level * 6 + (s.equipped.weapon === 'sword' ? 84 : 0); if (rand(s) <= hitChance(accuracy, PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfMeleeEvasion)) { let raw = 18 * (1 + s.skills.Attack.level / 100); const crit = rand(s) < (.05 + (s.equipped.weapon === 'sword' ? .01 : 0)); if (crit) raw *= 1.5; const dmg = damageAfterResistance(Math.max(1, Math.floor(raw * (.9 + rand(s) * .2))), RESISTANCES[c.stance]); c.wolfHp = Math.max(0, c.wolfHp - dmg); addXp(s, 'Attack', dmg * .4); addXp(s, 'Hitpoints', dmg * .1); addXp(s, 'Defence', dmg * .1); c.log = [crit ? `Critical hit — ${dmg} ${c.stance}.` : `You hit Road Wolf for ${dmg} ${c.stance}.`, ...c.log].slice(0, 8); } else c.log = ['Your attack misses.', ...c.log].slice(0, 8); c.playerTimer = s.equipped.weapon === 'sword' ? 2400 : 3000; if (c.wolfHp <= 0) { c.kills++; c.xp += 24; c.gold += PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.gold; c.trophies++; gain(s, 'trophy', 1); s.gold += PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.gold; addXp(s, 'Attack', 18); addXp(s, 'Defence', 8); addXp(s, 'Hitpoints', 8); s.objectives.victory = true; c.log = ['Road Wolf defeated.', ...c.log].slice(0, 8); c.respawn = 3000; c.wolfHp = 0; s.lastEvent = 'Road Wolf defeated'; } }
function enemyAttack(s: SaveState) { const c = s.combat; const index = c.seq % 3; const rending = index === 2; const acc = hitChance(PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfAccuracy, 100 + s.skills.Defence.level * 5); c.seq = (c.seq + 1) % 3; c.enemyTimer = PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfInterval; if (rand(s) <= acc) { const raw = PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfMaxHit * (rending ? 1.25 : 1) * (.72 + rand(s) * .28); const armor = (s.equipped.head === 'helm' ? 2 : 0) + (s.equipped.armor === 'plate' ? 4 : 0); const dmg = damageAfterResistance(Math.floor(raw), armor); c.playerHp -= dmg; c.log = [`Road Wolf uses ${rending ? 'Rending Fang' : 'Bite'} for ${dmg} Stab.`, ...c.log].slice(0, 8); if (rending) { c.bleed = dmg * .1; c.bleedTicks = 6; c.bleedTimer = 1000; } } else c.log = ['Road Wolf misses.', ...c.log].slice(0, 8); if (c.playerHp <= 0) { c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; c.log = ['Defeated — you recover at the roadside.', ...c.log].slice(0, 8); s.lastEvent = 'Defeated'; } }
function killWolf(s: SaveState) { const c = s.combat; c.wolfHp = PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfHp; c.seq = 0; c.enemyTimer = PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfInterval; c.respawn = 0; }
export function advance(input: SaveState, elapsedMs: number) { const s = structuredClone(input); let left = Math.max(0, elapsedMs); while (left > 0 && s.activity) { let step = left; if (s.activity === 'mining') step = Math.min(step, s.mining.timer || 2400); else if (s.activity === 'smelting' || s.activity === 'forging') step = Math.min(step, s.smithing.timer || (s.activity === 'forging' ? 2200 : 3040)); else { const c = s.combat; step = Math.min(step, c.playerTimer || 2400, c.enemyTimer || 3000, c.respawn || Infinity, c.bleedTimer || Infinity); } if (!(step > 0 && Number.isFinite(step))) break; left -= step; if (s.activity === 'mining') { s.mining.timer -= step; if (s.mining.timer <= 0) { miningHit(s); s.mining.timer = 2400; } } else if (s.activity === 'smelting') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (!s.smithing.warm) { s.smithing.warm = true; s.smithing.timer = 3000; } else smelt(s); } } else if (s.activity === 'forging') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (s.smithing.reheat) { s.smithing.heat = 100; s.smithing.reheat = false; s.smithing.timer = 2200; } else forgeStrike(s); } } else { const c = s.combat; c.elapsed += step; c.playerTimer -= step; c.enemyTimer -= step; if (c.respawn > 0) c.respawn -= step; if (c.bleedTimer > 0) c.bleedTimer -= step; if (c.bleedTicks > 0 && c.bleedTimer <= 0) { const tick = c.bleed / c.bleedTicks; c.playerHp -= tick; c.bleed -= tick; c.bleedTicks--; c.log = [`Bleed deals ${tick.toFixed(1)} damage.`, ...c.log].slice(0, 8); c.bleedTimer = c.bleedTicks ? 1000 : 0; if (c.playerHp <= 0) { c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; s.lastEvent = 'Defeated'; } } if (s.activity === 'combat' && c.respawn <= 0 && c.wolfHp <= 0) killWolf(s); if (s.activity === 'combat' && c.wolfHp > 0 && c.playerTimer <= 0) playerAttack(s); if (s.activity === 'combat' && c.wolfHp > 0 && c.enemyTimer <= 0) enemyAttack(s); } }
 s.savedAt = Date.now(); return s; }
export function loadState(raw: string | null, now = Date.now()): { state: SaveState; awayMs: number; fresh: boolean } { if (!raw) return { state: freshState(now), awayMs: 0, fresh: true }; try { const envelope = JSON.parse(raw); if (envelope.version !== 1 || !envelope.state || typeof envelope.state !== 'object') throw Error('Unsupported save'); const d = freshState(now), s = { ...d, ...envelope.state, version: 1, skills: { ...d.skills, ...envelope.state.skills }, bank: envelope.state.bank ?? d.bank, equipped: { ...d.equipped, ...envelope.state.equipped }, mining: { ...d.mining, ...envelope.state.mining }, smithing: { ...d.smithing, ...envelope.state.smithing }, combat: { ...d.combat, ...envelope.state.combat }, objectives: { ...d.objectives, ...envelope.state.objectives }, settings: { ...d.settings, ...envelope.state.settings }, rng: Number.isFinite(envelope.state.rng) ? envelope.state.rng : d.rng } as SaveState; const awayMs = Math.max(0, now - Number(envelope.savedAt || now)); return { state: advance(s, awayMs), awayMs, fresh: false }; } catch { return { state: freshState(now), awayMs: 0, fresh: true }; } }
