import type { ForgingRecipeId, ItemId } from '../../types/gameTypes';
export type ForgeCategory = 'weapons' | 'armor' | 'offhand' | 'tools';
export type ForgingRecipe = { id: ForgingRecipeId; name: string; unlockLevel: number; inputs: { item: ItemId; amount: number; preservable?: boolean }[]; output: ItemId; workMultiplier: number; category: ForgeCategory; slot: string; workBase: number; xpPerStrike: number; dependencyBridge?: { missingCanonicalDependency: string; replacementPhase: string } };
export const FORGING_RECIPES: Record<ForgingRecipeId, ForgingRecipe> = {
  'recipe.smithing.copper_sword': { id: 'recipe.smithing.copper_sword', name: 'Copper Sword', unlockLevel: 1, inputs: [{ item: 'item.smithing.copper_ingot', amount: 4, preservable: true }], output: 'combat.weapon.melee.copper_sword', workMultiplier: 1.1, category: 'weapons', slot: 'Weapon', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_battle_axe': { id: 'recipe.smithing.copper_battle_axe', name: 'Copper Battle Axe', unlockLevel: 3, inputs: [{ item: 'item.smithing.copper_ingot', amount: 4, preservable: true }], output: 'combat.weapon.melee.copper_battle_axe', workMultiplier: 1.15, category: 'weapons', slot: 'Weapon', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_mace': { id: 'recipe.smithing.copper_mace', name: 'Copper Mace', unlockLevel: 3, inputs: [{ item: 'item.smithing.copper_ingot', amount: 4, preservable: true }], output: 'combat.weapon.melee.copper_mace', workMultiplier: 1.1, category: 'weapons', slot: 'Weapon', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_helm': { id: 'recipe.smithing.copper_helm', name: 'Copper Helm', unlockLevel: 5, inputs: [{ item: 'item.smithing.copper_ingot', amount: 3, preservable: true }], output: 'combat.armor.heavy.copper_helm', workMultiplier: .9, category: 'armor', slot: 'Head', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_armor': { id: 'recipe.smithing.copper_armor', name: 'Copper Plate Armor', unlockLevel: 5, inputs: [{ item: 'item.smithing.copper_ingot', amount: 12, preservable: true }], output: 'combat.armor.heavy.copper_armor', workMultiplier: 3.15, category: 'armor', slot: 'Armor', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_gauntlets': { id: 'recipe.smithing.copper_gauntlets', name: 'Copper Gauntlets', unlockLevel: 5, inputs: [{ item: 'item.smithing.copper_ingot', amount: 2, preservable: true }], output: 'combat.armor.heavy.copper_gauntlets', workMultiplier: .7, category: 'armor', slot: 'Hands', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_greaves': { id: 'recipe.smithing.copper_greaves', name: 'Copper Greaves', unlockLevel: 5, inputs: [{ item: 'item.smithing.copper_ingot', amount: 2, preservable: true }], output: 'combat.armor.heavy.copper_greaves', workMultiplier: .75, category: 'armor', slot: 'Feet', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_shield': { id: 'recipe.smithing.copper_shield', name: 'Copper Shield', unlockLevel: 5, inputs: [{ item: 'item.smithing.copper_ingot', amount: 5, preservable: true }], output: 'combat.offhand.melee.copper_shield', workMultiplier: 1.25, category: 'offhand', slot: 'Off-hand', workBase: 28, xpPerStrike: 2 },
  'recipe.smithing.copper_pickaxe': { id: 'recipe.smithing.copper_pickaxe', name: 'Copper Pickaxe', unlockLevel: 5, inputs: [{ item: 'item.mining.worn_pickaxe', amount: 1 }, { item: 'item.smithing.copper_ingot', amount: 3, preservable: true }], output: 'item.mining.copper_pickaxe', workMultiplier: 1.45, category: 'tools', slot: 'Pickaxe', workBase: 28, xpPerStrike: 2, dependencyBridge: { missingCanonicalDependency: 'tool handle', replacementPhase: 'Phase 2 Woodcutting/Fletching' } },
  'recipe.smithing.copper_smithing_hammer': { id: 'recipe.smithing.copper_smithing_hammer', name: 'Copper Smithing Hammer', unlockLevel: 5, inputs: [{ item: 'item.smithing.worn_smithing_hammer', amount: 1 }, { item: 'item.smithing.copper_ingot', amount: 2, preservable: true }], output: 'item.smithing.copper_smithing_hammer', workMultiplier: 1.35, category: 'tools', slot: 'Hammer', workBase: 28, xpPerStrike: 2, dependencyBridge: { missingCanonicalDependency: 'tool handle', replacementPhase: 'Phase 2 Woodcutting/Fletching' } },
};
