import { useState } from 'react';
import { Badge, Bar, Button, Icon, Panel } from '../../../ui/primitives';
import { ScreenHeading } from '../../../ui/game/ScreenPrimitives';
import { ActionProgress } from '../../../ui/game/ActionProgress';
import { FISHING_RODS, FISHING_SPOTS, FISH_SPECIES, FISHING_TACKLE } from '../../../game/content/fishing/fishingContent';
import { fishingBiteTime, fishingCatchWeights, fishingLandingTime, xpForLevel, type ItemId, type SaveState } from '../../../game/game';
import { GameItemFrame, GameState } from '../../../ui/game-v2/GameKit';

export function FishingScreen({game:g,start,stop,selectSpot,change,bridgeRod,buyBait}: {game:SaveState;start:()=>void;stop:()=>void;selectSpot:(id:string)=>void;change:(patch:Partial<SaveState['fishing']>)=>void;bridgeRod:()=>void;buyBait:(id:string)=>void}) {
 const f=g.fishing, spot=FISHING_SPOTS.find(x=>x.id===f.spot)!, rod=FISHING_RODS.find(x=>x.id===f.rod) ?? FISHING_RODS[0]!, fish=FISH_SPECIES.find(x=>x.id===f.selectedFish), active=g.activity==='fishing', pool=fishingCatchWeights(g), nextRod=FISHING_RODS.find(x=>x.previousRod===rod.id), bridgeFind=FISHING_SPOTS.find(x=>x.findId===nextRod?.bridgeItem)?.findName;const [search,setSearch]=useState('');const waters=FISHING_SPOTS.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));
 const waterType=spot.name.includes('River')||spot.name.includes('Brook')?'river':spot.name.includes('Pond')||spot.name.includes('Lake')?'still':spot.name.includes('Trench')||spot.name.includes('Basin')?'deep':'coast';
 return <div className="screen profession-screen fishing-screen fishing-v2" data-feedback-screen="Fishing"><ScreenHeading eyebrow="PROFESSION / OPEN WATER" title="Fishing" sub="Read the water, set your line, then wait for a catch." accent="fishing" level={g.skills.Fishing.level} xp={g.skills.Fishing.xp} maxXp={xpForLevel(g.skills.Fishing.level)}><Badge tone={active?'live':'level-badge'}>LEVEL {g.skills.Fishing.level}</Badge></ScreenHeading>
  <div className="profession-grid fishing-atlas"><Panel className="profession-rail waters-panel" title="Fishing Atlas" action={<Badge>{FISHING_SPOTS.length} waters</Badge>}><label className="water-search"><span className="sr-only">Search fishing waters</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a water"/></label><div className="waters-list">{waters.map(s=>{const locked=g.skills.Fishing.level<s.unlockLevel,selected=s.id===spot.id,water=s.name.includes('River')||s.name.includes('Brook')?'RIVER':s.name.includes('Pond')||s.name.includes('Lake')?'STILLWATER':s.name.includes('Trench')||s.name.includes('Basin')?'DEEPWATER':'COAST';return <button className={`water-choice ${selected?'selected':''} ${locked?'locked':''}`} key={s.id} onClick={()=>!locked&&selectSpot(s.id)} aria-pressed={selected} disabled={locked}><span className="water-emblem" aria-hidden="true">{s.tier<4?'~':s.tier<7?'≋':'≈'}</span><span><b>{s.name}</b><small>{locked?`Fishing ${s.unlockLevel} required`:`${water} / Fishing ${s.unlockLevel} / ${FISH_SPECIES.filter(x=>x.spotId===s.id&&x.unlockLevel<=g.skills.Fishing.level).length} species / ${s.findName}`}</small></span><Badge>{locked?`LV ${s.unlockLevel}`:'SPOT'}</Badge></button>;})}</div>
   <div className="profession-bridge"><span className="tiny-label">ROD SLOT</span><b>{rod.name} / Power {rod.power}</b>{nextRod&&<><small>Next rod: {nextRod.name} / requires 1 {bridgeFind ?? 'Aquatic Find'}.</small><Button tone="quiet" disabled={g.skills.Fishing.level<nextRod.unlockLevel||(g.bank[nextRod.bridgeItem as ItemId] ?? 0)<1} onClick={bridgeRod}>Craft next rod</Button></>}</div>
  </Panel>
  <Panel className={`profession-focus ${active?'is-active':''} ${active?`phase-${f.phase}`:''}`} title={spot.name} action={<GameState tone={active?'active':'ready'} icon={active?'hook':undefined}>{active?(f.phase==='bite'?'BITE':'LANDING'):'WATERS CALM'}</GameState>}>
   <div data-feedback-anchor="Fishing" className={`water-scene water-scene-v2 biome-${waterType}`}><div className="water-sky"><i className="sky-disc"/><i className="distant-ridge ridge-one"/><i className="distant-ridge ridge-two"/></div><div className="waterline-horizon"/><div className="water-shallows"/><div className="water-ripple ripple-one"/><div className="water-ripple ripple-two"/><div className="water-ripple ripple-three"/><div className="fishing-rod-silhouette"><i/><b/></div><div className="fishing-line-v2"><i/></div><span className="line-float" aria-label={active&&f.phase==='bite'?'A fish is biting':'Fishing float'}>{fish?'●':'○'}</span><small>{fish?`${fish.rarity.toUpperCase()} / ${fish.name}`:active&&f.phase==='bite'?'BITE! SET THE HOOK':'WAITING FOR A BITE'}</small><div className="water-scene-location"><span>FISHING GROUND</span><b>{spot.name}</b></div></div>
   <div className="profession-progress"><div><span>{active?(f.phase==='bite'?'BITE PHASE':'LANDING PHASE'):'NEXT BITE'}</span><b>{fish?.name ?? `${(fishingBiteTime(g)/1000).toFixed(2)}s base`}</b></div><ActionProgress active={active} remainingMs={f.timer||fishingBiteTime(g)} durationMs={f.phase==='landing'&&fish?fishingLandingTime(g,fish):fishingBiteTime(g)} phaseKey={`fishing:${f.actionSerial}`} label="Fishing phase progress" tone="xp"/></div>
   {fish&&<div className="fish-reveal"><span>REELING IN</span><strong>{fish.name}</strong><small>{fish.fight} Fight  /  {fish.xp} XP ?? quantity</small></div>}
   <div className="profession-actions"><label>BAIT<select value={f.bait ?? ''} onChange={e=>change({bait:e.target.value||null})}><option value="">None</option>{['worm','insect','fish_strip','shell','luminous'].map(id=><option key={id} value={`fishing.bait.${id}`}>{id.replace('_',' ')}  /  {g.bank[`fishing.bait.${id}` as ItemId] ?? 0}</option>)}</select></label><Button tone="copper" disabled={!active&&g.skills.Fishing.level<spot.unlockLevel} onClick={active?stop:start}>{active?'Stop Fishing':'Start Fishing'}</Button></div>
  </Panel>
  <Panel className="profession-inspector" title="Catch Pool" action={<span className="tiny-label">LIVE WEIGHTS</span>}>
   <div className="catch-pool-v2">{pool.map(({fish:item,percent})=><article className={`catch-card-v2 rarity-${item.rarity.toLowerCase().replace(' ','-')} ${f.selectedFish===item.id?'selected':''}`} key={item.id}><GameItemFrame id={item.id} size="compact" state={item.rarity==='Very Rare'||item.rarity==='Rare'?'reward':'normal'} tier={item.tier}/><div><b>{item.name}</b><small>{item.water} · {item.cookingClass}{item.predator?' · Predator':''}</small></div><strong>{percent.toFixed(2)}<small>%</small></strong><span className="catch-card-footer"><i>{item.rarity}</i><i>{item.xp} Fishing XP</i><i>Cook: {item.cookingClass}</i></span></article>)}</div>
   <div className="fishing-rig-controls"><div className="rig-control-title"><Icon name="hook" size={16}/><b>Line setup</b><small>Rod · tackle · bait</small></div><div className="fishing-controls"><label>TACKLE<select value={f.tackle ?? ''} onChange={e=>change({tackle:e.target.value||null})}><option value="">No tackle</option>{FISHING_TACKLE.filter(t=>t.level<=g.skills.Fishing.level).map(t=><option key={t.id} value={t.id}>{t.name}  /  Fishing {t.level}</option>)}</select></label><label>SPECIALIZATION<select value={f.specialization ?? ''} disabled={g.skills.Fishing.level<35||active} onChange={e=>change({specialization:e.target.value||null})}><option value="">None</option>{['Provisioner','Trophy Angler','Deepwater Fisher'].map(x=><option key={x}>{x}</option>)}</select></label>{g.skills.Fishing.level>=95&&<label>PREFERRED SPECIES<select value={f.preferredSpecies ?? ''} disabled={active} onChange={e=>change({preferredSpecies:e.target.value||null})}><option value="">None</option>{FISH_SPECIES.filter(x=>x.spotId===spot.id&&x.unlockLevel<=g.skills.Fishing.level).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div>
   <div className="fishing-controls bait-shop-v2">{['worm','insect','luminous'].map(b=><Button key={b} tone="quiet" onClick={()=>buyBait(`fishing.bait.${b}`)}>Buy {b}  /  1g</Button>)}</div></div>
   <div className="spot-find"><span>AQUATIC FIND</span><b>{spot.findName}</b><small>{(spot.findChance*100).toFixed(1)}% per landed catch  /  Fishing XP {g.skills.Fishing.level}</small></div>
  </Panel>
  <Panel className="profession-stats" title="Angler Record"><div className="stat-strip"><div><span>Session XP</span><b>{Math.round(f.sessionXp).toLocaleString()}</b></div><div><span>Fish Landed</span><b>{Object.values(f.sessionFish).reduce<number>((a,n)=>a+(n ?? 0),0)}</b></div><div><span>Species Caught</span><b>{Object.keys(f.sessionFish).length}</b></div></div>{active&&<Bar value={f.phase==='bite'?1:0} max={1} label="Bite state"/>}</Panel>
  </div>
 </div>;
}
