import { Badge, Bar, Button, Panel } from '../../../ui/primitives';
import { ScreenHeading } from '../../../ui/game/ScreenPrimitives';
import { ActionProgress } from '../../../ui/game/ActionProgress';
import { FISHING_RODS, FISHING_SPOTS, FISH_SPECIES, FISHING_TACKLE } from '../../../game/content/fishing/fishingContent';
import { fishingBiteTime, fishingCatchWeights, fishingLandingTime, type ItemId, type SaveState } from '../../../game/game';

export function FishingScreen({game:g,start,stop,selectSpot,change,bridgeRod,buyBait}: {game:SaveState;start:()=>void;stop:()=>void;selectSpot:(id:string)=>void;change:(patch:Partial<SaveState['fishing']>)=>void;bridgeRod:()=>void;buyBait:(id:string)=>void}) {
 const f=g.fishing, spot=FISHING_SPOTS.find(x=>x.id===f.spot)!, rod=FISHING_RODS.find(x=>x.id===f.rod)??FISHING_RODS[0]!, fish=FISH_SPECIES.find(x=>x.id===f.selectedFish), active=g.activity==='fishing', pool=fishingCatchWeights(g), rodIndex=FISHING_RODS.findIndex(x=>x.id===rod.id), nextRod=FISHING_RODS[rodIndex+1];
 return <div className="screen profession-screen fishing-screen"><ScreenHeading eyebrow="PROFESSION · OPEN WATER" title="Fishing" sub="Read the pool, set your tackle, then let the line work." accent="mining"><Badge tone={active?'live':'level-badge'}>LEVEL {g.skills.Fishing.level}</Badge></ScreenHeading>
  <div className="profession-grid"><Panel className="profession-rail" title="Fishing Spots">{FISHING_SPOTS.map((s)=>{const locked=g.skills.Fishing.level<s.unlockLevel,selected=s.id===spot.id;return <button className={`profession-choice ${selected?'selected':''}`} key={s.id} disabled={locked} onClick={()=>selectSpot(s.id)}><span className="choice-tier">T{s.tier}</span><span><b>{s.name}</b><small>{locked?`Fishing ${s.unlockLevel}`:`${FISH_SPECIES.filter(x=>x.spotId===s.id&&x.unlockLevel<=g.skills.Fishing.level).length}/4 species · ${s.findName}`}</small></span></button>;})}
   <div className="profession-bridge"><span className="tiny-label">PHASE 1 ANGLER ROD BRIDGE</span><b>{rod.name} · Power {rod.power}</b>{nextRod&&<><small>Next: {nextRod.name} · requires 1 {spot.findName} from its source Spot.</small><Button tone="quiet" onClick={bridgeRod}>Make next rod</Button></>}</div>
  </Panel>
  <Panel className="profession-focus" title={spot.name} action={<Badge tone={active?'live':''}>{active?(f.phase==='bite'?'BITE':'LANDING'):'READY'}</Badge>}>
   <div className="water-scene"><div className="water-ripple ripple-one"/><div className="water-ripple ripple-two"/><span className="line-float">{f.phase==='bite'?'⌁':fish?'◉':'⌁'}</span><small>{fish?`${fish.rarity.toUpperCase()} · ${fish.name}`:'WAITING FOR A BITE'}</small></div>
   <div className="profession-progress"><div><span>{active?(f.phase==='bite'?'BITE PHASE':'LANDING PHASE'):'NEXT BITE'}</span><b>{fish?.name??`${(fishingBiteTime(g)/1000).toFixed(2)}s base`}</b></div><ActionProgress active={active} remainingMs={f.timer||fishingBiteTime(g)} durationMs={f.phase==='landing'&&fish?fishingLandingTime(g,fish):fishingBiteTime(g)} phaseKey={`${f.phase}:${f.selectedFish??f.timer}`} label="Fishing phase progress" tone="xp"/></div>
   {fish&&<div className="fish-reveal"><span>REELING IN</span><strong>{fish.name}</strong><small>{fish.fight} Fight · {fish.xp} XP × quantity</small></div>}
   <div className="profession-actions"><label>BAIT<select value={f.bait??''} onChange={e=>change({bait:e.target.value||null})}><option value="">None</option>{['worm','insect','fish_strip','shell','luminous'].map(id=><option key={id} value={`fishing.bait.${id}`}>{id.replace('_',' ')} · {g.bank[`fishing.bait.${id}` as ItemId]??0}</option>)}</select></label><Button tone="copper" disabled={!active&&g.skills.Fishing.level<spot.unlockLevel} onClick={active?stop:start}>{active?'Stop Fishing':'Start Fishing'}</Button></div>
  </Panel>
  <Panel className="profession-inspector" title="Catch Pool" action={<span className="tiny-label">LIVE WEIGHTS</span>}>
   <div className="pool-table"><div className="pool-row pool-head"><span>SPECIES</span><span>RARITY</span><span>POOL</span><span>XP</span></div>{pool.map(({fish:item,percent})=><div className={`pool-row ${f.selectedFish===item.id?'is-current':''}`} key={item.id}><span><b>{item.name}</b><small>{item.water}{item.predator?' · Predator':''} · {item.cookingClass}</small></span><span>{item.rarity}</span><strong>{percent.toFixed(2)}%</strong><span>{item.xp}</span></div>)}</div>
   <div className="fishing-controls"><label>TACKLE<select value={f.tackle??''} onChange={e=>change({tackle:e.target.value||null})}><option value="">No tackle</option>{FISHING_TACKLE.filter(t=>t.level<=g.skills.Fishing.level).map(t=><option key={t.id} value={t.id}>{t.name} · Fishing {t.level}</option>)}</select></label><label>SPECIALIZATION<select value={f.specialization??''} disabled={g.skills.Fishing.level<35||active} onChange={e=>change({specialization:e.target.value||null})}><option value="">None</option>{['Provisioner','Trophy Angler','Deepwater Fisher'].map(x=><option key={x}>{x}</option>)}</select></label>{g.skills.Fishing.level>=95&&<label>PREFERRED SPECIES<select value={f.preferredSpecies??''} disabled={active} onChange={e=>change({preferredSpecies:e.target.value||null})}><option value="">None</option>{FISH_SPECIES.filter(x=>x.spotId===spot.id&&x.unlockLevel<=g.skills.Fishing.level).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div>
   <div className="fishing-controls">{['worm','insect','luminous'].map(b=><Button key={b} tone="quiet" onClick={()=>buyBait(`fishing.bait.${b}`)}>Buy {b} · 1g</Button>)}</div>
   <div className="spot-find"><span>AQUATIC FIND</span><b>{spot.findName}</b><small>{(spot.findChance*100).toFixed(1)}% per landed catch · Fishing XP {g.skills.Fishing.level}</small></div>
  </Panel>
  <Panel className="profession-stats" title="Angler Record"><div className="stat-strip"><div><span>Fishing XP</span><b>{Math.round(f.sessionXp).toLocaleString()}</b></div><div><span>Fish Landed</span><b>{Object.values(f.sessionFish).reduce<number>((a,n)=>a+(n??0),0)}</b></div><div><span>Species Mastery</span><b>{Object.keys(f.mastery).length}/40</b></div></div>{active&&<Bar value={f.phase==='bite'?1:0} max={1} label="Bite state"/>}</Panel>
  </div>
 </div>;
}
