import { useMemo, useState } from 'react';
import { Badge, Bar, Button, Panel } from '../../../ui/primitives';
import { ItemMark } from '../../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime, formatDuration } from '../../../ui/game/formatters';
import { MINING_DEPOSITS, MINING_STAGE_MODEL, MINING_TOOLS, type DepositId, type ItemId, type SaveState } from '../../../game/game';
import { getDepositStageDensity, getMiningPower, getMiningStrikeTime, getPrimaryExpectedQuantity } from '../../../game/systems/gameMath';
import { ActionProgress } from '../../../ui/game/ActionProgress';
import { canMineDeposit } from '../../../game/systems/mining/miningResolver';
type Metrics={outputs:Partial<Record<ItemId,number>>;Mining:{xpHour:number}};
export function MiningScreen({game:g,xp,maxXp,start,stop,select,equipTool,speedMultiplier=1,metrics}:{game:SaveState;xp:number;maxXp:number;start:()=>void;stop:()=>void;select:(id:DepositId)=>void;equipTool?:(item:ItemId)=>void;speedMultiplier?:number;metrics?:Metrics}){
 const [tier,setTier]=useState('All'),[category,setCategory]=useState('All'),[query,setQuery]=useState('');const active=g.activity==='mining',deposit=MINING_DEPOSITS[g.mining.deposit],runtime=g.mining.deposits[g.mining.deposit]!,stage=MINING_STAGE_MODEL[runtime.stageIndex]!,tool=MINING_TOOLS[(g.equipped.miningTool??'item.mining.worn_pickaxe') as keyof typeof MINING_TOOLS];
 const power=getMiningPower(tool.power,deposit.category==='Deep-Core'?(tool.effects.deepCorePowerMultiplier??1):1),strikeMs=getMiningStrikeTime(deposit.strikeMs,tool.speed),maxDensity=getDepositStageDensity(runtime.stageIndex,deposit.id),strikes=Math.ceil(runtime.densityRemaining/power),rate=metrics?.outputs[deposit.primary]??0;
 const deposits=useMemo(()=>Object.values(MINING_DEPOSITS).filter(d=>(tier==='All'||String(d.tier)===tier)&&(category==='All'||d.category===category)&&d.name.toLowerCase().includes(query.toLowerCase())),[tier,category,query]);
 const cycleMs=MINING_STAGE_MODEL.reduce((sum,_,i)=>sum+Math.ceil(getDepositStageDensity(i,deposit.id)/power)*strikeMs,0);
 return <div className="screen mining-screen" data-profession="mining"><ScreenHeading eyebrow="PROFESSION · UNDERGROUND" title="Mining" sub="Choose a deposit, read its strata, and work each seam down to the core." accent="mining"><Badge tone="level-badge">LEVEL {g.skills.Mining.level}</Badge></ScreenHeading>
  <div className="mine-layout"><Panel className="deposit-rail" title="Deposits" action={<Badge>{Object.keys(MINING_DEPOSITS).length} SITES</Badge>}><div className="recipe-filters"><select aria-label="Deposit tier" value={tier} onChange={e=>setTier(e.target.value)}><option>All</option>{[1,2,3,4,5,6,7,8,9,10].map(x=><option key={x} value={x}>Tier {x}</option>)}</select><select aria-label="Deposit type" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{['Ore','Quarry','Catalyst','Gem','Essence','Deep-Core'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Search deposits" placeholder="Search deposits" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="deposit-browser">{deposits.map(entry=>{const levelLocked=g.skills.Mining.level<entry.unlockLevel,toolLocked=!levelLocked&&!canMineDeposit(g,entry.id),locked=levelLocked||toolLocked||Boolean(entry.endgameGated),selected=entry.id===deposit.id;return <button className={`deposit-selected ${selected?'selected':''} ${locked?'locked':''}`} key={entry.id} onClick={()=>!locked&&select(entry.id)} disabled={locked} aria-pressed={selected}><span className="selection-edge"/><ItemMark id={entry.primary}/><div className="deposit-label"><b>{entry.name}</b><small>T{entry.tier} · {entry.category} · {entry.endgameGated?'Endgame requirement not yet available':levelLocked?`Mining ${entry.unlockLevel} required`:toolLocked?`${MINING_TOOLS[entry.requiredTool as keyof typeof MINING_TOOLS]?.name??'Required pickaxe'} required`:entry.resourceName}</small></div><Badge tone={locked?'missing':selected?'live':'ready'}>{entry.endgameGated?'ENDGAME':toolLocked?'TOOL':levelLocked?`LV ${entry.unlockLevel}`:selected?'ACTIVE':'READY'}</Badge></button>})}</div><div className="deposit-req"><div><span>REQUIRES</span><b>Mining {deposit.unlockLevel}</b></div><div><span>PICKAXE</span><b>{MINING_TOOLS[deposit.requiredTool as keyof typeof MINING_TOOLS]?.name??'—'}</b></div><div><span>YIELDS</span><b>{deposit.resourceName} ×{deposit.baseQuantity}</b></div><div><span>STRIKE</span><b>{(deposit.strikeMs/1000).toFixed(2)}s</b></div></div></Panel>
   <Panel className={`mine-focus ${active?'is-active':''}`}><div className="focus-top"><div><span className="screen-overline">TIER {deposit.tier} · {deposit.category.toUpperCase()}</span><h2>{deposit.name}</h2></div><Badge tone={active?'live':''}>{active?'MINING':'READY'}</Badge></div><div className={`vein-art mining-impact ${deposit.category==='Quarry'?'stone-vein-art':''}`}><div className="cave-ridge ridge-a"/><div className="cave-ridge ridge-b"/><div className="ore-face"><i/><i/><i/><i/><i/></div><div className="ore-glint g1"/><div className="ore-glint g2"/><div className="vein-depth"><span>{deposit.resourceName.toUpperCase()}</span><b>{String(runtime.stageIndex+1).padStart(2,'0')} / 05</b></div><div className="vein-vignette"/></div>
    <div className="stage-name-line"><div><span className="tiny-label">CURRENT LAYER</span><h3>{stage.name}</h3></div><div className="stage-reward"><span>EXPECTED PRIMARY</span><b><ItemMark id={deposit.primary}/> {getPrimaryExpectedQuantity(runtime.stageIndex,deposit.id).toFixed(2)}× {deposit.resourceName}</b></div></div><div className="bar-label"><span>Stage Density</span><b>{runtime.densityRemaining.toFixed(1)} <small>/ {maxDensity}</small></b></div><Bar value={runtime.densityRemaining} max={maxDensity} accent="copper" className="density-bar" label={`${strikes} strikes remaining`}/><div className="mine-action-progress"><div><span className="tiny-label">NEXT SWING</span><b>{active?formatActionTime(g.mining.timer):formatActionTime(strikeMs)}</b></div><ActionProgress active={active} remainingMs={g.mining.timer||strikeMs} durationMs={strikeMs} phaseKey={`${deposit.id}:${g.mining.strikes}`} speedMultiplier={speedMultiplier} label="Mining swing progress"/></div><div className="mine-controls"><div className="strike-readout"><span className={`pulse-dot ${active?'pulsing':''}`}/><div><b>{active?'Next strike':'Strike time'}</b><small>{formatActionTime(strikeMs)} · {power} power</small></div></div><Button tone="copper" onClick={active?stop:start}>{active?'Stop Mining':'Start Mining'}</Button></div><div className="stage-path">{MINING_STAGE_MODEL.map((item,index)=><div key={item.id} className={`stage-node ${index<runtime.stageIndex?'complete':''} ${index===runtime.stageIndex?'current':''}`}><div className="node-head"><span className="node-mark">{index<runtime.stageIndex?'✓':`0${index+1}`}</span><span className="node-join"/></div><b>{item.name}</b><small>×{getPrimaryExpectedQuantity(index,deposit.id).toFixed(2)} · {index<runtime.stageIndex?'cleared':index===runtime.stageIndex?'here now':'ahead'}</small></div>)}</div></Panel>
   <Panel className="mine-inspector" title="Field Readings"><div className="tool-card"><div className="tool-insignia"><ItemMark id={tool.item}/></div><div><span className="tiny-label">EQUIPPED PICKAXE</span><b>{tool.name}</b><small>Power {tool.power} · Speed +{Math.round(tool.speed*100)}% · {tool.effect}</small></div><Badge tone="equipped">EQUIPPED</Badge></div><div className="stat-rows"><Stat label="Mining Power" value={`${power}`}/><Stat label="Final strike time" value={formatActionTime(strikeMs)}/><Stat label="Primary extra quantity" value={`${tool.extraQuantityChance+(tool.effects.primaryExtraPp??0)} pp`}/><Stat label={`${deposit.resourceName} / hour`} value={rate?Math.round(rate).toLocaleString():'Estimating…'} accent="copper-text"/><Stat label="Mining XP / hour" value={metrics?.Mining.xpHour?Math.round(metrics.Mining.xpHour).toLocaleString():'Estimating…'} accent="xp-text"/><Stat label="Next Mining level ETA" value={metrics?.Mining.xpHour?formatDuration(Math.max(0,maxXp-xp)/metrics.Mining.xpHour*3_600_000):'Estimating…'}/><Stat label="Stage strikes" value={`${strikes} remaining`}/><Stat label="Full stage cycle" value={`~${formatDuration(cycleMs)}`}/><Stat label="Completed cycles" value={fmt(runtime.cyclesCompleted)}/></div><div className="xp-block"><div><span>Mining XP</span><b>Lv. {g.skills.Mining.level}</b></div><Bar value={xp} max={maxXp} accent="xp"/><small>{fmt(xp)} / {fmt(maxXp)} XP to next level</small></div>{equipTool&&<div className="tool-upgrades">{Object.values(MINING_TOOLS).filter(t=>t.item!==tool.item&&(g.bank[t.item]??0)>0).map(t=><Button key={t.item} tone="quiet" onClick={()=>equipTool(t.item)}>{t.name} · Power {t.power}</Button>)}</div>}</Panel>
  </div></div>;
}
