import { useState } from 'react';
import { Badge, Bar, Button, Icon, Modal, Panel } from '../../../ui/primitives';
import { ItemMark, ItemTip } from '../../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime, formatDuration } from '../../../ui/game/formatters';
import { MINING_DEPOSITS, MINING_STAGE_MODEL, MINING_TOOLS, MINING_MASTERY_EFFECTS, type DepositId, type ItemId, type SaveState } from '../../../game/game';
import { getDepositStageDensity, getMiningPower, getMiningStrikeTime, getPrimaryExpectedQuantity, masteryXpToNext, masteryXpIntoLevel } from '../../../game/systems/gameMath';
import { ActionProgress } from '../../../ui/game/ActionProgress';

type MiningMetrics = { outputs: Partial<Record<ItemId, number>>; masteryXpHour?: number; Mining: { xpHour: number } };
export function MiningScreen({ game: g, xp, maxXp, start, stop, select, equipTool, speedMultiplier = 1, metrics }: { game: SaveState; xp: number; maxXp: number; start: () => void; stop: () => void; select: (id: DepositId) => void; equipTool?: (item: ItemId) => void; speedMultiplier?: number; metrics?: MiningMetrics }) {
 const [pendingDeposit, setPendingDeposit] = useState<DepositId | null>(null);
 const active = g.activity === 'mining', deposit = MINING_DEPOSITS[g.mining.deposit], runtime = g.mining.deposits[g.mining.deposit]!, stage = MINING_STAGE_MODEL[runtime.stageIndex]!, tool = MINING_TOOLS[(g.equipped.miningTool ?? 'item.mining.worn_pickaxe') as keyof typeof MINING_TOOLS];
 const currentMax = getDepositStageDensity(runtime.stageIndex, deposit.id), remaining = runtime.densityRemaining, mastery = runtime.mastery, power = getMiningPower(tool.power, mastery.level, runtime.stageIndex), strikeMs = getMiningStrikeTime(deposit.strikeMs, tool.speed);
 const strikesRemaining = Math.ceil(remaining / power), cycleStrikes = MINING_STAGE_MODEL.reduce((sum, _, i) => sum + Math.ceil(getDepositStageDensity(i, deposit.id) / getMiningPower(tool.power, mastery.level, i)), 0);
 const cycleMs = MINING_STAGE_MODEL.reduce((sum, _, i) => sum + Math.ceil(getDepositStageDensity(i, deposit.id) / getMiningPower(tool.power, mastery.level, i)) * strikeMs, 0);
 const nextMilestone = [10,25,50,75,100].find((level) => mastery.level < level), masteryXpNext = masteryXpToNext(mastery), rate = metrics?.outputs[deposit.primary] ?? 0;
 const switchTo = (id: DepositId) => { if (id === deposit.id) return; if (remaining < currentMax) { setPendingDeposit(id); return; } select(id); };
 const confirmSwitch = () => { if (pendingDeposit) select(pendingDeposit); setPendingDeposit(null); };
 return <div className="screen mining-screen" data-profession="mining"><ScreenHeading eyebrow="PROFESSION · TIER 1" title="Mining" sub="Choose a deposit, read its strata, and work each seam down to the core." accent="mining"><Badge tone="level-badge">LEVEL {g.skills.Mining.level}</Badge></ScreenHeading>
  <div className="mine-layout">
   <Panel className="deposit-rail" title="Deposits">{Object.values(MINING_DEPOSITS).map((entry) => { const locked = g.skills.Mining.level < entry.unlockLevel, selected = entry.id === deposit.id, entryMastery = g.mining.deposits[entry.id]?.mastery ?? { xp: 0, level: 1 }; return <button className={`deposit-selected ${selected ? 'selected' : ''} ${locked ? 'locked' : ''}`} key={entry.id} onClick={() => !locked && switchTo(entry.id)} disabled={locked} aria-pressed={selected}><span className="selection-edge"/><ItemMark id={entry.primary}/><div className="deposit-label"><b>{entry.name}</b><small>{entry.resourceName} · {entry.category}</small></div><Badge tone={locked ? 'missing' : selected ? 'live' : 'ready'}>{locked ? `MINING ${entry.unlockLevel}` : selected ? 'ACTIVE' : `M. ${entryMastery.level}`}</Badge></button>; })}
    <div className="deposit-req"><div><span>DEPOSIT</span><b>{deposit.category}</b></div><div><span>REQUIRES</span><b>Mining {deposit.unlockLevel}</b></div><div><span>YIELDS</span><b>{deposit.resourceName}</b></div><div><span>BASE STRIKE</span><b>{(deposit.strikeMs / 1000).toFixed(2)}s</b></div></div>
    <div className="rail-bottom"><span className="tiny-label">{deposit.name.toUpperCase()} CYCLES</span><b>{fmt(runtime.cyclesCompleted)}</b></div>
   </Panel>
   <Panel className={`mine-focus ${active ? 'is-active' : ''}`}><div className="focus-top"><div><span className="screen-overline">{deposit.category.toUpperCase()}</span><h2>{deposit.name}</h2></div><Badge tone={active ? 'live' : ''}>{active ? 'MINING' : 'READY'}</Badge></div>
    <div key={`${deposit.id}-${g.mining.strikes}`} className={`vein-art mining-impact ${deposit.id === 'mining.deposit.fieldstone_quarry' ? 'stone-vein-art' : ''}`} aria-label={`Illustration of ${deposit.name}`}><div className="cave-ridge ridge-a"/><div className="cave-ridge ridge-b"/><div className="ore-face"><i/><i/><i/><i/><i/></div><div className="ore-glint g1"/><div className="ore-glint g2"/><div className="vein-depth"><span>{deposit.resourceName.toUpperCase()}</span><b>{String(runtime.stageIndex + 1).padStart(2, '0')} / 05</b></div><div className="vein-vignette"/></div>
    <div className="stage-name-line"><div><span className="tiny-label">CURRENT LAYER</span><h3>{stage.name}</h3></div><div className="stage-reward"><span>EXPECTED PRIMARY</span><b><ItemTip id={deposit.primary}><ItemMark id={deposit.primary}/></ItemTip> {getPrimaryExpectedQuantity(runtime.stageIndex, deposit.id).toFixed(2)}× {deposit.resourceName}</b></div></div>
    <div className="bar-label"><span>Stage Density</span><b>{remaining.toFixed(1)} <small>/ {currentMax}</small></b></div><Bar value={remaining} max={currentMax} accent="copper" className="density-bar" label={`${strikesRemaining} strikes remaining`} />
    <div className="mine-action-progress"><div><span className="tiny-label">NEXT SWING</span><b>{active ? formatActionTime(g.mining.timer) : formatActionTime(strikeMs)}</b></div><ActionProgress active={active} remainingMs={g.mining.timer || strikeMs} durationMs={strikeMs} phaseKey={`${deposit.id}-${g.mining.strikes}`} speedMultiplier={speedMultiplier} label="Mining swing progress"/></div>
    <div className="mine-controls"><div className="strike-readout"><span className={`pulse-dot ${active ? 'pulsing' : ''}`} /><div><b>{active ? 'Next strike' : 'Strike time'}</b><small>{formatActionTime(strikeMs)} · {power.toFixed(power % 1 ? 2 : 0)} power</small></div></div><Button tone="copper" onClick={active ? stop : start} className="mine-action">{active ? 'Stop Mining' : 'Start Mining'}<span className="button-key">{active ? 'Ⅱ' : '▶'}</span></Button></div>
    <div className="stage-path">{MINING_STAGE_MODEL.map((item, index) => { const expected = getPrimaryExpectedQuantity(index, deposit.id); return <div key={item.id} className={`stage-node ${index < runtime.stageIndex ? 'complete' : ''} ${index === runtime.stageIndex ? 'current' : ''}`}><div className="node-head"><span className="node-mark">{index < runtime.stageIndex ? '✓' : `0${index + 1}`}</span><span className="node-join" /></div><b>{item.name}</b><small>×{expected.toFixed(2)} · {index < runtime.stageIndex ? 'cleared' : index === runtime.stageIndex ? 'here now' : 'ahead'}</small></div>; })}</div>
   </Panel>
   <Panel className="mine-inspector" title="Field Readings"><div className="tool-card"><div className="tool-insignia"><ItemTip id={tool.item}><Icon name={tool.icon} size={25}/></ItemTip></div><div><span className="tiny-label">EQUIPPED PICKAXE</span><b>{tool.name}</b><small>Power {tool.power}{tool.speed ? ` · Speed +${Math.round(tool.speed * 100)}% · Primary quantity +${tool.extraQuantityChance} pp` : ' · Starter tool'}</small></div><Badge tone="equipped">EQUIPPED</Badge></div>
    {equipTool && g.bank['item.mining.copper_pickaxe'] && g.equipped.miningTool !== 'item.mining.copper_pickaxe' && <Button tone="quiet" className="wide-action" onClick={() => equipTool('item.mining.copper_pickaxe')}>Equip Copper Pickaxe</Button>}
    <div className="stat-rows"><Stat label="Mining Power" value={power.toFixed(power % 1 ? 2 : 0)} tip="Pickaxe power modified by this Deposit's Mastery."/><Stat label="Final strike time" value={formatActionTime(strikeMs)}/><Stat label="Primary extra quantity" value={`${tool.extraQuantityChance + (mastery.level >= 25 ? 5 : 0)} pp`}/><Stat label={`${deposit.resourceName} / hour`} value={rate ? Math.round(rate).toLocaleString() : 'Estimating…'} accent="copper-text"/><Stat label="Mining XP / hour" value={metrics?.Mining.xpHour ? Math.round(metrics.Mining.xpHour).toLocaleString() : 'Estimating…'} accent="xp-text"/><Stat label="Mastery XP / hour" value={metrics?.masteryXpHour ? Math.round(metrics.masteryXpHour).toLocaleString() : 'Estimating…'}/><Stat label="Next Mining level ETA" value={metrics?.Mining.xpHour ? formatDuration(Math.max(0, maxXp - xp) / metrics.Mining.xpHour * 3_600_000) : 'Estimating…'}/><Stat label="Stage strikes" value={`${strikesRemaining} remaining`}/><Stat label="Full cycle" value={`~${formatDuration(cycleMs)}`}/><Stat label="Completed cycles" value={fmt(runtime.cyclesCompleted)}/></div>
    <div className="xp-block"><div><span>Mining XP</span><b>Lv. {g.skills.Mining.level}</b></div><Bar value={xp} max={maxXp} accent="xp"/><small>{fmt(xp)} / {fmt(maxXp)} XP to next level</small></div>
    <div className="mastery-block"><div><span>{deposit.name} Mastery</span><b>Level {mastery.level}</b></div><Bar value={masteryXpIntoLevel(mastery)} max={masteryXpNext || 1} accent="steel"/><small>{mastery.level >= 100 ? 'Mastery complete' : `${fmt(masteryXpIntoLevel(mastery))} / ${fmt(masteryXpNext)} Mastery XP · Next: M${nextMilestone ?? 100} · ${MINING_MASTERY_EFFECTS[nextMilestone ?? 100]}`}</small></div>
    <div className="cycle-block"><div className="cycle-meta"><span>Lifetime {deposit.resourceName}</span><b>{fmt(runtime.totalPrimary)} <ItemMark id={deposit.primary}/></b></div><Bar value={runtime.totalStagesCompleted % MINING_STAGE_MODEL.length} max={MINING_STAGE_MODEL.length} accent="steel"/><div className="cycle-footer"><span>Stages completed</span><b>{fmt(runtime.totalStagesCompleted)} · {cycleStrikes} strikes/cycle</b></div></div>
   </Panel>
  </div>
  {pendingDeposit && <Modal title="Switch Deposit?" eyebrow="MINING PROGRESS" onClose={() => setPendingDeposit(null)} className="confirm-modal"><p>Switching now abandons progress on the current <b>{stage.name}</b>. Completed Stage rewards are already safe.</p><div className="confirm-actions"><Button onClick={() => setPendingDeposit(null)}>Cancel</Button><Button tone="copper" onClick={confirmSwitch}>Switch Deposit</Button></div></Modal>}
 </div>;
}
