import { useMemo, useState } from 'react';
import { Badge, Button, Panel } from '../../ui/primitives';
import { ItemMark } from '../../ui/game/ItemDisplay';
import { ScreenHeading } from '../../ui/game/ScreenPrimitives';
import { fmt } from '../../ui/game/formatters';
import { ITEMS, MELEE_WEAPONS, maxHitpoints, getPlayerAttackInterval, getPlayerResistances, canEquip, type ItemId, type SaveState } from '../../game/game';
import type { EquipmentMeta } from '../../game/content/items/itemRegistry';

type CombatSlot='weapon'|'head'|'armor'|'hands'|'feet'|'offhand';
type Profession='Mining'|'Smithing'|'Fishing'|'Cooking';
type EquipSlot=CombatSlot|'miningTool'|'smithingHammer';
const COMBAT_SLOTS:CombatSlot[]=['weapon','offhand','head','armor','hands','feet'];
const PROFESSIONS:Profession[]=['Mining','Smithing','Fishing','Cooking'];
const SLOT_LABEL:Record<string,string>={weapon:'Weapon',head:'Head',armor:'Armor',hands:'Hands',feet:'Feet',offhand:'Off-hand',miningTool:'Pickaxe',smithingHammer:'Hammer',Rod:'Rod',Tackle:'Tackle',Knife:'Knife'};
const lowerSlot=(value:string)=>value.toLowerCase()==='off-hand'?'offhand':value.toLowerCase();
const equippedSlot=(g:SaveState,slot:string):ItemId|null=>slot==='weapon'?g.equipped.weapon:slot==='head'?g.equipped.head:slot==='armor'?g.equipped.armor:slot==='hands'?g.equipped.hands:slot==='feet'?g.equipped.feet:slot==='offhand'?g.equipped.offhand:slot==='Pickaxe'?g.equipped.miningTool:slot==='Hammer'?g.equipped.smithingHammer:slot==='Rod'?g.fishing.rod:slot==='Knife'?g.cooking.knife:slot==='Tackle'?g.fishing.tackle as ItemId|null:null;
const slotArg=(slot:string):EquipSlot|null=>{const normalized=lowerSlot(slot);return normalized==='weapon'||normalized==='head'||normalized==='armor'||normalized==='hands'||normalized==='feet'||normalized==='offhand'?normalized:normalized==='pickaxe'?'miningTool':normalized==='hammer'?'smithingHammer':null;};
const itemMeta=(id:ItemId):EquipmentMeta|undefined=>ITEMS[id]?.equipment;
const metaStats=(id:ItemId|null)=>id?itemMeta(id)?.stats ?? {}:{};

export function EquipmentScreen({game:g,equip,unequip,equipProfession}:{game:SaveState;equip:(item:ItemId,slot:EquipSlot)=>void;unequip:(slot:EquipSlot)=>void;equipProfession?:(item:ItemId)=>void}){
 const [mode,setMode]=useState<'Combat'|'Profession'>('Combat'),[profession,setProfession]=useState<Profession>('Mining'),[slot,setSlot]=useState('weapon'),[query,setQuery]=useState(''),[showUnowned,setShowUnowned]=useState(false),[family,setFamily]=useState('All'),[selected,setSelected]=useState<ItemId|null>(null);
 const availableSlots=mode==='Combat'?COMBAT_SLOTS:profession==='Mining'?['Pickaxe']:profession==='Smithing'?['Hammer']:profession==='Fishing'?['Rod','Tackle']:['Knife'];
 const selectedSlot=availableSlots.includes(slot as never)?slot:availableSlots[0]!;const current=equippedSlot(g,selectedSlot);
 const candidates=useMemo(()=>Object.entries(ITEMS).flatMap(([raw,item])=>{const id=raw as ItemId,meta=item.equipment;if(!meta)return[];const context=mode==='Combat'?'combat':'profession';if(meta.context!==context)return[];if(context==='profession'&&meta.profession!==profession)return[];if(lowerSlot(meta.slot)!==lowerSlot(selectedSlot))return[];const count=meta.slot==='Tackle'?(g.skills.Fishing.level>=meta.requiredLevel?1:0):(g.bank[id] ?? 0);if(!showUnowned&&count<1&&current!==id)return[];if(family!=='All'&&selectedSlot==='weapon'&&!item.name.toLowerCase().includes(family.toLowerCase().replace('battle axes','axe').replace('swords','sword').replace('maces','mace').replace('spears','spear')))return[];if(family==='Heavy'&&!item.name.toLowerCase().includes('heavy'))return[];if(!item.name.toLowerCase().includes(query.toLowerCase()))return[];if(context==='combat'&&!canEquip(g,id,selectedSlot,false)&&id!==current)return[];return[{id,item,meta,count}]}).sort((a,b)=>b.meta.tier-a.meta.tier||a.item.name.localeCompare(b.item.name)),[mode,profession,selectedSlot,showUnowned,family,query,g.bank,g.equipped,g.skills,current]);
 const activeCandidate=candidates.find(x=>x.id===selected) ?? candidates[0] ?? null;
 const weapon=g.equipped.weapon&&g.equipped.weapon in MELEE_WEAPONS?MELEE_WEAPONS[g.equipped.weapon as keyof typeof MELEE_WEAPONS]:null;
 const resistances=getPlayerResistances(g);
 const equipCandidate=(id:ItemId,meta:EquipmentMeta)=>{const target=slotArg(meta.slot);if(target)equip(id,target);else equipProfession?.(id);setSelected(id);};
 const inspector=activeCandidate, equippedStats=metaStats(current),nextStats=inspector?.meta.stats ?? {};
 const comparisonKeys=Array.from(new Set([...Object.keys(equippedStats),...Object.keys(nextStats)]));
 return <div className="screen equipment-screen"><ScreenHeading eyebrow="LOADOUT · GEAR & TOOLS" title="Equipment" sub="Choose a loadout, inspect owned gear, and compare it with what you have equipped." accent="equipment"><Badge tone="level-badge">LOADOUT</Badge></ScreenHeading>
  <div className="equipment-modes" role="tablist"><button role="tab" aria-selected={mode==='Combat'} className={mode==='Combat'?'selected':''} onClick={()=>{setMode('Combat');setSlot('weapon');setSelected(null);setFamily('All');}}>Combat Loadout</button><button role="tab" aria-selected={mode==='Profession'} className={mode==='Profession'?'selected':''} onClick={()=>{setMode('Profession');setSlot(availableSlots[0]!);setSelected(null);}}>Profession Loadouts</button></div>
  <div className="equipment-layout equipment-picker-layout"><Panel className="loadout-panel" title={mode==='Combat'?'Combat Slots':`${profession} Loadout`}>
    {mode==='Profession'&&<div className="profession-loadout-tabs">{PROFESSIONS.map(p=><button key={p} className={p===profession?'selected':''} onClick={()=>{setProfession(p);setSelected(null);setFamily('All');}}>{p}</button>)}</div>}
    <div className="equipment-slot-tabs">{availableSlots.map(s=>{const id=equippedSlot(g,s);return <button key={s} className={s===selectedSlot?'selected':''} onClick={()=>{setSlot(s);setSelected(null);setFamily('All');}}><span>{SLOT_LABEL[s] ?? s}</span><b>{id?ITEMS[id]?.name ?? 'Equipped':'Empty'}</b></button>})}</div>
    {mode==='Combat'&&<div className="combat-summary-strip"><span>Attack <b>{g.skills.Attack.level}</b></span><span>Defence <b>{g.skills.Defence.level}</b></span><span>HP <b>{Math.ceil(g.combat.playerHp)}/{maxHitpoints(g.skills.Hitpoints.level)}</b></span><span>Interval <b>{(getPlayerAttackInterval(g)/1000).toFixed(2)}s</b></span><span>Style <b>{weapon?.style ?? '—'}</b></span><span>Slash / Pierce / Fire <b>{resistances.Slash}% / {resistances.Pierce}% / {resistances.Fire}%</b></span></div>}
    <div className="loadout-hint">Selecting an equipped slot returns it to the Bank. Candidate lists show owned, compatible gear by default.</div>
    <div className="selected-slot-actions">{current&&slotArg(selectedSlot)&&<Button tone="quiet" onClick={()=>unequip(slotArg(selectedSlot)!)}>Unequip {SLOT_LABEL[selectedSlot] ?? selectedSlot}</Button>}</div>
   </Panel>
   <Panel className="equipment-inspector" title="Item Picker" action={<Badge>{candidates.length} ITEMS</Badge>}>
    <div className="equipment-filters"><label className="sr-only" htmlFor="equipment-search">Search items</label><input id="equipment-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search compatible gear"/>{(selectedSlot==='weapon'?['All','Swords','Battle Axes','Maces','Spears']:selectedSlot==='armor'?['All','Heavy']:[]).map(option=><button type="button" key={option} className={family===option?'selected':''} aria-pressed={family===option} onClick={()=>setFamily(option)}>{option}</button>)}<label><input type="checkbox" checked={showUnowned} onChange={e=>setShowUnowned(e.target.checked)}/> Show unowned</label></div>
    <div className="candidate-list" role="listbox " aria-label={`${SLOT_LABEL[selectedSlot] ?? selectedSlot} candidates`}>{candidates.map(({id,item,meta,count})=><button type="button" role="option" aria-selected={inspector?.id===id} className={`candidate-row ${current===id?'equipped':''} ${inspector?.id===id?'selected':''}`} key={id} onClick={()=>setSelected(id)}><ItemMark id={id}/><span className="candidate-copy"><b>{item.name}</b><small>T{meta.tier} · {meta.skill} {meta.requiredLevel} · {Object.entries(meta.stats).slice(0,2).map(([k,v])=>`${k} ${v}`).join(' · ')}</small></span><span className="candidate-count">×{fmt(count)}</span></button>)}{candidates.length===0&&<p className="empty-copy">No compatible items match this search.</p>}</div>
    {inspector&&<div className="item-compare"><div className="item-compare-heading"><ItemMark id={inspector.id} large/><div><span className="tiny-label">TIER {inspector.meta.tier} · {inspector.item.category.toUpperCase()}</span><h3>{inspector.item.name}</h3><small>{inspector.meta.skill} {inspector.meta.requiredLevel} required · {inspector.meta.slot==='Tackle'?'Unlocked by Fishing level':`Bank ${fmt(inspector.count)}`}</small></div></div><div className="comparison-table"><div className="comparison-header"><span>STAT</span><span>CURRENT</span><span>CANDIDATE</span><span>CHANGE</span></div>{comparisonKeys.length?comparisonKeys.map(key=>{const oldValue=equippedStats[key] ?? '-',newValue=nextStats[key] ?? '-',before=Number(oldValue),after=Number(newValue),numeric=Number.isFinite(before)&&Number.isFinite(after),delta=numeric?after-before:0,lowerBetter=/interval|cooldown|weight/i.test(key),tone=!numeric?'even':delta===0?'even':(lowerBetter?delta<0:delta>0)?'better':'worse';return <div className="comparison-row" key={key}><span>{key}</span><span>{numeric?before:String(oldValue)}</span><span>{numeric?after:String(newValue)}</span><b className={tone}>{numeric?`${delta>0?'+':''}${delta}`:'-'}</b></div>}):<p className="empty-copy">No numeric stats for this slot.</p>}</div><Button tone="copper" disabled={inspector.count<1||current===inspector.id||g.skills[inspector.meta.skill].level<inspector.meta.requiredLevel} onClick={()=>equipCandidate(inspector.id,inspector.meta)}>{current===inspector.id?'Equipped':g.skills[inspector.meta.skill].level<inspector.meta.requiredLevel?`Requires ${inspector.meta.skill} ${inspector.meta.requiredLevel}`:'Equip Item'}</Button></div>}
   </Panel></div>
 </div>;
}
