import { Badge, Button, Icon, Panel } from '../../ui/primitives';
import { ItemMark } from '../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../ui/game/ScreenPrimitives';
import { fmt } from '../../ui/game/formatters';
import { ITEMS, maxHitpoints, type ItemId, type SaveState } from '../../game/game';

export function EquipmentScreen({ game: g, equip, unequip }: { game: SaveState; equip: (item: ItemId, slot: 'weapon' | 'head' | 'armor' | 'hands' | 'feet' | 'offhand') => void; unequip: (slot: 'weapon' | 'head' | 'armor' | 'hands' | 'feet' | 'offhand') => void }) {
 const slots: { name: string; key: 'weapon' | 'offhand' | 'head' | 'armor' | 'hands' | 'feet'; item: ItemId | null }[] = [{ name: 'Weapon', key: 'weapon', item: g.equipped.weapon }, { name: 'Off-hand', key: 'offhand', item: g.equipped.offhand }, { name: 'Head', key: 'head', item: g.equipped.head }, { name: 'Armor', key: 'armor', item: g.equipped.armor }, { name: 'Hands', key: 'hands', item: g.equipped.hands }, { name: 'Feet', key: 'feet', item: g.equipped.feet }, { name: 'Ring', key: 'offhand', item: null }, { name: 'Necklace', key: 'offhand', item: null }];
 const equipmentItems: { id: ItemId; slot: typeof slots[number]['key'] }[] = [{ id: 'sword', slot: 'weapon' }, { id: 'shield', slot: 'offhand' }, { id: 'helm', slot: 'head' }, { id: 'plate', slot: 'armor' }, { id: 'gloves', slot: 'hands' }, { id: 'greaves', slot: 'feet' }];
 const resistance = (slot: string) => slot === 'head' && g.equipped.head === 'helm' ? 2 : slot === 'armor' && g.equipped.armor === 'plate' ? 4 : 0;
 return <div className="screen equipment-screen"><ScreenHeading eyebrow="LOADOUT · TIER 1" title="Equipment" sub="Set your first combat kit before you leave the road behind." accent="equipment"><Badge tone="level-badge">MELEE KIT</Badge></ScreenHeading><div className="equipment-layout"><Panel className="loadout-panel" title="Adventurer Loadout"><div className="loadout-board"><div className="slot-column left-slots">{slots.slice(0, 4).map((slot) => <EquipmentSlot key={slot.name} slot={slot.name} item={slot.item} click={() => slot.item && unequip(slot.key)} />)}</div><div className="character-silhouette"><div className="char-head"/><div className="char-shoulders"/><div className="char-body"><div className="char-buckle"/></div><div className="char-legs"><i/><i/></div><div className="char-glow"/></div><div className="slot-column right-slots">{slots.slice(4).map((slot) => <EquipmentSlot key={slot.name} slot={slot.name} item={slot.item} click={() => slot.item && unequip(slot.key)} />)}</div></div><div className="loadout-hint">Select an equipped slot to return an item to the Bank.</div></Panel><Panel className="equipment-inspector" title="Combat Readiness"><div className="ready-header"><span className="readiness-emblem"><Icon name="sword" size={25}/></span><div><b>{g.equipped.weapon === 'sword' ? 'Copper Sword' : 'No weapon equipped'}</b><small>{g.equipped.head === 'helm' ? 'Copper Helm secured' : 'Add one piece of armor'}</small></div><Badge tone={g.equipped.weapon === 'sword' && g.equipped.head ? 'ready' : 'missing'}>{g.equipped.weapon === 'sword' && g.equipped.head ? 'READY' : 'INCOMPLETE'}</Badge></div><div className="stat-rows combat-statrows"><Stat label="Hitpoints" value={`${Math.max(0, Math.ceil(g.combat.playerHp))} / ${maxHitpoints(g.skills.Hitpoints.level)}`} /><Stat label="Melee Accuracy" value={`${100 + 6 * g.skills.Attack.level + (g.equipped.weapon === 'sword' ? 84 : 0)}`} /><Stat label="Melee Evasion" value={`${100 + 5 * g.skills.Defence.level}`} /><Stat label="Critical Rate" value={g.equipped.weapon === 'sword' ? '6%' : '5%'} /><Stat label="Critical Damage" value="150%" /><Stat label="Slash / Stab resist" value={`${resistance('head') + resistance('armor')}%`} accent="positive" /></div><div className="candidate-list"><span className="tiny-label">AVAILABLE TO EQUIP</span>{equipmentItems.map(({ id, slot }) => <div className="candidate-row" key={id}><ItemMark id={id}/><div><b>{ITEMS[id].name}</b><small>{slot[0].toUpperCase() + slot.slice(1)} · T1</small></div><span className="candidate-count">×{fmt(g.bank[id] ?? 0)}</span><Button tone="quiet" disabled={(g.bank[id] ?? 0) < 1} onClick={() => equip(id, slot)}>Equip</Button></div>)}</div></Panel></div></div>;
}

export function EquipmentSlot({ slot, item, click }: { slot: string; item: ItemId | null; click: () => void }) { return <button className={`equipment-slot ${item ? 'filled' : ''}`} onClick={click} disabled={!item} aria-label={`${slot}: ${item ? ITEMS[item].name + ', click to unequip' : 'empty'}`}><span className="slot-type">{slot}</span>{item ? <><ItemMark id={item}/><b>{ITEMS[item].name.replace('Copper ', '')}</b></> : <span className="empty-rune">+</span>}</button>; }
