import { COMBAT_AREAS, DUNGEONS, ENEMIES, activeSequence } from '../content/combat/t1Enemies';
import { FORGING_RECIPES } from '../content/smithing/forgingRecipes';
import { FORGE_HAMMERS } from '../content/smithing/smithingTools';
import { MINING_DEPOSITS } from '../content/mining/miningDeposits';
import { MINING_TOOLS } from '../content/mining/miningTools';
import { FISHING_SPOTS, FISH_SPECIES } from '../content/fishing/fishingContent';
import { COOKING_KNIVES, COOKING_RECIPES } from '../content/cooking/cookingContent';
import { getMiningStrikeTime, maxHitpoints, xpForLevel } from './gameMath';
import { advanceCombat, clearEncounterStatuses, combatNextBoundary, forceCurrentEnemyDefeat } from './combat/combatResolver';
import { evaluateCombatTierUnlocks } from './combat/combatProgression';
export { evaluateCombatTierUnlocks } from './combat/combatProgression';
import { areaUnlocked, canStartCombat, enemyUnlocked, getPlayerAttackInterval } from './combat/combatMath';
import { canMineDeposit, miningHit, syncMining } from './mining/miningResolver';
import { canStartCooking, cookingMethodTime, cookingPrepTime, resolveRecipeInputs } from './cooking/cookingResolver';
import { canStartFishing, fishingBiteTime, fishingCatchWeights, fishingLandingTime, fishingRod } from './fishing/fishingResolver';
import { getForgeWorkRequired, selectedSmeltRecipe, smithingActionTime, smeltingUnitTime, smeltingWarmupTime } from './smithing/smithingResolver';
export { canStartCooking, cookingMethodTime, cookingPrepTime, resolveCookingInput, resolveRecipeInputs } from './cooking/cookingResolver';
export { canStartFishing, fishingBiteTime, fishingCatchWeights, fishingLandingTime } from './fishing/fishingResolver';
export { getForgeWorkRequired, smithingActionTime, smeltingUnitTime, smeltingWarmupTime } from './smithing/smithingResolver';
export { selectDeposit } from './mining/miningResolver';
export { canMineDeposit } from './mining/miningResolver';
import type { Activity, EnemyId, ForgingRecipeId, GameEvent, ItemId, RecipeId, SaveState, SimulationResult, SkillId } from '../types/gameTypes';

const MIN_WORKING_HEAT = 25, BASE_REHEAT_MS = 2000, BASE_HEAT_LOSS = 10;
const pushLog = (s: SaveState, line: string) => { s.combat.log = [line, ...s.combat.log].slice(0, 8); };
function rand(s: SaveState) { let x = s.rng | 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; s.rng = x >>> 0; return s.rng / 4294967296; }
function gain(s: SaveState, item: ItemId, n: number, events?: GameEvent[], source = 'activity') { if (n > 0) { s.bank[item] = (s.bank[item] ?? 0) + n; events?.push({ type: 'item-gained', item, amount: n, source }); } }
function consume(s: SaveState, item: ItemId, n: number) { if ((s.bank[item] ?? 0) < n) return false; s.bank[item] = (s.bank[item] ?? 0) - n; if (!s.bank[item]) delete s.bank[item]; return true; }
function addXp(s: SaveState, skill: SkillId, amount: number, events?: GameEvent[]) { if (amount <= 0) return; s.skills[skill].xp += amount; events?.push({ type: 'xp-gained', skill, amount }); while (s.skills[skill].level < 100 && s.skills[skill].xp >= xpForLevel(s.skills[skill].level)) { s.skills[skill].xp -= xpForLevel(s.skills[skill].level); s.skills[skill].level++; const level = s.skills[skill].level; events?.push({ type: 'level-up', skill, level }); if(skill==='Attack')evaluateCombatTierUnlocks(s,events); if (skill === 'Mining' && level === 5) events?.push({ type: 'unlock', id: 'mining.deposit.fieldstone_quarry', label: 'Fieldstone Quarry unlocked · Mining 5' }); pushLog(s, `${skill} reached level ${level}.`); } }
function equippedTool(s: SaveState) { return MINING_TOOLS[(s.equipped.miningTool ?? 'item.mining.worn_pickaxe') as keyof typeof MINING_TOOLS]; }
function equippedHammer(s: SaveState) { return FORGE_HAMMERS[(s.equipped.smithingHammer ?? 'item.smithing.worn_smithing_hammer') as keyof typeof FORGE_HAMMERS]; }
export function setCombatTarget(s: SaveState, id: EnemyId) { const enemy = ENEMIES[id]; if (!enemy || enemy.rank==='Dungeon'||enemy.rank==='Boss'||!enemyUnlocked(s, id)) return false; if (s.activity === 'combat') stopActivity(s);clearEncounterStatuses(s);s.combat.targetId = id; s.combat.areaId = enemy.areaId; s.combat.dungeonId = null; s.combat.encounterIndex=0;s.combat.runState = 'idle'; s.combat.enemyHp = enemy.maxHp; s.combat.sequenceIndex = 0; s.combat.activePhaseIndex = 0; s.combat.enemyTimer = enemy.intervalMs*(enemy.sequence[0]?.intervalMultiplier??1); s.combat.respawn = 0; return true; }
export function startDungeon(s:SaveState,id:string){const dungeon=DUNGEONS[id],elite=Object.values(ENEMIES).find(e=>e.tier===dungeon?.tier&&e.rank==='Elite');if(!dungeon||!areaUnlocked(s,id)||!elite||!s.combatProgress.eliteFirstKills[elite.id]||s.activity==='combat')return false;const enemy=ENEMIES[dungeon.encounters[0]!];clearEncounterStatuses(s);s.combat.targetId=enemy.id;s.combat.areaId=id;s.combat.dungeonId=id;s.combat.encounterIndex=0;s.combat.runState='idle';s.combat.enemyHp=enemy.maxHp;s.combat.enemyTimer=enemy.intervalMs*(enemy.sequence[0]?.intervalMultiplier??1);s.combat.sequenceIndex=0;s.combat.activePhaseIndex=0;s.combat.respawn=0;s.page='Combat';return true;}
export function setCombatArea(s: SaveState, areaId: string) { const area = COMBAT_AREAS[areaId]; if (!area || !areaUnlocked(s, areaId) || s.activity === 'combat') return false;if(area.kind==='dungeon')return startDungeon(s,areaId);const target = area.enemies.find((id) => enemyUnlocked(s, id)); if (!target) return false; return setCombatTarget(s,target); }
function reserveCookingInputs(s: SaveState) { const resolved=resolveRecipeInputs(s); if(!resolved)return false; const knife=COOKING_KNIVES.find(k=>k.id===s.cooking.knife)??COOKING_KNIVES[0]!,recipe=COOKING_RECIPES.find(r=>r.id===s.cooking.recipe)!,preserveChance=Math.min(.5,((knife.effects.preservationPp??0)/100)+(s.cooking.specialization==='Provisioner'?.05:0)+(s.cooking.specialization==='Gourmet Chef'&&recipe.complexity>=5?.08:0));s.cooking.reservedInputs=[];for(const input of resolved){let consumed=0;for(let unit=0;unit<input.amount;unit++){const preserved=s.cooking.forcePreservation||rand(s)<preserveChance;if(!preserved){if(!consume(s,input.item,1)){for(const old of s.cooking.reservedInputs)gain(s,old.item,old.amount);s.cooking.reservedInputs=[];return false;}consumed++;}}if(consumed)s.cooking.reservedInputs.push({item:input.item,amount:consumed});}s.cooking.selectedInputs=Object.fromEntries(resolved.map((x,i)=>[`${i}:${x.tag}`,x.item])); return true; }
export function cookingHasFood(item: ItemId) { return COOKING_RECIPES.some((r)=>r.output===item&&r.foodValue>0); }
export function foodStats(item: ItemId) { const recipe=COOKING_RECIPES.find((r)=>r.output===item&&r.foodValue>0); return recipe?{foodValue:recipe.foodValue,heal:recipe.foodValue*10,satiety:20}:null; }
export function eatFood(s: SaveState, slotIndex: number, automatic=false, events: GameEvent[] = []) { const food=s.food,slot=food.slots[slotIndex];if(!slot||!slot.enabled||!slot.item||food.eatCooldownMs>0||food.foodLockMs>0||food.stunMs>0||s.combat.playerHp<=0)return false;const count=s.bank[slot.item]??0;if(count<=slot.reserve||!cookingHasFood(slot.item))return false;const stats=foodStats(slot.item);if(!stats||!consume(s,slot.item,1))return false;s.combat.playerHp=Math.min(maxHitpoints(s.skills.Hitpoints.level),s.combat.playerHp+stats.heal);food.satiety=Math.min(100,food.satiety+stats.satiety);food.eatCooldownMs=1000;if(automatic)food.autoEatIntervalMs=food.minimumIntervalMs;food.activePriority=slotIndex;food.feedback=`+${stats.heal} HP · +${stats.satiety} Satiety`;s.combat.playerTimer=getPlayerAttackInterval(s);events.push({type:'food-consumed',item:slot.item,heal:stats.heal,satiety:stats.satiety,automatic},{type:automatic?'auto-eat':'manual-eat',item:slot.item});if(food.satiety>=100){food.stunMs=5000;food.foodLockMs=25000;events.push({type:'overeat-triggered'});}const next=food.slots.findIndex((x,i)=>i>slotIndex&&x.enabled&&x.item&&(s.bank[x.item]??0)>x.reserve);if((s.bank[slot.item]??0)<=slot.reserve&&next>=0)food.activePriority=next;return true; }
function tryAutoEat(s: SaveState, events: GameEvent[]) { if(!s.food.autoEat||s.combat.playerHp/maxHitpoints(s.skills.Hitpoints.level)*100>s.food.threshold||s.food.eatCooldownMs>0||s.food.autoEatIntervalMs>0||s.food.foodLockMs>0||s.food.stunMs>0)return;for(let offset=0;offset<s.food.slots.length;offset++){const i=(s.food.activePriority+offset)%s.food.slots.length;if(eatFood(s,i,true,events))return;}s.activity=null;events.push({type:"combat-stopped-food-empty"});pushLog(s,"Combat stopped: no usable Food remains."); }
function selectFish(s: SaveState) { if(s.fishing.forceSpecies){const forced=FISH_SPECIES.find((x)=>x.id===s.fishing.forceSpecies);if(forced&&forced.spotId===s.fishing.spot&&s.skills.Fishing.level>=forced.unlockLevel)return forced;} const pool=fishingCatchWeights(s); let roll=rand(s)*pool.reduce((n,x)=>n+x.weight,0); for(const x of pool){roll-=x.weight;if(roll<=0)return x.fish;} return pool[pool.length-1]?.fish; }
function cookingComplete(s: SaveState, events: GameEvent[]) { const recipe=COOKING_RECIPES.find((r)=>r.id===s.cooking.recipe)!; let quantity=recipe.quantity; const knife=COOKING_KNIVES.find(k=>k.id===s.cooking.knife)??COOKING_KNIVES[0]!;const chance=Math.min(.5,(knife.effects.extraServingPp??0)/100+(s.cooking.specialization==="Provisioner"?.12:0)+(s.cooking.specialization==="Hearth Chef"?.05:0)); if(s.cooking.forceExtraServing||rand(s)<chance){quantity++;events.push({type:'extra-serving',item:recipe.output as ItemId});} gain(s,recipe.output as ItemId,quantity,events,'cooking'); const xp=recipe.xp;addXp(s,'Cooking',xp,events);s.cooking.sessionXp+=xp;s.cooking.sessionOutputs[recipe.output as ItemId]=(s.cooking.sessionOutputs[recipe.output as ItemId]??0)+quantity;events.push({type:'cooking-craft-complete',recipeId:recipe.id as RecipeId,item:recipe.output as ItemId,amount:quantity});s.cooking.selectedInputs={};s.cooking.reservedInputs=[];s.cooking.forceExtraServing=false;if(reserveCookingInputs(s)){s.cooking.phase='prep';s.cooking.actionSerial++;s.cooking.timer=cookingPrepTime(s);}else{s.cooking.phase='prep';s.cooking.timer=0;s.activity=null;} }
function fishingLand(s: SaveState, events: GameEvent[]) { const fish=FISH_SPECIES.find((x)=>x.id===s.fishing.selectedFish);if(!fish)return;const rod=fishingRod(s);let double=.0;if(rod.id==='fishing.tool.emberwood_rod')double+=.03;if(rod.id==='fishing.tool.starwood_rod')double+=.05;if(s.fishing.tackle==='fishing.tackle.double_hook')double+=.10;if(s.fishing.specialization==='Provisioner')double+=.12;if(s.fishing.specialization==='Trophy Angler')double-=.05;double=Math.min(.6,double);const doubled=s.fishing.forceDouble||rand(s)<double;const qty=fish.quantity*(doubled?2:1);gain(s,fish.id as ItemId,qty,events,'fishing');const xp=fish.xp*qty;addXp(s,'Fishing',xp,events);s.fishing.sessionXp+=xp;s.fishing.sessionFish[fish.id as ItemId]=(s.fishing.sessionFish[fish.id as ItemId]??0)+qty;events.push({type:'fish-landed',fishId:fish.id,amount:qty});if(doubled)events.push({type:'fishing-double-catch',fishId:fish.id});const spot=FISHING_SPOTS.find((x)=>x.id===s.fishing.spot)!;const findChance=Math.min(.5,spot.findChance*(1+(rod.id==="fishing.tool.stormwillow_rod"?.1:0))*(s.fishing.specialization==="Deepwater Fisher"?1.3:1));if(s.fishing.forceFind||rand(s)<findChance) { gain(s,spot.findId as ItemId,1,events,'aquatic-find');events.push({type:'aquatic-find',item:spot.findId as ItemId});s.fishing.forceFind=false; }if(s.fishing.bait){if(rand(s)<Math.min(.6,(rod.id==='fishing.tool.reed_rod'?.03:0)+(rod.id==='fishing.tool.ironwood_rod'?.05:0)+(rod.id==='fishing.tool.umbralwood_rod'?.08:0)+(s.fishing.tackle==='fishing.tackle.barbless_master_hook'?.1:0)))events.push({type:'bait-preserved',bait:s.fishing.bait});else consume(s,s.fishing.bait as ItemId,1);}s.fishing.selectedFish=null;s.fishing.phase='bite';s.fishing.actionSerial++;s.fishing.timer=fishingBiteTime(s);s.fishing.forceDouble=false; }
function recipeInputs(recipeId: ForgingRecipeId) { return FORGING_RECIPES[recipeId].inputs; }
function canReserveRecipe(s: SaveState, recipeId: ForgingRecipeId) { return recipeInputs(recipeId).every(({ item, amount }) => (s.bank[item] ?? 0) + (item === s.equipped.miningTool || item === s.equipped.smithingHammer ? 1 : 0) >= amount); }
function startForge(s: SaveState) { const recipe = FORGING_RECIPES[s.smithing.recipe], reserved: Partial<Record<ItemId, number>> = {}; let reservedEquipment: ItemId | null = null;
  for (const input of recipe.inputs) { let remaining = input.amount; if (input.item === s.equipped.miningTool || input.item === s.equipped.smithingHammer) { if (remaining > 0) { reservedEquipment = input.item; remaining--; if (input.item === s.equipped.miningTool) s.equipped.miningTool = null; else s.equipped.smithingHammer = null; } } if (remaining && !consume(s, input.item, remaining)) { if (reservedEquipment === 'item.mining.worn_pickaxe') s.equipped.miningTool = reservedEquipment; if (reservedEquipment === 'item.smithing.worn_smithing_hammer') s.equipped.smithingHammer = reservedEquipment; return false; } reserved[input.item] = input.amount; }
  s.smithing.reservedItems = reserved; s.smithing.reservedEquipment = reservedEquipment; s.smithing.reserved = Object.values(reserved).reduce<number>((a, b) => a + (b ?? 0), 0); s.smithing.work = getForgeWorkRequired(s.smithing.recipe); s.smithing.heat = 100; s.smithing.reheat = false; return true;
}
export function startActivity(s: SaveState, activity: Exclude<Activity, null>) {
  if(activity==='combat'&&s.combat.dungeonId&&s.combat.runState==='ended')return;
  if (activity === 'mining' && !canMineDeposit(s,s.mining.deposit)) return;
  if (activity === 'smelting' && s.skills.Smithing.level<selectedSmeltRecipe(s).unlockLevel) { s.smithing.message = `Smithing ${selectedSmeltRecipe(s).unlockLevel} required`; return; }
  if (activity === 'smelting' && !selectedSmeltRecipe(s).inputs.every(input=>(s.bank[input.item]??0)>=input.amount)) { s.smithing.message = 'Not enough smelting inputs'; return; }
  if (activity === 'forging' && !s.smithing.reserved && (!canReserveRecipe(s, s.smithing.recipe) || s.skills.Smithing.level < FORGING_RECIPES[s.smithing.recipe].unlockLevel)) { s.smithing.message = 'Missing recipe inputs or Smithing level'; return; }
  if (activity === 'combat' && (!canStartCombat(s) || !enemyUnlocked(s, s.combat.targetId))) return;
  if (activity === 'fishing' && !canStartFishing(s)) { s.cooking.message = 'Fishing level, rod, or selected Spot requirement not met'; return; }
  if (activity === 'cooking' && !canStartCooking(s)) { s.cooking.message = 'Missing recipe ingredients, level, or method'; return; }
  if (s.activity && s.activity !== activity) { if(s.activity==='combat')stopActivity(s);else s.activity = null; }
  s.activity = activity;
  if (activity === 'mining') { const d = MINING_DEPOSITS[s.mining.deposit], tool = equippedTool(s); s.page = 'Mining'; syncMining(s); s.mining.timer ||= getMiningStrikeTime(d.strikeMs, tool.speed); }
  if (activity === 'smelting') { s.page = 'Smithing'; s.smithing.mode = 'smelting'; s.smithing.message = ''; s.smithing.timer ||= s.smithing.warm ? smeltingUnitTime(s) : smeltingWarmupTime(s); }
  if (activity === 'forging') { s.page = 'Smithing'; s.smithing.mode = 'forging'; s.smithing.message = ''; if (!s.smithing.reserved && !startForge(s)) { s.activity = null; s.smithing.message = 'Recipe inputs are no longer available'; return; } s.smithing.timer ||= smithingActionTime(s, s.smithing.recipe); }
  if (activity === 'fishing') { s.page = 'Fishing'; s.fishing.phase = 'bite'; s.fishing.actionSerial++; s.fishing.timer = fishingBiteTime(s); s.fishing.selectedFish = null; }
  if (activity === 'cooking') { s.page = 'Cooking'; if (!reserveCookingInputs(s)) { s.activity = null; s.cooking.message = 'Recipe inputs are no longer available'; return; } s.cooking.phase = 'prep'; s.cooking.actionSerial++; s.cooking.timer = cookingPrepTime(s); }
  if (activity === 'combat') { s.page = 'Combat'; s.combat.runState = 'active'; s.combat.playerTimer ||= getPlayerAttackInterval(s); const enemy=ENEMIES[s.combat.targetId],sequence=activeSequence(enemy,s.combat.enemyHp);s.combat.enemyTimer ||= enemy.intervalMs*(sequence[s.combat.sequenceIndex%sequence.length]?.intervalMultiplier??1); }
}
export function stopActivity(s: SaveState) { if (s.activity === 'mining') syncMining(s); if(s.activity==='cooking'){for(const input of s.cooking.reservedInputs)gain(s,input.item,input.amount);s.cooking.reservedInputs=[];s.cooking.selectedInputs={};s.cooking.timer=0;} if(s.activity==='combat')clearEncounterStatuses(s);s.activity = null; if (s.combat.runState === 'active') s.combat.runState = s.combat.dungeonId?'ended':'idle'; }
function preservationChance(s: SaveState, _recipeId: RecipeId) { if (s.smithing.forcePreservation) return 1; return Math.min(.5, (equippedHammer(s).effects.preservationPp ?? 0) / 100); }
function addSmithingReward(s: SaveState, _recipeId: RecipeId, xp: number, events: GameEvent[]) { addXp(s, 'Smithing', xp, events); }
function smelt(s: SaveState, events: GameEvent[]) { const recipe = selectedSmeltRecipe(s), id = recipe.id, chance = preservationChance(s, id); for (const input of recipe.inputs) for (let i = 0; i < input.amount; i++) if (rand(s) >= chance && !consume(s, input.item, 1)) { s.activity = null; s.smithing.message = `Not enough ${input.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}`; events.push({ type: 'error', message: s.smithing.message }); return; }
  gain(s, recipe.output.item, recipe.output.amount, events, 'smelting'); s.smithing.produced++; addSmithingReward(s, id, recipe.smithingXp, events); s.objectives.firstIngot = true; s.smithing.timer = recipe.unitTimeMs; if (!recipe.inputs.every(input=>(s.bank[input.item]??0)>=input.amount)) { s.activity = null; s.smithing.message = 'Not enough smelting inputs'; } }
function finishForge(s: SaveState, events: GameEvent[]) { const sm = s.smithing, id = sm.recipe, recipe = FORGING_RECIPES[id], chance = preservationChance(s, id);
  for (const input of recipe.inputs) { if (!input.preservable) continue; for (let i = 0; i < input.amount; i++) if (rand(s) < chance) gain(s, input.item, 1, events, 'smithing-preservation'); }
  gain(s, recipe.output, 1, events, 'forging'); events.push({ type: 'craft-completed', recipeId: id, item: recipe.output }); sm.reserved = 0; sm.reservedItems = {}; sm.reservedEquipment = null; sm.produced++; sm.message = `${recipe.name} forged`;
  if (recipe.output in MINING_TOOLS) { consume(s, recipe.output, 1); s.equipped.miningTool = recipe.output; }
  if (recipe.output in FORGE_HAMMERS) { consume(s, recipe.output, 1); s.equipped.smithingHammer = recipe.output; }
  if (recipe.slot === 'Weapon') s.objectives.sword = true; if (recipe.slot === 'Head') s.objectives.helm = true; s.activity = null; sm.timer = 0; }
function forgeStrike(s: SaveState, events: GameEvent[]) { const sm = s.smithing, hammer = equippedHammer(s); if (sm.heat < MIN_WORKING_HEAT) { sm.reheat = true; sm.timer = BASE_REHEAT_MS*(hammer.effects.reheatMultiplier??1); return; } sm.work = Math.max(0, sm.work - Math.round(hammer.power*(hammer.effects.forgePowerMultiplier??1))); sm.heat -= BASE_HEAT_LOSS*(hammer.effects.heatLossMultiplier??1); addSmithingReward(s, sm.recipe, FORGING_RECIPES[sm.recipe].xpPerStrike, events); if (sm.work <= 0) finishForge(s, events); else sm.timer = smithingActionTime(s, sm.recipe); }


export function advanceWithEvents(input: SaveState, elapsedMs: number): SimulationResult { const s = structuredClone(input), events: GameEvent[] = []; let left = Math.max(0, elapsedMs); while (left > 0 && s.activity) { let step = left; if (s.activity === 'mining') step = Math.min(step, s.mining.timer || getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed)); else if (s.activity === 'smelting' || s.activity === 'forging') step = Math.min(step, s.smithing.timer || (s.activity === 'forging' ? smithingActionTime(s, s.smithing.recipe) : smeltingWarmupTime(s))); else if (s.activity === 'fishing') step = Math.min(step, s.fishing.timer || fishingBiteTime(s)); else if (s.activity === 'cooking') step = Math.min(step, s.cooking.timer || (s.cooking.phase === 'prep' ? cookingPrepTime(s) : cookingMethodTime(s))); else step = Math.min(step, combatNextBoundary(s));
    if (!(step > 0 && Number.isFinite(step))) break; left -= step;
    if (s.activity === 'mining') { s.mining.timer -= step; if (s.mining.timer <= 0) { miningHit(s, events, {rand,gain,addXp}); s.mining.timer = getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed); } }
    else if (s.activity === 'smelting') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (!s.smithing.warm) { s.smithing.warm = true; s.smithing.timer = smeltingUnitTime(s); } else smelt(s, events); } }
    else if (s.activity === 'forging') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (s.smithing.reheat) { s.smithing.heat = 100; s.smithing.reheat = false; s.smithing.timer = smithingActionTime(s, s.smithing.recipe); } else forgeStrike(s, events); } }
    else if (s.activity === 'fishing') { s.fishing.timer -= step; if (s.fishing.timer <= 0) { if (s.fishing.phase === 'bite') { const fish = selectFish(s); if (!fish) { s.activity = null; break; } s.fishing.selectedFish = fish.id; s.fishing.phase = 'landing'; s.fishing.actionSerial++; events.push({ type:'fishing-bite-complete',spotId:s.fishing.spot },{ type:'fish-selected',fishId:fish.id}); s.fishing.timer=fishingLandingTime(s,fish); } else fishingLand(s,events); } }
    else if (s.activity === 'cooking') { s.cooking.timer -= step; if (s.cooking.timer <= 0) { if (s.cooking.phase === 'prep') { events.push({ type:'cooking-prep-complete',recipeId:s.cooking.recipe as RecipeId }); const recipe=COOKING_RECIPES.find((r)=>r.id===s.cooking.recipe)!; if(recipe.method==='Prep Table') cookingComplete(s,events); else { s.cooking.phase='cook'; s.cooking.actionSerial++; s.cooking.timer=cookingMethodTime(s); } } else cookingComplete(s,events); } }
    else { advanceCombat(s, step, events, { rand, gain, addXp }); if (s.activity === 'combat') tryAutoEat(s, events); }
  }
  if(input.activity!=='combat') { const decay=Math.max(0,elapsedMs);s.food.satiety=Math.max(0,s.food.satiety-decay/1000);s.food.eatCooldownMs=Math.max(0,s.food.eatCooldownMs-decay);s.food.autoEatIntervalMs=Math.max(0,s.food.autoEatIntervalMs-decay);s.food.foodLockMs=Math.max(0,s.food.foodLockMs-decay);s.food.stunMs=Math.max(0,s.food.stunMs-decay); } else if(s.activity!=='combat'&&left>0) { s.food.satiety=Math.max(0,s.food.satiety-left/1000);s.food.eatCooldownMs=Math.max(0,s.food.eatCooldownMs-left);s.food.autoEatIntervalMs=Math.max(0,s.food.autoEatIntervalMs-left);s.food.foodLockMs=Math.max(0,s.food.foodLockMs-left);s.food.stunMs=Math.max(0,s.food.stunMs-left); }
  s.savedAt = Date.now(); return { state: s, events };
}
export function advance(input: SaveState, elapsedMs: number) { return advanceWithEvents(input, elapsedMs).state; }
export function devForceCurrentEnemyDefeat(s:SaveState) { forceCurrentEnemyDefeat(s,[],{rand,gain,addXp}); }
export function estimateForgeCompletion(s: SaveState) { const sm = s.smithing; if (!sm.work && !sm.reserved) return 0; const hammer = equippedHammer(s), interval = smithingActionTime(s, sm.recipe); let work = sm.work || getForgeWorkRequired(sm.recipe), heat = sm.heat, remaining = Math.max(0, sm.timer), reheatInProgress = sm.reheat; let guard = 0; while (work > 0 && guard++ < 1000) { if (reheatInProgress) { heat = 100; reheatInProgress = false; } else if (heat < MIN_WORKING_HEAT) { remaining += BASE_REHEAT_MS*(hammer.effects.reheatMultiplier??1); heat = 100; } else { remaining += interval; work = Math.max(0, work - Math.round(hammer.power*(hammer.effects.forgePowerMultiplier??1))); heat -= BASE_HEAT_LOSS*(hammer.effects.heatLossMultiplier??1); } } return remaining; }
