import { ENEMIES, NORMAL_ENEMIES } from '../content/combat/t1Enemies';
import { MELEE_WEAPONS } from '../content/combat/meleeWeapons';
import { HEAVY_ARMOR } from '../content/combat/heavyArmor';
import { OFFHANDS } from '../content/combat/offhands';
import { FORGING_RECIPES } from '../content/smithing/forgingRecipes';
import { SMELTING_RECIPES } from '../content/smithing/smeltingRecipes';
import { FORGE_HAMMERS } from '../content/smithing/smithingTools';
import { MINING_DEPOSITS } from '../content/mining/miningDeposits';
import { MINING_STAGE_MODEL } from '../content/mining/miningStages';
import { MINING_TOOLS } from '../content/mining/miningTools';
import { MINING_MASTERY_EFFECTS } from '../content/mining/miningMastery';
import { SMITHING_MASTERY_EFFECTS } from '../content/smithing/smithingMastery';
import { damageAfterResistance, getCoreMaterialChance, getDepositStageDensity, getMasteryLevel, getMiningMasteryXp, getMiningPower, getMiningStrikeTime, getPrimaryExpectedQuantity, hitChance, maxHitpoints, resolvePrimaryQuantity, xpForLevel } from './gameMath';
import type { Activity, ActiveStatus, DepositId, DamageType, EnemyId, ForgingRecipeId, GameEvent, ItemId, MasteryProgress, RecipeId, SaveState, SimulationResult, SkillId } from '../types/gameTypes';

const MIN_WORKING_HEAT = 25, BASE_REHEAT_MS = 2000, BASE_HEAT_LOSS = 10;
const pushLog = (s: SaveState, line: string) => { s.combat.log = [line, ...s.combat.log].slice(0, 8); };
function rand(s: SaveState) { let x = s.rng | 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; s.rng = x >>> 0; return s.rng / 4294967296; }
function gain(s: SaveState, item: ItemId, n: number, events?: GameEvent[], source = 'activity') { if (n > 0) { s.bank[item] = (s.bank[item] ?? 0) + n; events?.push({ type: 'item-gained', item, amount: n, source }); } }
function consume(s: SaveState, item: ItemId, n: number) { if ((s.bank[item] ?? 0) < n) return false; s.bank[item] = (s.bank[item] ?? 0) - n; if (!s.bank[item]) delete s.bank[item]; return true; }
function mastery(s: SaveState, domain: 'mining' | 'smithing', key: DepositId | RecipeId): MasteryProgress { if (domain === 'mining') { const id = key as DepositId; const runtime = s.mining.deposits[id] ??= { stageIndex: 0, densityRemaining: MINING_DEPOSITS[id].baseDensity, cyclesCompleted: 0, totalPrimary: 0, totalStagesCompleted: 0, mastery: { xp: 0, level: 1 } }; return runtime.mastery; } return s.smithing.mastery[key as RecipeId] ??= { xp: 0, level: 1 }; }
function addMasteryXp(s: SaveState, domain: 'mining' | 'smithing', key: DepositId | RecipeId, amount: number, events: GameEvent[]) { if (amount <= 0) return; const progress = mastery(s, domain, key), oldLevel = progress.level; progress.xp += amount; progress.level = getMasteryLevel(progress.xp); events.push({ type: 'mastery-xp-gained', domain, key, amount }); if (progress.level > oldLevel) events.push({ type: 'mastery-level-up', domain, key, level: progress.level }); for (const level of domain === 'mining' ? [10, 25, 50, 75, 100] : [10, 25, 50, 75, 100]) if (oldLevel < level && progress.level >= level) { const effect = (domain === 'mining' ? MINING_MASTERY_EFFECTS : SMITHING_MASTERY_EFFECTS)[level]!; events.push({ type: 'mastery-milestone', domain, key, milestone: level, effect }); } }
function addXp(s: SaveState, skill: SkillId, amount: number, events?: GameEvent[]) { if (amount <= 0) return; s.skills[skill].xp += amount; events?.push({ type: 'xp-gained', skill, amount }); while (s.skills[skill].level < 100 && s.skills[skill].xp >= xpForLevel(s.skills[skill].level)) { s.skills[skill].xp -= xpForLevel(s.skills[skill].level); s.skills[skill].level++; const level = s.skills[skill].level; events?.push({ type: 'level-up', skill, level }); if (skill === 'Mining' && level === 5) events?.push({ type: 'unlock', id: 'mining.deposit.fieldstone_quarry', label: 'Fieldstone Quarry unlocked · Mining 5' }); pushLog(s, `${skill} reached level ${level}.`); } }
function equippedTool(s: SaveState) { return MINING_TOOLS[(s.equipped.miningTool ?? 'item.mining.worn_pickaxe') as keyof typeof MINING_TOOLS]; }
function equippedHammer(s: SaveState) { return FORGE_HAMMERS[(s.equipped.smithingHammer ?? 'item.smithing.worn_smithing_hammer') as keyof typeof FORGE_HAMMERS]; }
function runtimeDeposit(s: SaveState, id: DepositId) { const def = MINING_DEPOSITS[id]; return s.mining.deposits[id] ??= { stageIndex: 0, densityRemaining: def.baseDensity, cyclesCompleted: 0, totalPrimary: 0, totalStagesCompleted: 0, mastery: { xp: 0, level: 1 } }; }
function syncMining(s: SaveState) { const d = runtimeDeposit(s, s.mining.deposit); s.mining.stage = d.stageIndex; s.mining.density = d.densityRemaining; s.mining.cycles = d.cyclesCompleted; }
export function selectDeposit(s: SaveState, id: DepositId) { const next = MINING_DEPOSITS[id]; if (s.skills.Mining.level < next.unlockLevel) return false; if (s.mining.deposit === id) return true; const current = runtimeDeposit(s, s.mining.deposit); current.densityRemaining = getDepositStageDensity(current.stageIndex, s.mining.deposit); if (s.activity === 'mining') s.activity = null; s.mining.deposit = id; const target = runtimeDeposit(s, id); target.densityRemaining = getDepositStageDensity(target.stageIndex, id); s.mining.timer = 0; syncMining(s); return true; }
export function setCombatTarget(s: SaveState, id: EnemyId) { const enemy = ENEMIES[id]; if (id === 'ironjaw-boar' && !NORMAL_ENEMIES.every((target) => (s.combat.defeated[target] ?? 0) > 0)) return false; if (id === 'ironjaw-boar' && s.skills.Attack.level < enemy.unlock) return false; if (s.activity === 'combat') stopActivity(s); s.combat.targetId = id; s.combat.enemyHp = enemy.hp; s.combat.sequenceIndex = 0; s.combat.enemyTimer = enemy.intervalMs; s.combat.respawn = 0; s.combat.statuses = []; return true; }
function recipeInputs(recipeId: ForgingRecipeId) { return FORGING_RECIPES[recipeId].inputs; }
function canReserveRecipe(s: SaveState, recipeId: ForgingRecipeId) { return recipeInputs(recipeId).every(({ item, amount }) => (s.bank[item] ?? 0) + (item === s.equipped.miningTool || item === s.equipped.smithingHammer ? 1 : 0) >= amount); }
function startForge(s: SaveState) { const recipe = FORGING_RECIPES[s.smithing.recipe], reserved: Partial<Record<ItemId, number>> = {}; let reservedEquipment: ItemId | null = null;
  for (const input of recipe.inputs) { let remaining = input.amount; if (input.item === s.equipped.miningTool || input.item === s.equipped.smithingHammer) { if (remaining > 0) { reservedEquipment = input.item; remaining--; if (input.item === s.equipped.miningTool) s.equipped.miningTool = null; else s.equipped.smithingHammer = null; } } if (remaining && !consume(s, input.item, remaining)) { if (reservedEquipment === 'item.mining.worn_pickaxe') s.equipped.miningTool = reservedEquipment; if (reservedEquipment === 'item.smithing.worn_smithing_hammer') s.equipped.smithingHammer = reservedEquipment; return false; } reserved[input.item] = input.amount; }
  s.smithing.reservedItems = reserved; s.smithing.reservedEquipment = reservedEquipment; s.smithing.reserved = Object.values(reserved).reduce((a, b) => a + (b ?? 0), 0); s.smithing.work = getForgeWorkRequired(s.smithing.recipe); s.smithing.heat = 100; s.smithing.reheat = false; return true;
}
export function startActivity(s: SaveState, activity: Exclude<Activity, null>) {
  if (activity === 'smelting' && (s.bank['item.mining.copper_ore'] ?? 0) < 2) { s.smithing.message = 'Not enough Copper Ore'; return; }
  if (activity === 'forging' && !s.smithing.reserved && (!canReserveRecipe(s, s.smithing.recipe) || s.skills.Smithing.level < FORGING_RECIPES[s.smithing.recipe].unlockLevel)) { s.smithing.message = 'Missing recipe inputs or Smithing level'; return; }
  if (activity === 'combat' && (!['combat.weapon.melee.copper_sword','combat.weapon.melee.copper_battle_axe','combat.weapon.melee.copper_mace'].includes(s.equipped.weapon ?? '') || !(s.equipped.head || s.equipped.armor || s.equipped.hands || s.equipped.feet))) return;
  if (s.activity && s.activity !== activity) s.activity = null;
  s.activity = activity;
  if (activity === 'mining') { const d = MINING_DEPOSITS[s.mining.deposit], tool = equippedTool(s); s.page = 'Mining'; syncMining(s); s.mining.timer ||= getMiningStrikeTime(d.strikeMs, tool.speed); }
  if (activity === 'smelting') { s.page = 'Smithing'; s.smithing.mode = 'smelting'; s.smithing.message = ''; s.smithing.timer ||= s.smithing.warm ? smeltingUnitTime(s) : smeltingWarmupTime(s); }
  if (activity === 'forging') { s.page = 'Smithing'; s.smithing.mode = 'forging'; s.smithing.message = ''; if (!s.smithing.reserved && !startForge(s)) { s.activity = null; s.smithing.message = 'Recipe inputs are no longer available'; return; } s.smithing.timer ||= smithingActionTime(s, s.smithing.recipe); }
  if (activity === 'combat') { s.page = 'Combat'; if (s.combat.playerHp <= 0) s.combat.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.combat.playerTimer ||= 2400; s.combat.enemyTimer ||= ENEMIES[s.combat.targetId].intervalMs; }
}
export function stopActivity(s: SaveState) { if (s.activity === 'mining') syncMining(s); s.activity = null; }
export function getForgeWorkRequired(recipeId: ForgingRecipeId) { const recipe = FORGING_RECIPES[recipeId]; return Math.round(recipe.workBase * recipe.workMultiplier); }
export function smithingActionTime(s: SaveState, recipeId: ForgingRecipeId) { const level = mastery(s, 'smithing', recipeId).level; return equippedHammer(s).strikeMs * (level >= 100 ? .93 : level >= 10 ? .98 : 1); }
export function smeltingWarmupTime(s: SaveState) { const level = mastery(s, 'smithing', 'recipe.smithing.copper_ingot').level; return SMELTING_RECIPES['recipe.smithing.copper_ingot'].warmupMs * (level >= 50 ? .92 : 1); }
export function smeltingUnitTime(s: SaveState) { const level = mastery(s, 'smithing', 'recipe.smithing.copper_ingot').level; return SMELTING_RECIPES['recipe.smithing.copper_ingot'].unitTimeMs * (level >= 10 ? .98 : 1); }
function preservationChance(s: SaveState, recipeId: RecipeId) { if (s.smithing.forcePreservation) return 1; const level = mastery(s, 'smithing', recipeId).level; return Math.min(.5, (level >= 25 ? .03 : 0) + (level >= 100 ? .03 : 0)); }
function miningHit(s: SaveState, events: GameEvent[]) { const m = s.mining, id = m.deposit, deposit = MINING_DEPOSITS[id], runtime = runtimeDeposit(s, id), stageIndex = runtime.stageIndex, stage = MINING_STAGE_MODEL[stageIndex]!, tool = equippedTool(s), masteryLevel = runtime.mastery.level; const power = getMiningPower(tool.power, masteryLevel, stageIndex); runtime.densityRemaining = Math.max(0, runtime.densityRemaining - power); m.strikes++;
  if (runtime.densityRemaining > 0) { syncMining(s); return; }
  const extraChance = tool.extraQuantityChance + (masteryLevel >= 25 ? 5 : 0), primaryQuantity = resolvePrimaryQuantity(getPrimaryExpectedQuantity(stageIndex, id), extraChance, () => rand(s)); gain(s, deposit.primary, primaryQuantity, events, `mining:${id}`); runtime.totalPrimary += primaryQuantity;
  const xp = deposit.stageOneXp * stage.xpMultiplier; addXp(s, 'Mining', xp, events); m.sessionOutputs[deposit.primary] = (m.sessionOutputs[deposit.primary] ?? 0) + primaryQuantity; m.sessionXp += xp;
  const rareMod = masteryLevel >= 75 ? 1.15 : 1;
  if (deposit.structuralItem && deposit.structuralChance && rand(s) < deposit.structuralChance) gain(s, deposit.structuralItem, 1, events, `mining:${id}:rubble`);
  const gemChance = (deposit.gemBaseChance ?? 0) * stage.rareMultiplier * rareMod;
  if (deposit.gemPool?.length && rand(s) < gemChance) { const total = deposit.gemWeights?.reduce((a,b)=>a+b,0) ?? deposit.gemPool.length, roll = rand(s) * total; let index = 0, sum = 0; for (; index < deposit.gemPool.length - 1; index++) { sum += deposit.gemWeights?.[index] ?? 1; if (roll < sum) break; } gain(s, deposit.gemPool[index]!, 1, events, `mining:${id}:gem`); }
  const coreChance = getCoreMaterialChance(deposit.coreBaseChance ?? 0, stageIndex, deposit.coreStageMultipliers ?? [], masteryLevel);
  if (deposit.coreItem && rand(s) < coreChance) gain(s, deposit.coreItem, 1, events, `mining:${id}:core`);
  if (stageIndex === 4 && masteryLevel >= 100 && rand(s) < .1) { const repeated = resolvePrimaryQuantity(getPrimaryExpectedQuantity(stageIndex, id), extraChance, () => rand(s)); gain(s, deposit.primary, repeated, events, `mining:${id}:mastery-core-repeat`); runtime.totalPrimary += repeated; m.sessionOutputs[deposit.primary] = (m.sessionOutputs[deposit.primary] ?? 0) + repeated; }
  const masteryXp = getMiningMasteryXp(deposit.stageOneXp, stageIndex); addMasteryXp(s, 'mining', id, masteryXp, events);
  runtime.totalStagesCompleted++; events.push({ type: 'stage-completed', depositId: id, stage: stageIndex }); if (stageIndex === MINING_STAGE_MODEL.length - 1) { runtime.stageIndex = 0; runtime.cyclesCompleted++; s.objectives.firstCycle = true; } else runtime.stageIndex++;
  runtime.densityRemaining = getDepositStageDensity(runtime.stageIndex, id); syncMining(s);
}
function addSmithingReward(s: SaveState, recipeId: RecipeId, xp: number, events: GameEvent[]) { const level = mastery(s, 'smithing', recipeId).level, xpWithBonus = xp * (level >= 75 ? 1.05 : 1); addXp(s, 'Smithing', xpWithBonus, events); addMasteryXp(s, 'smithing', recipeId, xpWithBonus * .4 * (level >= 75 ? 1.05 : 1), events); }
function smelt(s: SaveState, events: GameEvent[]) { const recipe = SMELTING_RECIPES['recipe.smithing.copper_ingot'], id = recipe.id, chance = preservationChance(s, id); for (const input of recipe.inputs) for (let i = 0; i < input.amount; i++) if (rand(s) >= chance && !consume(s, input.item, 1)) { s.activity = null; s.smithing.message = 'Not enough Copper Ore'; events.push({ type: 'error', message: s.smithing.message }); return; }
  gain(s, recipe.output.item, recipe.output.amount, events, 'smelting'); s.smithing.produced++; addSmithingReward(s, id, recipe.smithingXp, events); s.objectives.firstIngot = true; const masteryLevel = mastery(s, 'smithing', id).level; s.smithing.timer = recipe.unitTimeMs * (masteryLevel >= 10 ? .98 : 1); if ((s.bank['item.mining.copper_ore'] ?? 0) < 2) { s.activity = null; s.smithing.message = 'Not enough Copper Ore'; } }
function finishForge(s: SaveState, events: GameEvent[]) { const sm = s.smithing, id = sm.recipe, recipe = FORGING_RECIPES[id], chance = preservationChance(s, id);
  for (const input of recipe.inputs) { if (!input.preservable) continue; for (let i = 0; i < input.amount; i++) if (rand(s) < chance) gain(s, input.item, 1, events, 'smithing-preservation'); }
  gain(s, recipe.output, 1, events, 'forging'); events.push({ type: 'craft-completed', recipeId: id, item: recipe.output }); sm.reserved = 0; sm.reservedItems = {}; sm.reservedEquipment = null; sm.produced++; sm.message = `${recipe.name} forged`;
  if (recipe.output === 'item.mining.copper_pickaxe') { consume(s, recipe.output, 1); s.equipped.miningTool = recipe.output; }
  if (recipe.output === 'item.smithing.copper_smithing_hammer') { consume(s, recipe.output, 1); s.equipped.smithingHammer = recipe.output; }
  if (id === 'recipe.smithing.copper_sword') s.objectives.sword = true; if (id === 'recipe.smithing.copper_helm') s.objectives.helm = true; if (s.objectives.sword && s.objectives.helm && !s.objectives.victory) events.push({ type: 'unlock', id: 'broken-road', label: 'Broken Road unlocked' }); s.activity = null; sm.timer = 0; }
function forgeStrike(s: SaveState, events: GameEvent[]) { const sm = s.smithing, hammer = equippedHammer(s); const masteryLevel = mastery(s, 'smithing', sm.recipe).level; if (sm.heat < MIN_WORKING_HEAT) { sm.reheat = true; sm.timer = BASE_REHEAT_MS * (masteryLevel >= 50 ? .92 : 1); return; } sm.work = Math.max(0, sm.work - hammer.power); sm.heat -= BASE_HEAT_LOSS * (masteryLevel >= 50 ? .92 : 1); addSmithingReward(s, sm.recipe, FORGING_RECIPES[sm.recipe].xpPerStrike, events); if (sm.work <= 0) finishForge(s, events); else sm.timer = smithingActionTime(s, sm.recipe); }

const weaponDefinition = (id: ItemId | null) => id && id in MELEE_WEAPONS ? MELEE_WEAPONS[id as keyof typeof MELEE_WEAPONS] : null;
const weaponDamage = (id: ItemId | null) => weaponDefinition(id)?.power ?? 0;
const weaponInterval = (s: SaveState) => (weaponDefinition(s.equipped.weapon)?.intervalMs ?? 2400) + (s.equipped.offhand === 'combat.offhand.melee.copper_shield' ? OFFHANDS['combat.offhand.melee.copper_shield'].attackIntervalPenaltyMs : 0);
const special = (s: SaveState) => { const weapon = weaponDefinition(s.equipped.weapon)?.special; return weapon ? { ...weapon, cost: weapon.stamina, accuracy: weapon.accuracyBonus, resistanceDown: weapon.resistanceDownPp } : null; };
function addStatus(c: SaveState['combat'], status: ActiveStatus) { c.statuses = c.statuses.filter((item) => !(item.type === status.type && item.sourceId === status.sourceId)); c.statuses.push(status); }
function resolvePlayerHit(s: SaveState, type: DamageType, events: GameEvent[], multiplier = 1, accuracyBonus = 0, specialData?: ReturnType<typeof special>) { const c = s.combat, enemy = ENEMIES[c.targetId], weapon = weaponDefinition(s.equipped.weapon); const accuracyDown = c.statuses.some((status) => status.target === 'player' && status.type === 'AccuracyDown') ? .08 : 0; const accuracy = (100 + s.skills.Attack.level * 6 + (weapon?.accuracyBonus ?? 0)) * (1 + accuracyBonus) * (1 - accuracyDown); if (rand(s) <= hitChance(accuracy, enemy.evasion)) { const physical = ['Slash','Stab','Crush','Pierce','Puncture'].includes(type); const resistanceDebuff = physical ? c.statuses.filter((status) => status.target === 'enemy' && status.type === 'ResistanceDown').reduce((sum, status) => sum + (status.magnitude ?? 0), 0) : 0; const penetration = weapon?.penetrationType === type ? weapon.penetrationPp ?? 0 : 0; const resistance = (enemy.resistance[type] ?? 0) - resistanceDebuff - penetration; let raw = weaponDamage(s.equipped.weapon) * multiplier * (1 + s.skills.Attack.level / 100); const crit = rand(s) < (.05 + (weapon?.critRateBonus ?? 0)); if (crit) raw *= 1.5 * (1 + (weapon?.critDamageBonus ?? 0)); if (specialData?.executeBonus && c.enemyHp / enemy.hp < .3) raw *= 1 + specialData.executeBonus; const dmg = damageAfterResistance(Math.max(1, Math.floor(raw * (.9 + rand(s) * .2))), resistance); c.enemyHp = Math.max(0, c.enemyHp - dmg); addXp(s, 'Attack', dmg * .4, events); addXp(s, 'Hitpoints', dmg * .1, events); addXp(s, 'Defence', dmg * .1, events); pushLog(s, `${crit ? 'Critical hit' : 'You hit'} ${enemy.name} for ${dmg} ${type}.`); if (specialData?.resistanceDown) addStatus(c, { id: 'concussive-resistance', type: 'ResistanceDown', sourceId: 'player', target: 'enemy', remainingMs: 8000, magnitude: specialData.resistanceDown }); return dmg; } pushLog(s, 'Your attack misses.'); return 0; }
function playerAttack(s: SaveState, events: GameEvent[]) { const c = s.combat; if (c.statuses.some((status) => status.target === 'player' && status.type === 'Stun')) { pushLog(s, 'You are stunned and lose your action.'); c.playerTimer = 1000; c.playerActionSerial++; return; } const weaponType: DamageType = weaponDefinition(s.equipped.weapon)?.style ?? c.stance; resolvePlayerHit(s, weaponType, events); c.playerActionSerial++;
  const queued = c.specialMode !== 'Off' && (c.queuedSpecial || (c.specialMode === 'Auto' && Boolean(special(s)))); const spec = special(s); if (c.enemyHp > 0 && queued && spec && c.stamina >= spec.cost) { c.stamina -= spec.cost; c.queuedSpecial = false; resolvePlayerHit(s, spec.type, events, spec.multiplier, spec.accuracy, spec); c.playerActionSerial++; } else if (c.queuedSpecial && spec && c.stamina < spec.cost) c.queuedSpecial = false;
  c.playerTimer = weaponInterval(s);
  if (c.enemyHp <= 0) { const enemy = ENEMIES[c.targetId]; c.kills++; c.defeated[enemy.id] = (c.defeated[enemy.id] ?? 0) + 1; c.xp += enemy.xp; c.gold += enemy.gold; c.trophies++; s.gold += enemy.gold; events.push({ type: 'gold-gained', amount: enemy.gold, source: 'combat' }); gain(s, enemy.loot, 1, events, `combat:${enemy.id}`); addXp(s, 'Attack', 18, events); addXp(s, 'Defence', 8, events); addXp(s, 'Hitpoints', 8, events); if (enemy.id === 'road-wolf') { s.objectives.victory = true; if (!s.objectives.firstStepsCompleteSeen) { events.push({ type: 'first-steps-complete' }); s.objectives.firstStepsCompleteSeen = true; } } events.push({ type: 'enemy-killed', enemyId: enemy.id }); if (!c.eliteUnlocked && NORMAL_ENEMIES.every((target) => (c.defeated[target] ?? 0) > 0)) { c.eliteUnlocked = true; events.push({ type: 'unlock', id: 'ironjaw-boar', label: 'Ironjaw Boar revealed · All Broken Road threats defeated' }); } pushLog(s, `${enemy.name} defeated.`); c.respawn = 3000; c.enemyHp = 0; } }
function enemyAttack(s: SaveState, events: GameEvent[]) { const c = s.combat, enemy = ENEMIES[c.targetId], action = enemy.sequence[c.sequenceIndex % enemy.sequence.length]!; c.sequenceIndex = (c.sequenceIndex + 1) % enemy.sequence.length; c.enemyActionSerial++; c.enemyTimer = enemy.intervalMs * (enemy.sequence[c.sequenceIndex % enemy.sequence.length]!.intervalMultiplier ?? 1); const stunned = c.statuses.some((status) => status.target === 'enemy' && status.type === 'Stun'); if (stunned) { c.statuses = c.statuses.filter((status) => !(status.target === 'enemy' && status.type === 'Stun')); pushLog(s, `${enemy.name} is stunned and loses its action.`); return; }
  const chance = hitChance(enemy.accuracy, 100 + s.skills.Defence.level * 5); if (rand(s) <= chance) { const raw = enemy.maxHit * action.multiplier * (.72 + rand(s) * .28); const physical = ['Slash','Stab','Crush','Pierce','Puncture'].includes(action.type); const armor = physical ? (s.equipped.head && s.equipped.head in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.head as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.armor && s.equipped.armor in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.armor as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.hands && s.equipped.hands in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.hands as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.feet && s.equipped.feet in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.feet as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.offhand === 'combat.offhand.melee.copper_shield' ? OFFHANDS['combat.offhand.melee.copper_shield'].physicalResistance : 0) : 0; const dmg = damageAfterResistance(Math.floor(raw), armor); c.playerHp -= dmg; pushLog(s, `${enemy.name} uses ${action.name} for ${dmg} ${action.type}.`); if (action.status) { addStatus(c, { id: `${enemy.id}-${action.status.type}`, type: action.status.type, sourceId: enemy.id, target: 'player', remainingMs: action.status.durationMs, magnitude: action.status.magnitude, tickMs: action.status.type === 'Bleed' ? 1000 : undefined, tickTimerMs: action.status.type === 'Bleed' ? 1000 : undefined, stacks: action.status.type === 'Bleed' ? Math.max(1, Math.floor(action.status.durationMs / 1000)) : undefined, remainingDamage: action.status.type === 'Bleed' ? Math.max(1, Math.floor(dmg * action.status.magnitude)) : undefined }); if (action.status.type === 'Stun') c.playerTimer += action.status.durationMs; } } else pushLog(s, `${enemy.name} misses.`);
  if (c.playerHp <= 0) { c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; events.push({ type: 'combat-defeat', enemyId: enemy.id }); pushLog(s, 'Defeated — you recover at the roadside.'); } }
function respawn(s: SaveState) { const c = s.combat, enemy = ENEMIES[c.targetId]; c.enemyHp = enemy.hp; c.sequenceIndex = 0; c.enemyTimer = enemy.intervalMs; c.respawn = 0; }

export function advanceWithEvents(input: SaveState, elapsedMs: number): SimulationResult { const s = structuredClone(input), events: GameEvent[] = []; let left = Math.max(0, elapsedMs); while (left > 0 && s.activity) { let step = left; if (s.activity === 'mining') step = Math.min(step, s.mining.timer || getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed)); else if (s.activity === 'smelting' || s.activity === 'forging') step = Math.min(step, s.smithing.timer || (s.activity === 'forging' ? smithingActionTime(s, s.smithing.recipe) : 3040)); else { const c = s.combat; step = Math.min(step, c.playerTimer || weaponInterval(s), c.enemyTimer || ENEMIES[c.targetId].intervalMs, c.respawn || Infinity, ...c.statuses.flatMap((status) => [status.remainingMs, status.tickTimerMs ?? Infinity])); }
    if (!(step > 0 && Number.isFinite(step))) break; left -= step;
    if (s.activity === 'mining') { s.mining.timer -= step; if (s.mining.timer <= 0) { miningHit(s, events); s.mining.timer = getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed); } }
    else if (s.activity === 'smelting') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (!s.smithing.warm) { s.smithing.warm = true; s.smithing.timer = smeltingUnitTime(s); } else smelt(s, events); } }
    else if (s.activity === 'forging') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (s.smithing.reheat) { s.smithing.heat = 100; s.smithing.reheat = false; s.smithing.timer = smithingActionTime(s, s.smithing.recipe); } else forgeStrike(s, events); } }
    else { const c = s.combat; c.elapsed += step; c.stamina = Math.min(100, c.stamina + step * .012); c.playerTimer -= step; c.enemyTimer -= step; if (c.respawn > 0) c.respawn -= step; for (const status of c.statuses) { status.remainingMs -= step; if (status.tickTimerMs !== undefined) status.tickTimerMs -= step; } const bleed = c.statuses.find((status) => status.target === 'player' && status.type === 'Bleed' && status.remainingMs > 0 && status.tickTimerMs !== undefined && status.tickTimerMs <= 0); if (bleed) { const count = bleed.stacks ?? 1, amount = Math.max(1, Math.ceil((bleed.remainingDamage ?? 1) / count)); c.playerHp -= amount; bleed.remainingDamage = Math.max(0, (bleed.remainingDamage ?? amount) - amount); bleed.stacks = Math.max(0, count - 1); bleed.tickTimerMs = bleed.tickMs ?? 1000; pushLog(s, `Bleed deals ${amount} damage.`); }
      c.statuses = c.statuses.filter((status) => status.remainingMs > 0); if (c.playerHp <= 0) { const id = c.targetId; c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; events.push({ type: 'combat-defeat', enemyId: id }); pushLog(s, 'Defeated — you recover at the roadside.'); }
      if (s.activity === 'combat' && c.respawn <= 0 && c.enemyHp <= 0) respawn(s); if (s.activity === 'combat' && c.enemyHp > 0 && c.playerTimer <= 0) playerAttack(s, events); if (s.activity === 'combat' && c.enemyHp > 0 && c.enemyTimer <= 0) enemyAttack(s, events); }
  }
  s.savedAt = Date.now(); return { state: s, events };
}
export function advance(input: SaveState, elapsedMs: number) { return advanceWithEvents(input, elapsedMs).state; }
export function estimateForgeCompletion(s: SaveState) { const sm = s.smithing; if (!sm.work && !sm.reserved) return 0; const hammer = equippedHammer(s), masteryLevel = mastery(s, 'smithing', sm.recipe).level, interval = smithingActionTime(s, sm.recipe); let work = sm.work || getForgeWorkRequired(sm.recipe), heat = sm.heat, remaining = Math.max(0, sm.timer), reheatInProgress = sm.reheat; let guard = 0; while (work > 0 && guard++ < 1000) { if (reheatInProgress) { heat = 100; reheatInProgress = false; } else if (heat < MIN_WORKING_HEAT) { remaining += BASE_REHEAT_MS * (masteryLevel >= 50 ? .92 : 1); heat = 100; } else { remaining += interval; work = Math.max(0, work - hammer.power); heat -= BASE_HEAT_LOSS * (masteryLevel >= 50 ? .92 : 1); } } return remaining; }
