import { ENEMIES, NORMAL_ENEMIES } from '../content/combat/t1Enemies';
import { MELEE_WEAPONS } from '../content/combat/meleeWeapons';
import { HEAVY_ARMOR } from '../content/combat/heavyArmor';
import { OFFHANDS } from '../content/combat/offhands';
import { FORGING_RECIPES } from '../content/smithing/forgingRecipes';
import { FORGE_HAMMERS } from '../content/smithing/smithingTools';
import { MINING_DEPOSITS } from '../content/mining/miningDeposits';
import { MINING_TOOLS } from '../content/mining/miningTools';
import { FISHING_SPOTS, FISH_SPECIES } from '../content/fishing/fishingContent';
import { COOKING_KNIVES, COOKING_RECIPES } from '../content/cooking/cookingContent';
import { damageAfterResistance, getMiningStrikeTime, hitChance, maxHitpoints, xpForLevel } from './gameMath';
import { miningHit, syncMining } from './mining/miningResolver';
import { canStartCooking, cookingMethodTime, cookingPrepTime, resolveRecipeInputs } from './cooking/cookingResolver';
import { canStartFishing, fishingBiteTime, fishingCatchWeights, fishingLandingTime, fishingRod } from './fishing/fishingResolver';
import { getForgeWorkRequired, selectedSmeltRecipe, smithingActionTime, smeltingUnitTime, smeltingWarmupTime } from './smithing/smithingResolver';
export { canStartCooking, cookingMethodTime, cookingPrepTime, resolveCookingInput, resolveRecipeInputs } from './cooking/cookingResolver';
export { canStartFishing, fishingBiteTime, fishingCatchWeights, fishingLandingTime } from './fishing/fishingResolver';
export { getForgeWorkRequired, smithingActionTime, smeltingUnitTime, smeltingWarmupTime } from './smithing/smithingResolver';
export { selectDeposit } from './mining/miningResolver';
import type { Activity, ActiveStatus, DamageType, EnemyId, ForgingRecipeId, GameEvent, ItemId, RecipeId, SaveState, SimulationResult, SkillId } from '../types/gameTypes';

const MIN_WORKING_HEAT = 25, BASE_REHEAT_MS = 2000, BASE_HEAT_LOSS = 10;
const pushLog = (s: SaveState, line: string) => { s.combat.log = [line, ...s.combat.log].slice(0, 8); };
function rand(s: SaveState) { let x = s.rng | 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; s.rng = x >>> 0; return s.rng / 4294967296; }
function gain(s: SaveState, item: ItemId, n: number, events?: GameEvent[], source = 'activity') { if (n > 0) { s.bank[item] = (s.bank[item] ?? 0) + n; events?.push({ type: 'item-gained', item, amount: n, source }); } }
function consume(s: SaveState, item: ItemId, n: number) { if ((s.bank[item] ?? 0) < n) return false; s.bank[item] = (s.bank[item] ?? 0) - n; if (!s.bank[item]) delete s.bank[item]; return true; }
function addXp(s: SaveState, skill: SkillId, amount: number, events?: GameEvent[]) { if (amount <= 0) return; s.skills[skill].xp += amount; events?.push({ type: 'xp-gained', skill, amount }); while (s.skills[skill].level < 100 && s.skills[skill].xp >= xpForLevel(s.skills[skill].level)) { s.skills[skill].xp -= xpForLevel(s.skills[skill].level); s.skills[skill].level++; const level = s.skills[skill].level; events?.push({ type: 'level-up', skill, level }); if (skill === 'Mining' && level === 5) events?.push({ type: 'unlock', id: 'mining.deposit.fieldstone_quarry', label: 'Fieldstone Quarry unlocked · Mining 5' }); pushLog(s, `${skill} reached level ${level}.`); } }
function equippedTool(s: SaveState) { return MINING_TOOLS[(s.equipped.miningTool ?? 'item.mining.worn_pickaxe') as keyof typeof MINING_TOOLS]; }
function equippedHammer(s: SaveState) { return FORGE_HAMMERS[(s.equipped.smithingHammer ?? 'item.smithing.worn_smithing_hammer') as keyof typeof FORGE_HAMMERS]; }
export function setCombatTarget(s: SaveState, id: EnemyId) { const enemy = ENEMIES[id]; if (id === 'ironjaw-boar' && !NORMAL_ENEMIES.every((target) => (s.combat.defeated[target] ?? 0) > 0)) return false; if (id === 'ironjaw-boar' && s.skills.Attack.level < enemy.unlock) return false; if (s.activity === 'combat') stopActivity(s); s.combat.targetId = id; s.combat.enemyHp = enemy.hp; s.combat.sequenceIndex = 0; s.combat.enemyTimer = enemy.intervalMs; s.combat.respawn = 0; s.combat.statuses = []; return true; }
function reserveCookingInputs(s: SaveState) { const resolved=resolveRecipeInputs(s); if(!resolved)return false; const knife=COOKING_KNIVES.find(k=>k.id===s.cooking.knife)??COOKING_KNIVES[0]!,recipe=COOKING_RECIPES.find(r=>r.id===s.cooking.recipe)!,preserveChance=Math.min(.5,((knife.effects.preservationPp??0)/100)+(s.cooking.specialization==='Provisioner'?.05:0)+(s.cooking.specialization==='Gourmet Chef'&&recipe.complexity>=5?.08:0));s.cooking.reservedInputs=[];for(const input of resolved){let consumed=0;for(let unit=0;unit<input.amount;unit++){const preserved=s.cooking.forcePreservation||rand(s)<preserveChance;if(!preserved){if(!consume(s,input.item,1)){for(const old of s.cooking.reservedInputs)gain(s,old.item,old.amount);s.cooking.reservedInputs=[];return false;}consumed++;}}if(consumed)s.cooking.reservedInputs.push({item:input.item,amount:consumed});}s.cooking.selectedInputs=Object.fromEntries(resolved.map((x,i)=>[`${i}:${x.tag}`,x.item])); return true; }
export function cookingHasFood(item: ItemId) { return COOKING_RECIPES.some((r)=>r.output===item&&r.foodValue>0); }
export function foodStats(item: ItemId) { const recipe=COOKING_RECIPES.find((r)=>r.output===item&&r.foodValue>0); return recipe?{foodValue:recipe.foodValue,heal:recipe.foodValue*10,satiety:20}:null; }
export function eatFood(s: SaveState, slotIndex: number, automatic=false, events: GameEvent[] = []) { const food=s.food,slot=food.slots[slotIndex];if(!slot||!slot.enabled||!slot.item||food.eatCooldownMs>0||food.foodLockMs>0||food.stunMs>0||s.combat.playerHp<=0)return false;const count=s.bank[slot.item]??0;if(count<=slot.reserve||!cookingHasFood(slot.item))return false;const stats=foodStats(slot.item);if(!stats||!consume(s,slot.item,1))return false;s.combat.playerHp=Math.min(maxHitpoints(s.skills.Hitpoints.level),s.combat.playerHp+stats.heal);food.satiety=Math.min(100,food.satiety+stats.satiety);food.eatCooldownMs=1000;if(automatic)food.autoEatIntervalMs=food.minimumIntervalMs;food.activePriority=slotIndex;food.feedback=`+${stats.heal} HP · +${stats.satiety} Satiety`;s.combat.playerTimer=weaponInterval(s);events.push({type:'food-consumed',item:slot.item,heal:stats.heal,satiety:stats.satiety,automatic},{type:automatic?'auto-eat':'manual-eat',item:slot.item});if(food.satiety>=100){food.stunMs=5000;food.foodLockMs=25000;events.push({type:'overeat-triggered'});}const next=food.slots.findIndex((x,i)=>i>slotIndex&&x.enabled&&x.item&&(s.bank[x.item]??0)>x.reserve);if((s.bank[slot.item]??0)<=slot.reserve&&next>=0)food.activePriority=next;return true; }
function tryAutoEat(s: SaveState, events: GameEvent[]) { if(!s.food.autoEat||s.combat.playerHp/maxHitpoints(s.skills.Hitpoints.level)*100>s.food.threshold||s.food.eatCooldownMs>0||s.food.autoEatIntervalMs>0||s.food.foodLockMs>0||s.food.stunMs>0)return;for(let offset=0;offset<s.food.slots.length;offset++){const i=(s.food.activePriority+offset)%s.food.slots.length;if(eatFood(s,i,true,events))return;}s.activity=null;events.push({type:"combat-stopped-food-empty"});pushLog(s,"Combat stopped: no usable Food remains."); }
function selectFish(s: SaveState) { if(s.fishing.forceSpecies){const forced=FISH_SPECIES.find((x)=>x.id===s.fishing.forceSpecies);if(forced&&forced.spotId===s.fishing.spot&&s.skills.Fishing.level>=forced.unlockLevel)return forced;} const pool=fishingCatchWeights(s); let roll=rand(s)*pool.reduce((n,x)=>n+x.weight,0); for(const x of pool){roll-=x.weight;if(roll<=0)return x.fish;} return pool[pool.length-1]?.fish; }
function cookingComplete(s: SaveState, events: GameEvent[]) { const recipe=COOKING_RECIPES.find((r)=>r.id===s.cooking.recipe)!; let quantity=recipe.quantity; const knife=COOKING_KNIVES.find(k=>k.id===s.cooking.knife)??COOKING_KNIVES[0]!;const chance=Math.min(.5,(knife.effects.extraServingPp??0)/100+(s.cooking.specialization==="Provisioner"?.12:0)+(s.cooking.specialization==="Hearth Chef"?.05:0)); if(s.cooking.forceExtraServing||rand(s)<chance){quantity++;events.push({type:'extra-serving',item:recipe.output as ItemId});} gain(s,recipe.output as ItemId,quantity,events,'cooking'); const xp=recipe.xp;addXp(s,'Cooking',xp,events);s.cooking.sessionXp+=xp;s.cooking.sessionOutputs[recipe.output as ItemId]=(s.cooking.sessionOutputs[recipe.output as ItemId]??0)+quantity;events.push({type:'cooking-craft-complete',recipeId:recipe.id as RecipeId,item:recipe.output as ItemId,amount:quantity});s.cooking.selectedInputs={};s.cooking.reservedInputs=[];s.cooking.forceExtraServing=false;if(reserveCookingInputs(s)){s.cooking.phase='prep';s.cooking.actionSerial++;s.cooking.timer=cookingPrepTime(s);}else{s.cooking.phase='prep';s.cooking.timer=0;s.activity=null;} }
function fishingLand(s: SaveState, events: GameEvent[]) { const fish=FISH_SPECIES.find((x)=>x.id===s.fishing.selectedFish);if(!fish)return;const rod=fishingRod(s);let double=.0;if(rod.id==='fishing.tool.emberwood_rod')double+=.03;if(rod.id==='fishing.tool.starwood_rod')double+=.05;if(s.fishing.tackle==='fishing.tackle.double_hook')double+=.10;if(s.fishing.specialization==='Provisioner')double+=.12;if(s.fishing.specialization==='Trophy Angler')double-=.05;double=Math.min(.6,double);const doubled=s.fishing.forceDouble||rand(s)<double;const qty=fish.quantity*(doubled?2:1);gain(s,fish.id as ItemId,qty,events,'fishing');const xp=fish.xp*qty;addXp(s,'Fishing',xp,events);s.fishing.sessionXp+=xp;s.fishing.sessionFish[fish.id as ItemId]=(s.fishing.sessionFish[fish.id as ItemId]??0)+qty;events.push({type:'fish-landed',fishId:fish.id,amount:qty});if(doubled)events.push({type:'fishing-double-catch',fishId:fish.id});const spot=FISHING_SPOTS.find((x)=>x.id===s.fishing.spot)!;const findChance=Math.min(.5,spot.findChance*(1+(rod.id==="fishing.tool.stormwillow_rod"?.1:0))*(s.fishing.specialization==="Deepwater Fisher"?1.3:1));if(s.fishing.forceFind||rand(s)<findChance) { gain(s,spot.findId as ItemId,1,events,'aquatic-find');events.push({type:'aquatic-find',item:spot.findId as ItemId});s.fishing.forceFind=false; }if(s.fishing.bait){if(rand(s)<Math.min(.6,(rod.id==='fishing.tool.reed_rod'?.03:0)+(rod.id==='fishing.tool.ironwood_rod'?.05:0)+(rod.id==='fishing.tool.umbralwood_rod'?.08:0)+(s.fishing.tackle==='fishing.tackle.barbless_master_hook'?.1:0)))events.push({type:'bait-preserved',bait:s.fishing.bait});else consume(s,s.fishing.bait as ItemId,1);}s.fishing.selectedFish=null;s.fishing.phase='bite';s.fishing.actionSerial++;s.fishing.timer=fishingBiteTime(s);s.fishing.forceDouble=false; }
function recipeInputs(recipeId: ForgingRecipeId) { return FORGING_RECIPES[recipeId].inputs; }
function canReserveRecipe(s: SaveState, recipeId: ForgingRecipeId) { return recipeInputs(recipeId).every(({ item, amount }) => (s.bank[item] ?? 0) + (item === s.equipped.miningTool || item === s.equipped.smithingHammer ? 1 : 0) >= amount); }
function startForge(s: SaveState) { const recipe = FORGING_RECIPES[s.smithing.recipe], reserved: Partial<Record<ItemId, number>> = {}; let reservedEquipment: ItemId | null = null;
  for (const input of recipe.inputs) { let remaining = input.amount; if (input.item === s.equipped.miningTool || input.item === s.equipped.smithingHammer) { if (remaining > 0) { reservedEquipment = input.item; remaining--; if (input.item === s.equipped.miningTool) s.equipped.miningTool = null; else s.equipped.smithingHammer = null; } } if (remaining && !consume(s, input.item, remaining)) { if (reservedEquipment === 'item.mining.worn_pickaxe') s.equipped.miningTool = reservedEquipment; if (reservedEquipment === 'item.smithing.worn_smithing_hammer') s.equipped.smithingHammer = reservedEquipment; return false; } reserved[input.item] = input.amount; }
  s.smithing.reservedItems = reserved; s.smithing.reservedEquipment = reservedEquipment; s.smithing.reserved = Object.values(reserved).reduce<number>((a, b) => a + (b ?? 0), 0); s.smithing.work = getForgeWorkRequired(s.smithing.recipe); s.smithing.heat = 100; s.smithing.reheat = false; return true;
}
export function startActivity(s: SaveState, activity: Exclude<Activity, null>) {
  if (activity === 'smelting' && s.skills.Smithing.level<selectedSmeltRecipe(s).unlockLevel) { s.smithing.message = `Smithing ${selectedSmeltRecipe(s).unlockLevel} required`; return; }
  if (activity === 'smelting' && !selectedSmeltRecipe(s).inputs.every(input=>(s.bank[input.item]??0)>=input.amount)) { s.smithing.message = 'Not enough smelting inputs'; return; }
  if (activity === 'forging' && !s.smithing.reserved && (!canReserveRecipe(s, s.smithing.recipe) || s.skills.Smithing.level < FORGING_RECIPES[s.smithing.recipe].unlockLevel)) { s.smithing.message = 'Missing recipe inputs or Smithing level'; return; }
  if (activity === 'combat' && (!(s.equipped.weapon && s.equipped.weapon in MELEE_WEAPONS) || !(s.equipped.head || s.equipped.armor || s.equipped.hands || s.equipped.feet))) return;
  if (activity === 'fishing' && !canStartFishing(s)) { s.cooking.message = 'Fishing level, rod, or selected Spot requirement not met'; return; }
  if (activity === 'cooking' && !canStartCooking(s)) { s.cooking.message = 'Missing recipe ingredients, level, or method'; return; }
  if (s.activity && s.activity !== activity) s.activity = null;
  s.activity = activity;
  if (activity === 'mining') { const d = MINING_DEPOSITS[s.mining.deposit], tool = equippedTool(s); s.page = 'Mining'; syncMining(s); s.mining.timer ||= getMiningStrikeTime(d.strikeMs, tool.speed); }
  if (activity === 'smelting') { s.page = 'Smithing'; s.smithing.mode = 'smelting'; s.smithing.message = ''; s.smithing.timer ||= s.smithing.warm ? smeltingUnitTime(s) : smeltingWarmupTime(s); }
  if (activity === 'forging') { s.page = 'Smithing'; s.smithing.mode = 'forging'; s.smithing.message = ''; if (!s.smithing.reserved && !startForge(s)) { s.activity = null; s.smithing.message = 'Recipe inputs are no longer available'; return; } s.smithing.timer ||= smithingActionTime(s, s.smithing.recipe); }
  if (activity === 'fishing') { s.page = 'Fishing'; s.fishing.phase = 'bite'; s.fishing.actionSerial++; s.fishing.timer = fishingBiteTime(s); s.fishing.selectedFish = null; }
  if (activity === 'cooking') { s.page = 'Cooking'; if (!reserveCookingInputs(s)) { s.activity = null; s.cooking.message = 'Recipe inputs are no longer available'; return; } s.cooking.phase = 'prep'; s.cooking.actionSerial++; s.cooking.timer = cookingPrepTime(s); }
  if (activity === 'combat') { s.page = 'Combat'; if (s.combat.playerHp <= 0) s.combat.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.combat.playerTimer ||= 2400; s.combat.enemyTimer ||= ENEMIES[s.combat.targetId].intervalMs; }
}
export function stopActivity(s: SaveState) { if (s.activity === 'mining') syncMining(s); if(s.activity==='cooking'){for(const input of s.cooking.reservedInputs)gain(s,input.item,input.amount);s.cooking.reservedInputs=[];s.cooking.selectedInputs={};s.cooking.timer=0;} s.activity = null; }
function preservationChance(s: SaveState, _recipeId: RecipeId) { if (s.smithing.forcePreservation) return 1; return Math.min(.5, (equippedHammer(s).effects.preservationPp ?? 0) / 100); }
function addSmithingReward(s: SaveState, _recipeId: RecipeId, xp: number, events: GameEvent[]) { addXp(s, 'Smithing', xp, events); }
function smelt(s: SaveState, events: GameEvent[]) { const recipe = selectedSmeltRecipe(s), id = recipe.id, chance = preservationChance(s, id); for (const input of recipe.inputs) for (let i = 0; i < input.amount; i++) if (rand(s) >= chance && !consume(s, input.item, 1)) { s.activity = null; s.smithing.message = `Not enough ${input.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}`; events.push({ type: 'error', message: s.smithing.message }); return; }
  gain(s, recipe.output.item, recipe.output.amount, events, 'smelting'); s.smithing.produced++; addSmithingReward(s, id, recipe.smithingXp, events); s.objectives.firstIngot = true; s.smithing.timer = recipe.unitTimeMs; if (!recipe.inputs.every(input=>(s.bank[input.item]??0)>=input.amount)) { s.activity = null; s.smithing.message = 'Not enough smelting inputs'; } }
function finishForge(s: SaveState, events: GameEvent[]) { const sm = s.smithing, id = sm.recipe, recipe = FORGING_RECIPES[id], chance = preservationChance(s, id);
  for (const input of recipe.inputs) { if (!input.preservable) continue; for (let i = 0; i < input.amount; i++) if (rand(s) < chance) gain(s, input.item, 1, events, 'smithing-preservation'); }
  gain(s, recipe.output, 1, events, 'forging'); events.push({ type: 'craft-completed', recipeId: id, item: recipe.output }); sm.reserved = 0; sm.reservedItems = {}; sm.reservedEquipment = null; sm.produced++; sm.message = `${recipe.name} forged`;
  if (recipe.output in MINING_TOOLS) { consume(s, recipe.output, 1); s.equipped.miningTool = recipe.output; }
  if (recipe.output in FORGE_HAMMERS) { consume(s, recipe.output, 1); s.equipped.smithingHammer = recipe.output; }
  if (id === 'recipe.smithing.copper_sword') s.objectives.sword = true; if (id === 'recipe.smithing.copper_helm') s.objectives.helm = true; if (s.objectives.sword && s.objectives.helm && !s.objectives.victory) events.push({ type: 'unlock', id: 'broken-road', label: 'Broken Road unlocked' }); s.activity = null; sm.timer = 0; }
function forgeStrike(s: SaveState, events: GameEvent[]) { const sm = s.smithing, hammer = equippedHammer(s); if (sm.heat < MIN_WORKING_HEAT) { sm.reheat = true; sm.timer = BASE_REHEAT_MS*(hammer.effects.reheatMultiplier??1); return; } sm.work = Math.max(0, sm.work - Math.round(hammer.power*(hammer.effects.forgePowerMultiplier??1))); sm.heat -= BASE_HEAT_LOSS*(hammer.effects.heatLossMultiplier??1); addSmithingReward(s, sm.recipe, FORGING_RECIPES[sm.recipe].xpPerStrike, events); if (sm.work <= 0) finishForge(s, events); else sm.timer = smithingActionTime(s, sm.recipe); }

const weaponDefinition = (id: ItemId | null) => id && id in MELEE_WEAPONS ? MELEE_WEAPONS[id as keyof typeof MELEE_WEAPONS] : null;
const weaponDamage = (id: ItemId | null) => weaponDefinition(id)?.power ?? 0;
const weaponInterval = (s: SaveState) => (weaponDefinition(s.equipped.weapon)?.intervalMs ?? 2400) + (s.equipped.offhand && s.equipped.offhand in OFFHANDS ? OFFHANDS[s.equipped.offhand as keyof typeof OFFHANDS].attackIntervalPenaltyMs : 0);
const special = (s: SaveState) => { const weapon = weaponDefinition(s.equipped.weapon)?.special; return weapon ? { ...weapon, cost: weapon.stamina, accuracy: weapon.accuracyBonus, resistanceDown: weapon.resistanceDownPp } : null; };
function addStatus(c: SaveState['combat'], status: ActiveStatus) { c.statuses = c.statuses.filter((item) => !(item.type === status.type && item.sourceId === status.sourceId)); c.statuses.push(status); }
function resolvePlayerHit(s: SaveState, type: DamageType, events: GameEvent[], multiplier = 1, accuracyBonus = 0, specialData?: ReturnType<typeof special>) { const c = s.combat, enemy = ENEMIES[c.targetId], weapon = weaponDefinition(s.equipped.weapon); const accuracyDown = c.statuses.some((status) => status.target === 'player' && status.type === 'AccuracyDown') ? .08 : 0; const accuracy = (100 + s.skills.Attack.level * 6 + (weapon?.accuracyBonus ?? 0)) * (1 + accuracyBonus) * (1 - accuracyDown); if (rand(s) <= hitChance(accuracy, enemy.evasion)) { const physical = ['Slash','Stab','Crush','Pierce','Puncture'].includes(type); const resistanceDebuff = physical ? c.statuses.filter((status) => status.target === 'enemy' && status.type === 'ResistanceDown').reduce((sum, status) => sum + (status.magnitude ?? 0), 0) : 0; const penetration = weapon?.penetrationType === type ? weapon.penetrationPp ?? 0 : 0; const resistance = (enemy.resistance[type] ?? 0) - resistanceDebuff - penetration; let raw = weaponDamage(s.equipped.weapon) * multiplier * (1 + s.skills.Attack.level / 100); const crit = rand(s) < (.05 + (weapon?.critRateBonus ?? 0)); if (crit) raw *= 1.5 * (1 + (weapon?.critDamageBonus ?? 0)); if (specialData?.executeBonus && c.enemyHp / enemy.hp < .3) raw *= 1 + specialData.executeBonus; const dmg = damageAfterResistance(Math.max(1, Math.floor(raw * (.9 + rand(s) * .2))), resistance); c.enemyHp = Math.max(0, c.enemyHp - dmg); addXp(s, 'Attack', dmg * .4, events); addXp(s, 'Hitpoints', dmg * .1, events); addXp(s, 'Defence', dmg * .1, events); pushLog(s, `${crit ? 'Critical hit' : 'You hit'} ${enemy.name} for ${dmg} ${type}.`); if (specialData?.resistanceDown) addStatus(c, { id: 'concussive-resistance', type: 'ResistanceDown', sourceId: 'player', target: 'enemy', remainingMs: 8000, magnitude: specialData.resistanceDown }); return dmg; } pushLog(s, 'Your attack misses.'); return 0; }
function playerAttack(s: SaveState, events: GameEvent[]) { const c = s.combat; if (s.food.stunMs>0||c.statuses.some((status) => status.target === 'player' && status.type === 'Stun')) { pushLog(s, 'You are stunned and lose your action.'); c.playerTimer = 1000; c.playerActionSerial++; return; } const weaponType: DamageType = weaponDefinition(s.equipped.weapon)?.style ?? c.stance; resolvePlayerHit(s, weaponType, events); c.playerActionSerial++;
  const queued = c.specialMode !== 'Off' && (c.queuedSpecial || (c.specialMode === 'Auto' && Boolean(special(s)))); const spec = special(s); if (c.enemyHp > 0 && queued && spec && c.stamina >= spec.cost) { c.stamina -= spec.cost; c.queuedSpecial = false; resolvePlayerHit(s, spec.type, events, spec.multiplier, spec.accuracy, spec); c.playerActionSerial++; } else if (c.queuedSpecial && spec && c.stamina < spec.cost) c.queuedSpecial = false;
  c.playerTimer = weaponInterval(s);
  if (c.enemyHp <= 0) { const enemy = ENEMIES[c.targetId]; c.kills++; c.defeated[enemy.id] = (c.defeated[enemy.id] ?? 0) + 1; c.xp += enemy.xp; c.gold += enemy.gold; c.trophies++; s.gold += enemy.gold; events.push({ type: 'gold-gained', amount: enemy.gold, source: 'combat' }); gain(s, enemy.loot, 1, events, `combat:${enemy.id}`); addXp(s, 'Attack', 18, events); addXp(s, 'Defence', 8, events); addXp(s, 'Hitpoints', 8, events); if (enemy.id === 'road-wolf') { s.objectives.victory = true; if (!s.objectives.firstStepsCompleteSeen) { events.push({ type: 'first-steps-complete' }); s.objectives.firstStepsCompleteSeen = true; } } events.push({ type: 'enemy-killed', enemyId: enemy.id }); if (!c.eliteUnlocked && NORMAL_ENEMIES.every((target) => (c.defeated[target] ?? 0) > 0)) { c.eliteUnlocked = true; events.push({ type: 'unlock', id: 'ironjaw-boar', label: 'Ironjaw Boar revealed · All Broken Road threats defeated' }); } pushLog(s, `${enemy.name} defeated.`); c.respawn = 3000; c.enemyHp = 0; } }
function enemyAttack(s: SaveState, events: GameEvent[]) { const c = s.combat, enemy = ENEMIES[c.targetId], action = enemy.sequence[c.sequenceIndex % enemy.sequence.length]!; c.sequenceIndex = (c.sequenceIndex + 1) % enemy.sequence.length; c.enemyActionSerial++; c.enemyTimer = enemy.intervalMs * (enemy.sequence[c.sequenceIndex % enemy.sequence.length]!.intervalMultiplier ?? 1); const stunned = c.statuses.some((status) => status.target === 'enemy' && status.type === 'Stun'); if (stunned) { c.statuses = c.statuses.filter((status) => !(status.target === 'enemy' && status.type === 'Stun')); pushLog(s, `${enemy.name} is stunned and loses its action.`); return; }
  const chance = hitChance(enemy.accuracy, 100 + s.skills.Defence.level * 5); if (rand(s) <= chance) { const raw = enemy.maxHit * action.multiplier * (.72 + rand(s) * .28); const physical = ['Slash','Stab','Crush','Pierce','Puncture'].includes(action.type); const armor = physical ? (s.equipped.head && s.equipped.head in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.head as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.armor && s.equipped.armor in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.armor as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.hands && s.equipped.hands in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.hands as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.feet && s.equipped.feet in HEAVY_ARMOR ? HEAVY_ARMOR[s.equipped.feet as keyof typeof HEAVY_ARMOR].physicalResistance : 0) + (s.equipped.offhand && s.equipped.offhand in OFFHANDS ? OFFHANDS[s.equipped.offhand as keyof typeof OFFHANDS].physicalResistance : 0) : 0; const dmg = damageAfterResistance(Math.floor(raw), armor); c.playerHp -= dmg; pushLog(s, `${enemy.name} uses ${action.name} for ${dmg} ${action.type}.`); if (action.status) { addStatus(c, { id: `${enemy.id}-${action.status.type}`, type: action.status.type, sourceId: enemy.id, target: 'player', remainingMs: action.status.durationMs, magnitude: action.status.magnitude, tickMs: action.status.type === 'Bleed' ? 1000 : undefined, tickTimerMs: action.status.type === 'Bleed' ? 1000 : undefined, stacks: action.status.type === 'Bleed' ? Math.max(1, Math.floor(action.status.durationMs / 1000)) : undefined, remainingDamage: action.status.type === 'Bleed' ? Math.max(1, Math.floor(dmg * action.status.magnitude)) : undefined }); if (action.status.type === 'Stun') c.playerTimer += action.status.durationMs; } } else pushLog(s, `${enemy.name} misses.`);
  if (c.playerHp <= 0) { c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; events.push({ type: 'combat-defeat', enemyId: enemy.id }); pushLog(s, 'Defeated — you recover at the roadside.'); } }
function respawn(s: SaveState) { const c = s.combat, enemy = ENEMIES[c.targetId]; c.enemyHp = enemy.hp; c.sequenceIndex = 0; c.enemyTimer = enemy.intervalMs; c.respawn = 0; }

export function advanceWithEvents(input: SaveState, elapsedMs: number): SimulationResult { const s = structuredClone(input), events: GameEvent[] = []; let left = Math.max(0, elapsedMs); while (left > 0 && s.activity) { let step = left; if (s.activity === 'mining') step = Math.min(step, s.mining.timer || getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed)); else if (s.activity === 'smelting' || s.activity === 'forging') step = Math.min(step, s.smithing.timer || (s.activity === 'forging' ? smithingActionTime(s, s.smithing.recipe) : 3040)); else if (s.activity === 'fishing') step = Math.min(step, s.fishing.timer || fishingBiteTime(s)); else if (s.activity === 'cooking') step = Math.min(step, s.cooking.timer || (s.cooking.phase === 'prep' ? cookingPrepTime(s) : cookingMethodTime(s))); else { const c = s.combat; step = Math.min(step, c.playerTimer || weaponInterval(s), c.enemyTimer || ENEMIES[c.targetId].intervalMs, c.respawn || Infinity, ...c.statuses.flatMap((status) => [status.remainingMs, status.tickTimerMs ?? Infinity])); }
    if (!(step > 0 && Number.isFinite(step))) break; left -= step;
    if (s.activity === 'mining') { s.mining.timer -= step; if (s.mining.timer <= 0) { miningHit(s, events, {rand,gain,addXp}); s.mining.timer = getMiningStrikeTime(MINING_DEPOSITS[s.mining.deposit].strikeMs, equippedTool(s).speed); } }
    else if (s.activity === 'smelting') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (!s.smithing.warm) { s.smithing.warm = true; s.smithing.timer = smeltingUnitTime(s); } else smelt(s, events); } }
    else if (s.activity === 'forging') { s.smithing.timer -= step; if (s.smithing.timer <= 0) { if (s.smithing.reheat) { s.smithing.heat = 100; s.smithing.reheat = false; s.smithing.timer = smithingActionTime(s, s.smithing.recipe); } else forgeStrike(s, events); } }
    else if (s.activity === 'fishing') { s.fishing.timer -= step; if (s.fishing.timer <= 0) { if (s.fishing.phase === 'bite') { const fish = selectFish(s); if (!fish) { s.activity = null; break; } s.fishing.selectedFish = fish.id; s.fishing.phase = 'landing'; s.fishing.actionSerial++; events.push({ type:'fishing-bite-complete',spotId:s.fishing.spot },{ type:'fish-selected',fishId:fish.id}); s.fishing.timer=fishingLandingTime(s,fish); } else fishingLand(s,events); } }
    else if (s.activity === 'cooking') { s.cooking.timer -= step; if (s.cooking.timer <= 0) { if (s.cooking.phase === 'prep') { events.push({ type:'cooking-prep-complete',recipeId:s.cooking.recipe as RecipeId }); const recipe=COOKING_RECIPES.find((r)=>r.id===s.cooking.recipe)!; if(recipe.method==='Prep Table') cookingComplete(s,events); else { s.cooking.phase='cook'; s.cooking.actionSerial++; s.cooking.timer=cookingMethodTime(s); } } else cookingComplete(s,events); } }
    else { const c = s.combat; c.elapsed += step; c.stamina = Math.min(100, c.stamina + step * .012); c.playerTimer -= step; c.enemyTimer -= step; if (c.respawn > 0) c.respawn -= step; s.food.satiety=Math.max(0,s.food.satiety-step/1000);s.food.eatCooldownMs=Math.max(0,s.food.eatCooldownMs-step);s.food.autoEatIntervalMs=Math.max(0,s.food.autoEatIntervalMs-step);s.food.foodLockMs=Math.max(0,s.food.foodLockMs-step);s.food.stunMs=Math.max(0,s.food.stunMs-step); for (const status of c.statuses) { status.remainingMs -= step; if (status.tickTimerMs !== undefined) status.tickTimerMs -= step; } const bleed = c.statuses.find((status) => status.target === 'player' && status.type === 'Bleed' && status.remainingMs > 0 && status.tickTimerMs !== undefined && status.tickTimerMs <= 0); if (bleed) { const count = bleed.stacks ?? 1, amount = Math.max(1, Math.ceil((bleed.remainingDamage ?? 1) / count)); c.playerHp -= amount; bleed.remainingDamage = Math.max(0, (bleed.remainingDamage ?? amount) - amount); bleed.stacks = Math.max(0, count - 1); bleed.tickTimerMs = bleed.tickMs ?? 1000; pushLog(s, `Bleed deals ${amount} damage.`); }
      c.statuses = c.statuses.filter((status) => status.remainingMs > 0); if (c.playerHp <= 0) { const id = c.targetId; c.playerHp = maxHitpoints(s.skills.Hitpoints.level); s.activity = null; events.push({ type: 'combat-defeat', enemyId: id }); pushLog(s, 'Defeated — you recover at the roadside.'); }
      if (s.activity === 'combat' && c.respawn <= 0 && c.enemyHp <= 0) respawn(s); if (s.activity === 'combat' && c.enemyHp > 0 && c.playerTimer <= 0) playerAttack(s, events); if (s.activity === 'combat' && c.enemyHp > 0 && c.enemyTimer <= 0) enemyAttack(s, events); if(s.activity==='combat')tryAutoEat(s,events); }
  }
  if(input.activity!=='combat') { const decay=Math.max(0,elapsedMs);s.food.satiety=Math.max(0,s.food.satiety-decay/1000);s.food.eatCooldownMs=Math.max(0,s.food.eatCooldownMs-decay);s.food.autoEatIntervalMs=Math.max(0,s.food.autoEatIntervalMs-decay);s.food.foodLockMs=Math.max(0,s.food.foodLockMs-decay);s.food.stunMs=Math.max(0,s.food.stunMs-decay); } else if(s.activity!=='combat'&&left>0) { s.food.satiety=Math.max(0,s.food.satiety-left/1000);s.food.eatCooldownMs=Math.max(0,s.food.eatCooldownMs-left);s.food.autoEatIntervalMs=Math.max(0,s.food.autoEatIntervalMs-left);s.food.foodLockMs=Math.max(0,s.food.foodLockMs-left);s.food.stunMs=Math.max(0,s.food.stunMs-left); }
  s.savedAt = Date.now(); return { state: s, events };
}
export function advance(input: SaveState, elapsedMs: number) { return advanceWithEvents(input, elapsedMs).state; }
export function estimateForgeCompletion(s: SaveState) { const sm = s.smithing; if (!sm.work && !sm.reserved) return 0; const hammer = equippedHammer(s), interval = smithingActionTime(s, sm.recipe); let work = sm.work || getForgeWorkRequired(sm.recipe), heat = sm.heat, remaining = Math.max(0, sm.timer), reheatInProgress = sm.reheat; let guard = 0; while (work > 0 && guard++ < 1000) { if (reheatInProgress) { heat = 100; reheatInProgress = false; } else if (heat < MIN_WORKING_HEAT) { remaining += BASE_REHEAT_MS*(hammer.effects.reheatMultiplier??1); heat = 100; } else { remaining += interval; work = Math.max(0, work - Math.round(hammer.power*(hammer.effects.forgePowerMultiplier??1))); heat -= BASE_HEAT_LOSS*(hammer.effects.heatLossMultiplier??1); } } return remaining; }
