import { Badge, Bar, Button, Icon, Panel } from '../../../ui/primitives';
import { ItemMark } from '../../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime, formatDuration } from '../../../ui/game/formatters';
import { FORGING_RECIPES, SMELTING_RECIPES, FORGE_HAMMERS, getForgeWorkRequired, smithingActionTime, estimateForgeCompletion, type Activity, type ForgingRecipeId, type ItemId, type SaveState } from '../../../game/game';
import { masteryXpToNext, masteryXpIntoLevel } from '../../../game/systems/gameMath';
import { ActionProgress } from '../../../ui/game/ActionProgress';

const CATEGORIES = [{ id: 'weapons', label: 'Weapons' }, { id: 'armor', label: 'Armor' }, { id: 'offhand', label: 'Off-hand' }, { id: 'tools', label: 'Tools' }] as const;
export function SmithingScreen({ game: g, mode, setMode, start, stop, choose, setCategory, equipHammer, speedMultiplier = 1 }: { game: SaveState; mode: 'smelting' | 'forging'; setMode: (m: 'smelting' | 'forging') => void; start: (a: Exclude<Activity, null>) => void; stop: () => void; choose: (r: ForgingRecipeId) => void; setCategory: (category: SaveState['smithing']['category']) => void; equipHammer?: (item: ItemId) => void; speedMultiplier?: number }) {
 const smeltActive = g.activity === 'smelting', forgeActive = g.activity === 'forging', recipe = FORGING_RECIPES[g.smithing.recipe], ingot = SMELTING_RECIPES['recipe.smithing.copper_ingot'];
 const available = g.bank['item.smithing.copper_ingot'] ?? 0, hammer = FORGE_HAMMERS[(g.equipped.smithingHammer ?? 'item.smithing.worn_smithing_hammer') as keyof typeof FORGE_HAMMERS], hammerCount = g.bank['item.smithing.copper_smithing_hammer'] ?? 0;
 const recipeMastery = g.smithing.mastery[g.smithing.recipe] ?? { xp: 0, level: 1 }, masteryNext = masteryXpToNext(recipeMastery), masteryProgress = masteryXpIntoLevel(recipeMastery);
 const missing = (id: ForgingRecipeId) => FORGING_RECIPES[id].inputs.some((input) => (g.bank[input.item] ?? 0) + (input.item === g.equipped.miningTool || input.item === g.equipped.smithingHammer ? 1 : 0) < input.amount);
 return <div className="screen smith-screen" data-profession="smithing"><ScreenHeading eyebrow="PROFESSION · TIER 1" title="Smithing" sub="Smelt copper, build recipe mastery, and forge the tools and armor that carry you farther." accent="smithing"><Badge tone="level-badge">LEVEL {g.skills.Smithing.level}</Badge></ScreenHeading>
  <div className="smith-tabs" role="tablist"><button role="tab" aria-selected={mode === 'smelting'} className={mode === 'smelting' ? 'selected' : ''} onClick={() => setMode('smelting')}><Icon name="ingot" size={17}/> Smelting <small>2 Ore to 1 Ingot</small></button><button role="tab" aria-selected={mode === 'forging'} className={mode === 'forging' ? 'selected' : ''} onClick={() => setMode('forging')}><Icon name="hammer" size={17}/> Forging <small>Recipe driven equipment</small></button><div className="forge-label"><span className="heat-light"/> FIELD FORGE <b>HEAT 40</b></div></div>
  {mode === 'smelting' ? <div className="smith-layout smelting-layout"><Panel className={`furnace-panel ${smeltActive ? 'furnace-lit' : ''}`} title="Field Forge" action={<Badge tone={smeltActive ? 'live' : ''}>{smeltActive ? (g.smithing.warm ? 'SMELTING' : 'WARMING') : 'COLD'}</Badge>}><div className="furnace-art"><div className="furnace-chimney"/><div className="furnace-crown"/><div className="furnace-body"><div className="furnace-window"><i/><i/><i/></div><div className="furnace-grate"/></div><div className="furnace-base"/><div className="heat-haze h1"/><div className="heat-haze h2"/></div><div className="furnace-readings"><div><span>HEAT RATING</span><b>40 <small>/ 40</small></b></div><div><span>RECIPE REQUIREMENT</span><b className="copper-text">{ingot.heatRequirement}</b></div><div><span>PRODUCED THIS RUN</span><b>{fmt(g.smithing.produced)}</b></div></div>{smeltActive && <div className="smith-timer-progress"><span className="tiny-label">{g.smithing.warm ? 'SMELTING COPPER INGOT' : 'HEATING THE FORGE'}</span><ActionProgress active={smeltActive} remainingMs={g.smithing.timer} durationMs={g.smithing.warm ? ingot.unitTimeMs : ingot.warmupMs} phaseKey={g.smithing.warm ? 'unit' : 'warmup'} speedMultiplier={speedMultiplier} label="Smelting progress"/></div>}<div className="warm-state"><span className={`pulse-dot ${smeltActive ? 'pulsing warm' : ''}`}/><div><b>{smeltActive ? g.smithing.warm ? 'Furnace is hot' : 'Warming the forge' : 'The forge is cold'}</b><small>{smeltActive ? g.smithing.warm ? 'Copper is flowing into the crucible.' : 'Copper needs a 3.04s heat-up.' : 'A cold start takes 3.04 seconds.'}</small></div><span className="timer-readout">{smeltActive ? formatActionTime(g.smithing.timer) : '3.04s'}</span></div></Panel>
   <Panel title={ingot.name} className="recipe-panel"><div className="recipe-hero"><ItemMark id={ingot.output.item} large/><div><h3>{ingot.name}</h3><span>Basic smelt · Tier 1</span></div><Badge>SMITHING {ingot.unlockLevel}</Badge></div><div className="recipe-equation"><div><ItemMark id={ingot.inputs[0]!.item}/><div><b>{fmt(g.bank[ingot.inputs[0]!.item] ?? 0)} Copper Ore</b><small>{ingot.inputs[0]!.amount} required per action</small></div></div><span className="recipe-arrow">→</span><div><ItemMark id={ingot.output.item}/><div><b>{ingot.output.amount} Copper Ingot</b><small>+{ingot.smithingXp} Smithing XP · +40% Mastery XP</small></div></div></div><div className="recipe-stats"><Stat label="Unit time" value={formatDuration(ingot.unitTimeMs)}/><Stat label="Warm-up" value={formatDuration(ingot.warmupMs)}/><Stat label="Heat required" value={`${ingot.heatRequirement} / 40`}/><Stat label="Copper Ore" value={`${fmt(g.bank['item.mining.copper_ore'] ?? 0)} available`}/></div>{g.smithing.message && <div className="inline-warning">{g.smithing.message}</div>}<Button tone="copper" className="wide-action" onClick={smeltActive ? stop : () => start('smelting')} disabled={!smeltActive && (g.bank['item.mining.copper_ore'] ?? 0) < 2}>{smeltActive ? 'Stop Smelting' : (g.bank['item.mining.copper_ore'] ?? 0) < 2 ? 'Need 2 Copper Ore' : 'Start Smelting'}<span>{smeltActive ? 'Ⅱ' : '▶'}</span></Button><p className="recipe-footnote">No fuel required · Batch size 1 · Field Forge</p></Panel></div>
   : <div className="smith-layout forging-layout"><Panel className="recipe-list-panel" title="T1 Forging" action={<Badge>{fmt(available)} INGOTS</Badge>}><div className="smith-category-tabs" role="tablist" aria-label="Recipe categories">{CATEGORIES.map((category) => <button key={category.id} role="tab" aria-selected={g.smithing.category === category.id} className={g.smithing.category === category.id ? 'selected' : ''} onClick={() => setCategory(category.id)}>{category.label}</button>)}</div><div className="recipe-list">{(Object.keys(FORGING_RECIPES) as ForgingRecipeId[]).filter((id) => FORGING_RECIPES[id].category === g.smithing.category).map((id) => { const r = FORGING_RECIPES[id], unlocked = g.skills.Smithing.level >= r.unlockLevel, isMissing = missing(id), equippedTool = r.category === 'tools' && [g.equipped.miningTool, g.equipped.smithingHammer].includes(r.output); return <button key={id} className={`recipe-choice ${g.smithing.recipe === id ? 'selected' : ''} ${!unlocked ? 'locked' : ''}`} onClick={() => unlocked && choose(id)} aria-pressed={g.smithing.recipe === id} disabled={!unlocked || Boolean((g.smithing.reserved || forgeActive) && id !== g.smithing.recipe)}><ItemMark id={r.output}/><span className="recipe-choice-text"><b>{r.name}</b><small>{r.slot} · {r.inputs.map((input) => `${input.amount} ${input.item === 'item.smithing.copper_ingot' ? 'Ingots' : input.item === 'item.mining.worn_pickaxe' ? 'Worn Pickaxe' : input.item === 'item.smithing.worn_smithing_hammer' ? 'Worn Hammer' : 'material'}`).join(' + ')} · Smithing {r.unlockLevel}{r.dependencyBridge ? ' · Phase 1 tool bridge' : ''}</small></span><Badge tone={!unlocked ? 'missing' : isMissing ? 'missing' : 'ready'}>{!unlocked ? `LEVEL ${r.unlockLevel}` : equippedTool ? 'EQUIPPED' : isMissing ? 'MISSING INPUT' : 'READY'}</Badge></button>; })}</div><div className="reservation-note"><Icon name="bank" size={16}/><span>Inputs are reserved when forging begins. Stop to pause; resume without losing work.</span></div></Panel>
   <Panel className={`workpiece-panel ${forgeActive ? 'is-active' : ''}`} title="Workpiece" action={<Badge tone={forgeActive ? 'live' : ''}>{g.smithing.reheat ? 'REHEATING' : forgeActive ? 'AT THE ANVIL' : 'READY'}</Badge>}><div className={`workpiece-art ${forgeActive ? 'hammering' : ''}`}><div className="anvil-shape"><div className="anvil-horn"/><div className="anvil-block"/><div className="anvil-foot"/></div><div className="workpiece"><ItemMark id={recipe.output} large/></div><div className="forge-flare flare-a"/><div className="forge-flare flare-b"/></div><div className="workpiece-title"><div><span className="tiny-label">CURRENT PATTERN</span><h3>{recipe.name}</h3><small>{recipe.slot} · Smithing {recipe.unlockLevel}</small></div><div className="strike-counter"><b>{Math.ceil((g.smithing.work || getForgeWorkRequired(g.smithing.recipe)) / hammer.power)}</b><small>strikes</small></div></div><div className="bar-label"><span>Work remaining</span><b>{g.smithing.work || getForgeWorkRequired(g.smithing.recipe)} <small>/ {getForgeWorkRequired(g.smithing.recipe)}</small></b></div><Bar value={g.smithing.work || getForgeWorkRequired(g.smithing.recipe)} max={getForgeWorkRequired(g.smithing.recipe)} accent="steel" className="work-bar"/><div className="bar-label heat-label"><span>Workpiece heat</span><b>{g.smithing.heat}<small> / 100</small></b></div><Bar value={g.smithing.heat} max={100} accent={g.smithing.heat < 30 ? 'danger' : 'heat'} className="heat-bar"/>{forgeActive && <div className="smith-timer-progress"><span className="tiny-label">{g.smithing.reheat ? 'REHEATING' : 'NEXT HAMMER STRIKE'}</span><ActionProgress active={forgeActive} remainingMs={g.smithing.timer} durationMs={g.smithing.reheat ? 2000 : smithingActionTime(g, g.smithing.recipe)} phaseKey={g.smithing.reheat ? 'reheat' : g.smithing.work} speedMultiplier={speedMultiplier} label="Forging progress"/></div>}
    <div className="forge-action-row"><div className="forge-status"><span className={`pulse-dot ${forgeActive ? 'pulsing warm' : ''}`}/><div><b>{g.smithing.reheat ? 'Reheating workpiece' : forgeActive ? 'Hammer strike' : hammer.name}</b><small>{g.smithing.reheat ? 'Returning heat to 100.' : forgeActive ? `${formatActionTime(g.smithing.timer)} until impact · ETA ${formatDuration(estimateForgeCompletion(g))}` : `${hammer.name} · Forge Power ${hammer.power} · ${(hammer.strikeMs / 1000).toFixed(2)}s`}</small></div></div><Button tone="copper" onClick={forgeActive ? stop : () => start('forging')} disabled={!forgeActive && (missing(g.smithing.recipe) || g.skills.Smithing.level < recipe.unlockLevel)}>{forgeActive ? 'Stop' : missing(g.smithing.recipe) ? 'Missing Inputs' : 'Begin Forging'}</Button></div>
    <div className="smith-tool-card"><div><span className="tiny-label">SMITHING LOADOUT</span><b>{hammer.name}</b><small>Forge Power {hammer.power} · Strike {formatActionTime(hammer.strikeMs)}</small></div>{equipHammer && hammerCount > 0 && g.equipped.smithingHammer !== 'item.smithing.copper_smithing_hammer' && <Button tone="quiet" onClick={() => equipHammer('item.smithing.copper_smithing_hammer')}>Equip Copper Hammer</Button>}</div>
    <div className="recipe-mastery"><div><span>{recipe.name} Mastery</span><b>Level {recipeMastery.level}</b></div><Bar value={masteryProgress} max={masteryNext || 1} accent="steel"/><small>{recipeMastery.level >= 100 ? 'Mastery complete' : `${fmt(masteryProgress)} / ${fmt(masteryNext)} Mastery XP · Next ${recipeMastery.level < 10 ? 'M10 · Action time -2%' : recipeMastery.level < 25 ? 'M25 · Preservation +3 pp' : recipeMastery.level < 50 ? 'M50 · Heat loss / warm-up -8%' : recipeMastery.level < 75 ? 'M75 · XP +5%' : 'M100 · Action time -5%'}`}{recipeMastery.level >= 25 ? ' · Preservation ' + Math.min(50, (recipeMastery.level >= 25 ? 3 : 0) + (recipeMastery.level >= 100 ? 3 : 0)) + '%' : ''}</small></div>
    {recipe.dependencyBridge && <p className="recipe-footnote">Temporary Phase 1 dependency bridge: the real tool handle arrives with Woodcutting/Fletching.</p>}{g.smithing.message && <div className="success-inline">{g.smithing.message}</div>}</Panel></div>}
  <div className="smith-xp-strip"><div><span>Smithing</span><Badge>LV. {g.skills.Smithing.level}</Badge></div><Bar value={g.skills.Smithing.xp} max={Math.round(15 + (g.skills.Smithing.level - 1) * 2)} accent="xp"/><small>{fmt(g.skills.Smithing.xp)} XP · {hammer.name} · Forge Power {hammer.power} · Strike {formatActionTime(hammer.strikeMs)}</small></div>
 </div>;
}
