import { useMemo, useState } from 'react';
import { Badge, Bar, Button, Panel } from '../../../ui/primitives';
import { ItemMark } from '../../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime, formatDuration } from '../../../ui/game/formatters';
import { FORGING_RECIPES, SMELTING_RECIPES, FORGE_HAMMERS, getForgeWorkRequired, smithingActionTime, estimateForgeCompletion, type Activity, type ForgingRecipeId, type ItemId, type SaveState } from '../../../game/game';
import { ActionProgress } from '../../../ui/game/ActionProgress';
const CATEGORIES=[{id:'weapons',label:'Weapons'},{id:'armor',label:'Armor'},{id:'offhand',label:'Off-hand'},{id:'tools',label:'Tools'}] as const;
export function SmithingScreen({game:g,mode,setMode,start,stop,choose,chooseSmelt,setCategory,equipHammer,speedMultiplier=1}:{game:SaveState;mode:'smelting'|'forging';setMode:(m:'smelting'|'forging')=>void;start:(a:Exclude<Activity,null>)=>void;stop:()=>void;choose:(r:ForgingRecipeId)=>void;chooseSmelt:(id:string)=>void;setCategory:(c:SaveState['smithing']['category'])=>void;equipHammer?:(item:ItemId)=>void;speedMultiplier?:number}){
 const [query,setQuery]=useState(''),[showAll,setShowAll]=useState(false);const smeltActive=g.activity==='smelting',forgeActive=g.activity==='forging',recipe=FORGING_RECIPES[g.smithing.recipe],smeltRecipe=SMELTING_RECIPES[g.smithing.smeltRecipe]??SMELTING_RECIPES['recipe.smithing.copper_ingot']!,hammer=FORGE_HAMMERS[(g.equipped.smithingHammer??'item.smithing.worn_smithing_hammer') as keyof typeof FORGE_HAMMERS];
 const smeltRecipes=useMemo(()=>Object.values(SMELTING_RECIPES).filter(r=>(showAll||r.unlockLevel<=g.skills.Smithing.level+10)&&r.name.toLowerCase().includes(query.toLowerCase())),[showAll,query,g.skills.Smithing.level]);
 const forgeRecipes=useMemo(()=>Object.values(FORGING_RECIPES).filter(r=>r.category===g.smithing.category&&(showAll||r.unlockLevel<=g.skills.Smithing.level+10)&&r.name.toLowerCase().includes(query.toLowerCase())),[showAll,query,g.smithing.category,g.skills.Smithing.level]);
 const missing=(id:ForgingRecipeId)=>FORGING_RECIPES[id].inputs.some(input=>(g.bank[input.item]??0)+(input.item===g.equipped.miningTool||input.item===g.equipped.smithingHammer?1:0)<input.amount);
 return <div className="screen smith-screen" data-profession="smithing"><ScreenHeading eyebrow="PROFESSION · FOUNDRY" title="Smithing" sub="Refine ore into alloys, then shape tools and melee equipment at the forge." accent="smithing"><Badge tone="level-badge">LEVEL {g.skills.Smithing.level}</Badge></ScreenHeading>
  <div className="smith-tabs" role="tablist"><button role="tab" aria-selected={mode==='smelting'} className={mode==='smelting'?'selected':''} onClick={()=>setMode('smelting')}>Smelting <small>Ingots and alloys</small></button><button role="tab" aria-selected={mode==='forging'} className={mode==='forging'?'selected':''} onClick={()=>setMode('forging')}>Forging <small>Melee gear and tools</small></button><div className="forge-label"><span className="heat-light"/> FIELD FORGE <b>HEAT 40</b></div></div>
  <div className={`smith-layout ${mode==='smelting'?'smelting-layout':'forging-layout'}`}><Panel className="recipe-list-panel" title={mode==='smelting'?'Smelting Recipes':'Forging Patterns'} action={<Badge>{mode==='smelting'?Object.keys(SMELTING_RECIPES).length:Object.keys(FORGING_RECIPES).length} RECIPES</Badge>}><div className="recipe-filters"><input aria-label="Search smithing recipes" placeholder="Search recipes" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> All tiers</label></div>{mode==='forging'&&<div className="smith-category-tabs" role="tablist">{CATEGORIES.map(c=><button key={c.id} role="tab" aria-selected={g.smithing.category===c.id} className={g.smithing.category===c.id?'selected':''} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div>}<div className="recipe-list">{mode==='smelting'?smeltRecipes.map(r=>{const unlocked=g.skills.Smithing.level>=r.unlockLevel;return <button key={r.id} className={`recipe-choice ${smeltRecipe.id===r.id?'selected':''} ${!unlocked?'locked':''}`} disabled={!unlocked||smeltActive} onClick={()=>chooseSmelt(r.id)}><ItemMark id={r.output.item}/><span className="recipe-choice-text"><b>{r.name}</b><small>Lv. {r.unlockLevel} · {r.inputs.map(i=>`${i.amount} ${i.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}`).join(' + ')} → {r.output.amount} {r.output.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}</small></span><Badge tone={unlocked?'ready':'missing'}>{unlocked?'SELECT':`LV ${r.unlockLevel}`}</Badge></button>}):forgeRecipes.map(r=>{const unlocked=g.skills.Smithing.level>=r.unlockLevel,ready=!missing(r.id);return <button key={r.id} className={`recipe-choice ${g.smithing.recipe===r.id?'selected':''} ${!unlocked?'locked':''}`} disabled={!unlocked||Boolean(g.smithing.reserved||forgeActive)&&g.smithing.recipe!==r.id} onClick={()=>choose(r.id)}><ItemMark id={r.output}/><span className="recipe-choice-text"><b>{r.name}</b><small>{r.slot} · Lv. {r.unlockLevel} · {r.inputs.map(i=>`${i.amount} ${i.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}`).join(' + ')}</small></span><Badge tone={!unlocked||!ready?'missing':'ready'}>{!unlocked?`LV ${r.unlockLevel}`:ready?'READY':'MISSING'}</Badge></button>})}{(mode==='smelting'?smeltRecipes:forgeRecipes).length===0&&<p className="empty-copy">No recipe matches this filter.</p>}</div></Panel>
   {mode==='smelting'?<Panel className={`furnace-panel ${smeltActive?'furnace-lit':''}`} title="Field Forge" action={<Badge tone={smeltActive?'live':''}>{smeltActive?(g.smithing.warm?'SMELTING':'WARMING'):'COLD'}</Badge>}><div className="furnace-readings"><div><span>HEAT RATING</span><b>40 <small>/ 40</small></b></div><div><span>RECIPE REQUIREMENT</span><b className="copper-text">{smeltRecipe.heatRequirement}</b></div><div><span>PRODUCED THIS RUN</span><b>{fmt(g.smithing.produced)}</b></div></div><div className="recipe-equation"><div><ItemMark id={smeltRecipe.inputs[0]!.item}/><div><b>{fmt(g.bank[smeltRecipe.inputs[0]!.item]??0)} {smeltRecipe.inputs[0]!.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}</b><small>{smeltRecipe.inputs[0]!.amount} required</small></div></div><span className="recipe-arrow">→</span><div><ItemMark id={smeltRecipe.output.item}/><div><b>{smeltRecipe.output.amount} {smeltRecipe.output.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}</b><small>+{smeltRecipe.smithingXp} Smithing XP</small></div></div></div><div className="recipe-stats"><Stat label="Unit time" value={formatDuration(smeltRecipe.unitTimeMs)}/><Stat label="Warm-up" value={formatDuration(smeltRecipe.warmupMs)}/><Stat label="Heat required" value={`${smeltRecipe.heatRequirement} / 40`}/></div>{smeltActive&&<div className="smith-timer-progress"><ActionProgress active={smeltActive} remainingMs={g.smithing.timer} durationMs={g.smithing.warm?smeltRecipe.unitTimeMs:smeltRecipe.warmupMs} phaseKey={g.smithing.warm?'smelt-unit':'smelt-warmup'} speedMultiplier={speedMultiplier} label="Smelting progress"/></div>}{g.smithing.message&&<div className="inline-warning">{g.smithing.message}</div>}<Button tone="copper" className="wide-action" onClick={smeltActive?stop:()=>start('smelting')}>{smeltActive?'Stop Smelting':'Start Smelting'}</Button></Panel>
    :<Panel className={`workpiece-panel ${forgeActive?'is-active':''}`} title="Workpiece" action={<Badge tone={forgeActive?'live':''}>{g.smithing.reheat?'REHEATING':forgeActive?'AT THE ANVIL':'READY'}</Badge>}><div className="workpiece-title"><div><span className="tiny-label">CURRENT PATTERN</span><h3>{recipe.name}</h3><small>{recipe.slot} · Smithing {recipe.unlockLevel}</small></div><ItemMark id={recipe.output} large/></div><div className="bar-label"><span>Work remaining</span><b>{g.smithing.work||getForgeWorkRequired(g.smithing.recipe)} <small>/ {getForgeWorkRequired(g.smithing.recipe)}</small></b></div><Bar value={g.smithing.work||getForgeWorkRequired(g.smithing.recipe)} max={getForgeWorkRequired(g.smithing.recipe)} accent="steel"/><div className="bar-label heat-label"><span>Workpiece heat</span><b>{g.smithing.heat}<small> / 100</small></b></div><Bar value={g.smithing.heat} max={100} accent={g.smithing.heat<30?'danger':'heat'}/>{forgeActive&&<div className="smith-timer-progress"><ActionProgress active={forgeActive} remainingMs={g.smithing.timer} durationMs={g.smithing.reheat?2000:smithingActionTime(g,g.smithing.recipe)} phaseKey={g.smithing.reheat?'reheat':g.smithing.work} speedMultiplier={speedMultiplier} label="Forging progress"/></div>}<div className="forge-action-row"><div className="forge-status"><b>{hammer.name} · Power {hammer.power}</b><small>{formatActionTime(hammer.strikeMs)} strike · ETA {formatDuration(estimateForgeCompletion(g))}</small></div><Button tone="copper" disabled={!forgeActive&&(missing(g.smithing.recipe)||g.skills.Smithing.level<recipe.unlockLevel)} onClick={forgeActive?stop:()=>start('forging')}>{forgeActive?'Stop':missing(g.smithing.recipe)?'Missing Inputs':'Begin Forging'}</Button></div><div className="recipe-stats"><Stat label="Pattern inputs" value={recipe.inputs.map(i=>`${i.amount} ${i.item.split('.').slice(-1)[0]?.replace(/_/g,' ')}`).join(' + ')}/><Stat label="Output" value={recipe.name}/><Stat label="Smithing XP / strike" value={`${recipe.xpPerStrike}`}/></div>{equipHammer&&Object.values(FORGE_HAMMERS).filter(h=>h.item!==hammer.item&&(g.bank[h.item]??0)>0).map(h=><Button key={h.item} tone="quiet" onClick={()=>equipHammer(h.item)}>{h.name} · Power {h.power}</Button>)}{g.smithing.message&&<div className="success-inline">{g.smithing.message}</div>}</Panel>}
  </div><div className="smith-xp-strip"><div><span>Smithing</span><Badge>LV. {g.skills.Smithing.level}</Badge></div><Bar value={g.skills.Smithing.xp} max={Math.round(15+(g.skills.Smithing.level-1)*2)} accent="xp"/><small>{fmt(g.skills.Smithing.xp)} XP · {hammer.name} · Power {hammer.power} · Strike {formatActionTime(hammer.strikeMs)}</small></div>
 </div>;
}
