import type { DamageType, EnemyId, ItemId } from '../../types/gameTypes';
export const RESISTANCES: Record<DamageType, number> = { Slash: 12, Stab: 18, Crush: 14, Pierce: 24, Puncture: 20, Air: 0, Fire: -5, Water: 8, Earth: -8 };
export type EnemyAction = { name: string; type: DamageType; multiplier: number; intervalMultiplier?: number; status?: { type: 'Bleed' | 'AccuracyDown' | 'Stun'; magnitude: number; durationMs: number } };
export type EnemyDefinition = { id: EnemyId; name: string; rank: 'Light' | 'Normal' | 'Elite'; kind: string; style: 'Melee' | 'Ranged' | 'Magic'; hp: number; accuracy: number; maxHit: number; intervalMs: number; evasion: number; resistance: Partial<Record<DamageType, number>>; sequence: readonly EnemyAction[]; xp: number; gold: number; unlock: number; loot: ItemId };
export const ENEMIES: Record<EnemyId, EnemyDefinition> = {
  'road-wolf': { id: 'road-wolf', name: 'Road Wolf', rank: 'Normal', kind: 'Beast', style: 'Melee', hp: 70, accuracy: 160, maxHit: 10, intervalMs: 3000, evasion: 120, resistance: RESISTANCES, sequence: [{ name: 'Bite', type: 'Stab', multiplier: 1 }, { name: 'Bite', type: 'Stab', multiplier: 1 }, { name: 'Rending Fang', type: 'Stab', multiplier: 1.25, status: { type: 'Bleed', magnitude: .1, durationMs: 6000 } }], xp: 24, gold: 8, unlock: 1, loot: 'combat.loot.beast_trophy' },
  'dust-rat': { id: 'dust-rat', name: 'Dust Rat', rank: 'Light', kind: 'Beast', style: 'Melee', hp: 46, accuracy: 108, maxHit: 7, intervalMs: 2500, evasion: 135, resistance: { ...RESISTANCES, Slash: 2, Stab: 10, Crush: -5 }, sequence: [{ name: 'Bite', type: 'Stab', multiplier: 1 }, { name: 'Quick Bite', type: 'Stab', multiplier: .7, intervalMultiplier: .75 }, { name: 'Bite', type: 'Stab', multiplier: 1 }], xp: 18, gold: 5, unlock: 1, loot: 'combat.loot.beast_trophy' },
  'ragged-poacher': { id: 'ragged-poacher', name: 'Ragged Poacher', rank: 'Normal', kind: 'Outlaw', style: 'Ranged', hp: 82, accuracy: 124, maxHit: 9, intervalMs: 3300, evasion: 106, resistance: { ...RESISTANCES, Pierce: 10, Puncture: 8 }, sequence: [{ name: 'Arrow', type: 'Pierce', multiplier: 1 }, { name: 'Arrow', type: 'Pierce', multiplier: 1 }, { name: 'Barbed Shot', type: 'Pierce', multiplier: 1.15, status: { type: 'Bleed', magnitude: .08, durationMs: 6000 } }], xp: 30, gold: 10, unlock: 1, loot: 'combat.loot.beast_trophy' },
  'hedge-spark': { id: 'hedge-spark', name: 'Hedge Spark', rank: 'Normal', kind: 'Fey', style: 'Magic', hp: 76, accuracy: 132, maxHit: 8, intervalMs: 3100, evasion: 112, resistance: { ...RESISTANCES, Air: 15, Fire: -12, Water: 10, Earth: -5 }, sequence: [{ name: 'Gust', type: 'Air', multiplier: 1 }, { name: 'Gust', type: 'Air', multiplier: 1 }, { name: 'Static Burst', type: 'Air', multiplier: 1.2, status: { type: 'AccuracyDown', magnitude: .08, durationMs: 5000 } }], xp: 28, gold: 9, unlock: 1, loot: 'combat.loot.beast_trophy' },
  'ironjaw-boar': { id: 'ironjaw-boar', name: 'Ironjaw Boar', rank: 'Elite', kind: 'Beast', style: 'Melee', hp: 250, accuracy: 178, maxHit: 16, intervalMs: 3400, evasion: 142, resistance: { ...RESISTANCES, Crush: 26, Fire: -12 }, sequence: [{ name: 'Gore', type: 'Crush', multiplier: 1 }, { name: 'Gore', type: 'Crush', multiplier: 1 }, { name: 'Iron Charge', type: 'Crush', multiplier: 1.55, intervalMultiplier: 1.25, status: { type: 'Stun', magnitude: 1, durationMs: 1000 } }], xp: 80, gold: 30, unlock: 1, loot: 'combat.loot.beast_trophy' },
};
export const NORMAL_ENEMIES: EnemyId[] = ['road-wolf', 'dust-rat', 'ragged-poacher', 'hedge-spark'];
