import { useMemo, useState } from 'react';
import { Badge, Button, Panel } from '../../../ui/primitives';
import { ScreenHeading } from '../../../ui/game/ScreenPrimitives';
import { ActionProgress } from '../../../ui/game/ActionProgress';
import { COOKING_KNIVES, COOKING_METHOD_UNLOCK, COOKING_RECIPES, PHASE1_PANTRY } from '../../../game/content/cooking/cookingContent';
import { canStartCooking, cookingPrepTime, cookingMethodTime, resolveRecipeInputs, type ItemId, type SaveState } from '../../../game/game';

export function CookingScreen({game:g,start,stop,choose,buyPantry,chooseKnife,setSpecialization}: {game:SaveState;start:()=>void;stop:()=>void;choose:(id:string)=>void;buyPantry:(id:ItemId)=>void;chooseKnife:(id:ItemId)=>void;setSpecialization:(value:string|null)=>void}) {
 const [method,setMethod]=useState('All'), [query,setQuery]=useState(''), [showAll,setShowAll]=useState(false); const c=g.cooking, recipe=COOKING_RECIPES.find(x=>x.id===c.recipe)??COOKING_RECIPES[0]!, active=g.activity==='cooking', inputs=resolveRecipeInputs(g,recipe.id), unlocked=COOKING_RECIPES.filter(r=>(showAll||r.unlockLevel<=g.skills.Cooking.level+10)&&(method==='All'||r.method===method)&&r.name.toLowerCase().includes(query.toLowerCase()));
 const ingredientNames=useMemo(()=>inputs?.map(x=>`${g.bank[x.item]??0}× ${x.item.split('.').slice(-1)[0]?.split('_').join(' ')}`)??recipe.inputs.map(x=>x.type==='single'?`${x.amount} ${x.tag}`:x.options.map(o=>`${o.amount} ${o.tag}`).join(' OR ')),[inputs,g.bank,recipe]);
 return <div className="screen profession-screen cooking-screen"><ScreenHeading eyebrow="PROFESSION · FIELD KITCHEN" title="Cooking" sub="Resolve ingredients by tag, prepare the batch, and keep the hearth moving." accent="cooking"><Badge tone={active?'live':'level-badge'}>LEVEL {g.skills.Cooking.level}</Badge></ScreenHeading>
  <div className="profession-grid cooking-grid"><Panel className="profession-rail recipe-browser" title="Recipe Book"><div className="recipe-filters"><label><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> All recipes</label><label className="sr-only" htmlFor="recipe-search">Search recipes</label><input id="recipe-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a recipe"/><select value={method} onChange={e=>setMethod(e.target.value)}><option>All</option>{Object.keys(COOKING_METHOD_UNLOCK).map(x=><option key={x}>{x}</option>)}</select></div><div className="recipe-list">{unlocked.map(r=><button key={r.id} className={`recipe-choice ${r.id===recipe.id?'selected':''} ${r.unlockLevel>g.skills.Cooking.level?'locked':''}`} disabled={active||r.unlockLevel>g.skills.Cooking.level} onClick={()=>r.unlockLevel<=g.skills.Cooking.level&&choose(r.id)}><span className="recipe-level">{r.unlockLevel}</span><span><b>{r.name}</b><small>{r.method} · {r.quantity} {r.foodValue?'servings':'utility'} · {r.xp} XP</small></span><span className="recipe-food">{r.foodValue||'—'}</span></button>)}{unlocked.length===0&&<p className="empty-copy">No recipe matches this filter.</p>}</div></Panel>
   <Panel className={`profession-focus kitchen-focus ${active?'is-active':''}`} title="Preparation Board" action={<Badge tone={active?'live':''}>{active?(c.phase==='prep'?'PREP':'COOK'):'READY'}</Badge>}>
    <div className="kitchen-scene"><div className="hearth-glow"/><div className="pan-shape"/><span>◆</span><small>{recipe.method.toUpperCase()} · {recipe.name.toUpperCase()}</small></div>
    <div className="profession-progress"><div><span>{active?c.phase==='prep'?'PREPARATION':'COOKING':'NEXT BATCH'}</span><b>{active?`${(c.timer/1000).toFixed(1)}s remaining`:recipe.method}</b></div><ActionProgress active={active} remainingMs={c.timer||(c.phase==='prep'?cookingPrepTime(g):cookingMethodTime(g))} durationMs={c.phase==='prep'?cookingPrepTime(g):cookingMethodTime(g)} phaseKey={`cooking:${c.actionSerial}`} label="Cooking phase progress" tone="xp"/></div>
    <div className="ingredient-readout"><span className="tiny-label">RESOLVED INGREDIENTS · LOWEST VALUE FIRST</span>{ingredientNames.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div>
    <div className="profession-actions"><div><strong>{recipe.outputName}</strong><small>{recipe.foodValue?`Food Value ${recipe.foodValue} · Heal ${recipe.foodValue*10} · Satiety 20`:'Utility output · not combat food'}</small></div><label>KNIFE<select value={c.knife} disabled={active} onChange={e=>chooseKnife(e.target.value as ItemId)}>{COOKING_KNIVES.filter(k=>k.id===c.knife||(g.bank[k.id as ItemId]??0)>0&&g.skills.Cooking.level>=k.unlockLevel).map(k=><option key={k.id} value={k.id}>{k.name} · Prep {k.power}</option>)}</select></label><Button tone="copper" disabled={!active&&!canStartCooking(g)} onClick={active?stop:start}>{active?'Stop Cooking':'Start Batch'}</Button></div>
    {c.message&&<p className="inline-warning" role="status">{c.message}</p>}
   </Panel>
   <Panel className="profession-inspector pantry-panel" title="Field Provisions"><p className="panel-note">Provisions currently cover ingredients outside Fishing until Farming and Foraging arrive. One gold per unit.</p><div className="pantry-grid">{Object.values(PHASE1_PANTRY).filter(x=>x.name!=='Field Game Meat').map(item=><button key={item.id} onClick={()=>buyPantry(item.id as ItemId)}><b>{item.name}</b><small>Stock {g.bank[item.id as ItemId]??0} · 1g</small><span>+</span></button>)}</div><label className="specialization-select">COOKING SPECIALIZATION<select value={c.specialization??''} disabled={g.skills.Cooking.level<35||active} onChange={e=>setSpecialization(e.target.value||null)}><option value="">None</option>{['Provisioner','Hearth Chef','Gourmet Chef'].map(x=><option key={x}>{x}</option>)}</select></label><div className="cooking-stats"><span>Recipes <b>{COOKING_RECIPES.length}/43</b></span><span>Meals made <b>{Object.values(c.sessionOutputs).reduce<number>((a,n)=>a+(n??0),0)}</b></span><span>Servings made <b>{Object.values(c.sessionOutputs).reduce<number>((a,n)=>a+(n??0),0)}</b></span></div><div className="station-unlocks">{Object.entries(COOKING_METHOD_UNLOCK).map(([name,level])=><span className={g.skills.Cooking.level>=level?'is-open':'is-locked'} key={name}>{name} <b>{level}</b></span>)}</div></Panel>
  </div>
 </div>;
}
