import { useState } from 'react';
import { DEFAULT_APP_SETTINGS, effectiveScale, type AppSettings } from '../../game/persistence/settingsStorage';
import type { ProfileRecord } from '../../game/persistence/profileIndex';
import { Button, Icon, Modal } from '../../ui/primitives';

type Category = 'Interface' | 'Feedback' | 'Audio' | 'Accessibility' | 'Profile';
const categoryIcon: Record<Category, string> = { Interface: 'gear', Feedback: 'spark', Audio: 'combat', Accessibility: 'shield', Profile: 'helm' };
export function SettingsModal({ settings, profile, saveError, onSettings, onClose, onSwitchProfile, onRenameProfile, onDeleteProfile }: { settings: AppSettings; profile: ProfileRecord | null; saveError?: string; onSettings: (next: AppSettings) => void; onClose: () => void; onSwitchProfile?: () => void; onRenameProfile?: (name: string) => void; onDeleteProfile?: () => void }) {
  const [category, setCategory] = useState<Category>('Interface'), [rename, setRename] = useState(false), [name, setName] = useState(profile?.name ?? ''), [confirmDelete, setConfirmDelete] = useState(false), [error, setError] = useState('');
  const update = (change: (next: AppSettings) => void) => { const next = structuredClone(settings); change(next); onSettings(next); };
  const categories: Category[] = profile ? ['Interface', 'Feedback', 'Audio', 'Accessibility', 'Profile'] : ['Interface', 'Feedback', 'Audio', 'Accessibility'];
  const toggle = (label: string, key: keyof AppSettings['feedback']) => <div className="setting-row" key={key}><div><b>{label}</b></div><button className={`toggle ${settings.feedback[key] ? 'on' : ''}`} role="switch" aria-label={label} aria-checked={settings.feedback[key]} onClick={() => update((next) => { next.feedback[key] = !next.feedback[key]; })}><i /></button></div>;
  return <Modal title="Settings" eyebrow="GAME OPTIONS" onClose={onClose} className="settings-modal">
    <div className="settings-layout"><nav className="settings-categories" aria-label="Settings categories">{categories.map((item) => <button key={item} className={category === item ? 'selected' : ''} aria-current={category === item ? 'page' : undefined} onClick={() => setCategory(item)}><Icon name={categoryIcon[item]} size={17}/><span>{item}</span></button>)}</nav>
      <div className="settings-content" key={category}>{saveError && <p className="settings-save-error" role="alert">{saveError}</p>}
        {category === 'Interface' && <><div className="settings-lead"><h3>Interface</h3><p>Adjust game scale, text size, and pointer behavior.</p></div><div className="setting-row scale-mode"><div><b>Game Scale</b><small>Auto adjusts interface size based on the game window.</small></div><div className="scale-modes"><button className={settings.interface.scaleMode === 'auto' ? 'selected' : ''} onClick={() => update((next) => { next.interface.scaleMode = 'auto'; })}>Auto</button><button className={settings.interface.scaleMode === 'manual' ? 'selected' : ''} onClick={() => update((next) => { next.interface.scaleMode = 'manual'; })}>Manual</button></div></div>
          <label className="range-setting"><span><b>{settings.interface.scaleMode === 'auto' ? `Auto — ${Math.round(effectiveScale(settings) * 100)}%` : `Game Scale — ${Math.round(settings.interface.manualScale * 100)}%`}</b><span>{settings.interface.scaleMode === 'auto' ? 'Based on the current browser window.' : 'Choose a comfortable interface size.'}</span></span><input type="range" min="80" max="160" step="5" disabled={settings.interface.scaleMode === 'auto'} value={settings.interface.scaleMode === 'auto' ? Math.round(effectiveScale(settings) * 100) : Math.round(settings.interface.manualScale * 100)} aria-label="Game Scale" onChange={(event) => update((next) => { next.interface.manualScale = Number(event.target.value) / 100; })} /><output>{Math.round((settings.interface.scaleMode === 'auto' ? effectiveScale(settings) : settings.interface.manualScale) * 100)}%</output></label>
          <label className="range-setting"><span><b>Text Size — {Math.round(settings.interface.textScale * 100)}%</b><span>Changes text independently from interface spacing.</span></span><input type="range" min="90" max="140" step="10" value={Math.round(settings.interface.textScale * 100)} aria-label="Text Size" onChange={(event) => update((next) => { next.interface.textScale = Number(event.target.value) / 100; })} /><output>{Math.round(settings.interface.textScale * 100)}%</output></label>
          <div className="setting-row"><div><b>Custom Game Cursor</b><small>Forged pointers on mouse and trackpad.</small></div><button className={`toggle ${settings.interface.customCursor ? 'on' : ''}`} role="switch" aria-label="Custom Game Cursor" aria-checked={settings.interface.customCursor} onClick={() => update((next) => { next.interface.customCursor = !next.interface.customCursor; })}><i /></button></div>
          <div className="interface-preview"><div className="preview-caption">LIVE PREVIEW</div><div className="preview-content"><small>MINING · COPPER VEIN</small><b>Copper Vein</b><p>Main Vein · 31 / 58 · Next strike 1.2s</p><div className="preview-item"><span className="preview-stone">◆</span><span>Copper Ore</span><b>× 124</b></div><Button tone="copper">Start Mining</Button></div></div></>}
        {category === 'Feedback' && <><div className="settings-lead"><h3>Feedback</h3><p>Choose which gameplay signals appear while you work.</p></div>{toggle('Show XP Drops','showXpDrops')}{toggle('Show Item Gain Feed','showItemGainFeed')}{toggle('Level-Up Effects','levelUpEffects')}{toggle('System Toasts','systemToasts')}<p className="settings-hint">The centered skill ring stays in the shell. Save and profile errors remain visible.</p></>}
        {category === 'Audio' && <><div className="settings-lead"><h3>Audio</h3><p>Control short feedback sounds throughout the game.</p></div><label className="range-setting"><span><b>Master Volume</b><span>Strikes, crafting, and combat feedback.</span></span><input type="range" min="0" max="100" value={Math.round(settings.audio.masterVolume * 100)} aria-label="Master volume" onChange={(event) => update((next) => { next.audio.masterVolume = Number(event.target.value) / 100; })} /><output>{Math.round(settings.audio.masterVolume * 100)}%</output></label><div className="setting-row"><div><b>Mute audio</b><small>Silence all game feedback.</small></div><button className={`toggle ${settings.audio.muted ? 'on' : ''}`} role="switch" aria-label="Mute audio" aria-checked={settings.audio.muted} onClick={() => update((next) => { next.audio.muted = !next.audio.muted; })}><i /></button></div></>}
        {category === 'Accessibility' && <><div className="settings-lead"><h3>Accessibility</h3><p>Choose motion behavior and readable text sizing.</p></div><div className="setting-row"><div><b>Reduced Motion</b><small>Reduce decorative movement and transitions.</small></div><select aria-label="Reduced motion" value={settings.accessibility.reducedMotion} onChange={(event) => update((next) => { next.accessibility.reducedMotion = event.target.value as AppSettings['accessibility']['reducedMotion']; })}><option value="system">System</option><option value="on">On</option><option value="off">Off</option></select></div><div className="accessibility-note"><b>Text Size</b><p>Set this in Interface settings from 90% to 140%.</p><button className="text-action" onClick={() => setCategory('Interface')}>Open Interface settings →</button></div></>}
        {category === 'Profile' && profile && <><div className="settings-lead"><h3>Profile</h3><p>Manage this adventurer’s local save.</p></div><div className="profile-settings-card"><small>PROFILE {profile.slot}</small><b>{profile.name}</b><span>Saved separately on this device</span></div>{rename ? <div className="rename-profile"><label htmlFor="rename-profile">Profile name</label><input id="rename-profile" maxLength={24} value={name} onChange={(event) => setName(event.target.value)} />{error && <p role="alert">{error}</p>}<Button tone="copper" onClick={() => { try { onRenameProfile?.(name); setRename(false); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not rename profile.'); } }}>Save Name</Button></div> : <Button onClick={() => setRename(true)}>Rename Profile</Button>}{error && !rename && <p role="alert">{error}</p>}<div className="profile-actions"><Button onClick={onSwitchProfile}>Switch Profile</Button></div><div className="danger-zone"><b>Danger Zone</b><span>Delete this profile and its saved progress.</span><Button tone="danger" onClick={() => setConfirmDelete(true)}>Delete Profile</Button></div></>}
      </div>
    </div><footer className="settings-modal-footer"><span>{error || (saveError ? 'Save needs attention' : `Interface ${Math.round(effectiveScale(settings) * 100)}% · ${Math.round(settings.interface.textScale * 100)}% text`)}</span>{category === 'Interface' && <Button onClick={() => update((next) => { next.interface = { ...DEFAULT_APP_SETTINGS.interface }; })}>Reset Interface</Button>}<Button onClick={onClose}>Close</Button></footer>
    {confirmDelete && <Modal title="Delete Profile?" eyebrow="DANGER ZONE" onClose={() => setConfirmDelete(false)} className="confirm-modal"><p>Delete <b>{profile?.name}</b> and all saved progress in slot {profile?.slot}?</p><div className="confirm-actions"><Button onClick={() => setConfirmDelete(false)}>Cancel</Button><Button tone="danger" onClick={() => { try { onDeleteProfile?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete profile.'); setConfirmDelete(false); } }}>Delete Profile</Button></div></Modal>}
  </Modal>;
}
