export type CookingMethod = 'Grill' | 'Pot' | 'Oven' | 'Smokehouse' | 'Banquet Station' | 'Prep Table';
export type IngredientRequirement = { type: 'single'; tag: string; amount: number } | { type: 'anyOf'; options: Array<{ tag: string; amount: number }> };
type RawIngredientRequirement = { tag: string; amount: number } | { anyOf: Array<{ tag: string; amount: number }> };
export type CookingInput = IngredientRequirement;
export type CookingRecipe = { id: string; name: string; unlockLevel: number; tier: number; method: CookingMethod; complexity: number; inputs: CookingInput[]; output: string; outputName: string; quantity: number; foodValue: number; prepSeconds: number; cookSeconds: number; xp: number; role: string };
const rows: Array<[number,number,string,CookingMethod,number,RawIngredientRequirement[],string,string,number,number,number,number,number,string]> = [
[1,1,'Grilled River Fish','Grill',1,[{anyOf:[{tag:'Basic Fish',amount:1},{tag:'Small / Schooling',amount:1}]}],'grilled_river_fish','Grilled River Fish',1,12,1.8,3.5,7,'Early direct food'],[4,1,'Riverweed Broth','Pot',1,[{tag:'Basic Fish',amount:1},{tag:'River Weed',amount:1}],'riverweed_broth','Riverweed Broth',2,9,2.2,5.5,9,'Ingredient-efficient early food'],[8,1,'Roasted Root Bowl','Grill',1,[{tag:'Vegetable',amount:1},{tag:'Fruit',amount:1}],'roasted_root_bowl','Roasted Root Bowl',2,8,2,4,8,'Non-Fishing early food'],[9,1,'Fish Strips','Prep Table',1,[{tag:'Small Fish',amount:2}],'fish_strips','Fish Strip',4,0,2,0,8,'Fishing Bait'],
[11,2,'Herbed Reedmere Fillet','Grill',2,[{tag:'Basic Fish',amount:1},{tag:'Herb',amount:1}],'herbed_reedmere_fillet','Herbed Reedmere Fillet',1,20,2.8,4.2,13,'Direct combat food'],[14,2,'Mussel Chowder','Pot',2,[{tag:'Freshwater Mussel',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'mussel_chowder','Mussel Chowder',3,15,3.4,6.5,17,'Multi-serving meal'],[17,2,'Hearty Fisher Stew','Pot',2,[{anyOf:[{tag:'Hearty Fish',amount:1},{tag:'Game Meat',amount:1}]},{tag:'Vegetable',amount:1},{tag:'Herb',amount:1}],'hearty_fisher_stew','Hearty Fisher Stew',3,17,3.6,7,19,'Hearty meal'],[19,2,'Smoked River Ration','Smokehouse',2,[{tag:'Basic Fish',amount:2},{tag:'Herb',amount:1}],'smoked_river_ration','Smoked River Ration',3,14,3.2,9,18,'Provision'],
[21,3,'Silverrun Herb Fillet','Grill',2,[{tag:'Delicate Fish',amount:1},{tag:'Herb',amount:1}],'silverrun_herb_fillet','Silverrun Herb Fillet',1,29,3.2,4.8,24,'High-value direct food'],[24,3,'Crayfish Grain Pot','Pot',3,[{tag:'Crayfish',amount:1},{tag:'Grain',amount:1},{tag:'Vegetable',amount:1}],'crayfish_grain_pot','Crayfish Grain Pot',3,23,4.2,7.5,29,'Efficient servings'],[27,3,'Oily Fish Cakes','Oven',3,[{tag:'Oily Fish',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'oily_fish_cakes','Oily Fish Cakes',2,27,4.5,7,31,'Balanced food'],[29,3,'Fish Oil','Prep Table',2,[{tag:'Oily Fish',amount:2}],'fish_oil','Fish Oil',1,0,3.4,0,26,'Cooking reagent'],
[31,4,'Brackwater Bake','Oven',3,[{tag:'Hearty Fish',amount:1},{tag:'Vegetable',amount:1},{tag:'Herb',amount:1}],'brackwater_bake','Brackwater Bake',2,36,4.8,7.8,39,'Midgame sustain'],[34,4,'Pearlscale Consommé','Pot',4,[{tag:'Rare Delicacy',amount:1},{tag:'Herb',amount:1},{tag:'Brine Kelp',amount:1}],'pearlscale_consomme','Pearlscale Consommé',2,42,5.3,8.5,46,'Rare-food conversion'],[37,4,'Kelp Grain Bowl','Pot',3,[{tag:'Basic Fish',amount:1},{tag:'Grain',amount:1},{tag:'Brine Kelp',amount:1}],'kelp_grain_bowl','Kelp Grain Bowl',3,31,4.6,7.6,41,'Bulk midgame food'],[38,4,'Orchard Fruit Preserve','Pot',2,[{tag:'Fruit',amount:2},{tag:'Grain',amount:1}],'orchard_fruit_preserve','Orchard Fruit Preserve',3,7,3,7,18,'Orchard sink'],[39,4,'Shell Bait','Prep Table',2,[{anyOf:[{tag:'Freshwater Mussel',amount:2},{tag:'Crayfish',amount:2},{tag:'Stormshell',amount:1}]}],'shell_bait','Shell Bait',4,0,3.8,0,34,'Fishing bait'],
[41,5,'Embercoast Seared Predator','Grill',3,[{tag:'Predator Fish',amount:1},{tag:'Herb',amount:1}],'embercoast_seared_predator','Embercoast Seared Predator',1,50,4.6,5.5,54,'Fast high-value food'],[44,5,'Ember Coral Stew','Pot',4,[{tag:'Hearty Fish',amount:1},{tag:'Ember Coral',amount:1},{tag:'Vegetable',amount:1}],'ember_coral_stew','Ember Coral Stew',3,42,5.8,9,61,'Efficient high-tier meal'],[47,5,'Cinder Schoolfish Skewers','Grill',3,[{tag:'Small / Schooling',amount:2},{tag:'Vegetable',amount:1}],'cinder_schoolfish_skewers','Cinder Schoolfish Skewers',4,33,5,6,56,'Bulk Fish conversion'],[49,5,'Spiced Smoked Predator','Smokehouse',4,[{tag:'Predator Fish',amount:2},{tag:'Herb',amount:1}],'spiced_smoked_predator','Spiced Smoked Predator',3,39,5.6,10.5,64,'Provision'],
[51,6,'Frostmere Salmon Roast','Oven',4,[{tag:'Oily Fish',amount:1},{tag:'Herb',amount:1},{tag:'Vegetable',amount:1}],'frostmere_salmon_roast','Frostmere Salmon Roast',1,63,5.5,8.8,72,'High sustain'],[54,6,'Frost Pearl Chowder','Pot',4,[{tag:'Premium Fish',amount:1},{tag:'Frost Pearl',amount:1},{tag:'Grain',amount:1}],'frost_pearl_chowder','Frost Pearl Chowder',3,54,6.2,9.5,80,'Premium multi-serving'],[57,6,'Glacial Sturgeon Platter','Oven',5,[{tag:'Premium Fish',amount:1},{tag:'Vegetable',amount:1},{tag:'Herb',amount:1},{tag:'Mushroom',amount:1}],'glacial_sturgeon_platter','Glacial Sturgeon Platter',3,57,6.8,10,86,'Complex premium food'],[59,6,'Refined Fish Oil','Prep Table',3,[{tag:'Oily Fish',amount:3},{tag:'Frost Pearl',amount:1}],'refined_fish_oil','Refined Fish Oil',2,0,5,0,70,'Advanced reagent'],
[61,7,'Stormreach Barracuda Grill','Grill',4,[{tag:'Predator Fish',amount:1},{tag:'Herb',amount:1},{tag:'Vegetable',amount:1}],'stormreach_barracuda_grill','Stormreach Barracuda Grill',1,76,5.8,6.5,91,'Fast combat food'],[64,7,'Stormshell Stew','Pot',5,[{tag:'Hearty Fish',amount:1},{tag:'Stormshell',amount:1},{tag:'Vegetable',amount:1},{tag:'Herb',amount:1}],'stormshell_stew','Stormshell Stew',3,66,7,10.5,102,'Efficient sustain'],[67,7,'Tempest Ray Bake','Oven',5,[{tag:'Rare Delicacy',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'tempest_ray_bake','Tempest Ray Bake',2,72,7.3,10.8,108,'Rare dish'],[68,7,'Stormfruit Bake','Oven',3,[{tag:'Fruit',amount:2},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'stormfruit_bake','Stormfruit Bake',2,14,5,12,34,'Premium fruit dish'],[69,7,'Storm Rations','Smokehouse',4,[{anyOf:[{tag:'Predator Fish',amount:2},{tag:'Game Meat',amount:2}]},{tag:'Herb',amount:1}],'storm_rations','Storm Rations',4,56,6.4,12.5,96,'Long-idle provisions'],
[71,8,'Aether Herb Plate','Oven',5,[{tag:'Premium Fish',amount:1},{tag:'Herb',amount:1},{tag:'Vegetable',amount:1}],'aether_herb_plate','Aether Herb Plate',2,88,7.4,11,116,'Premium sustain'],[74,8,'Prism Eel Pot','Pot',5,[{tag:'Oily Fish',amount:1},{tag:'Aether Pearl',amount:1},{tag:'Mushroom',amount:1}],'prism_eel_pot','Prism Eel Pot',3,80,7.8,11.5,124,'High-efficiency meal'],[77,8,'Skyglass Banquet','Banquet Station',6,[{tag:'Rare Delicacy',amount:1},{tag:'Premium Fish',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'skyglass_banquet','Skyglass Banquet',6,77,9.5,13,138,'Premium batch'],[79,8,'Aether Glaze','Prep Table',4,[{tag:'Aether Pearl',amount:1},{tag:'Fish Oil',amount:1},{tag:'Herb',amount:1}],'aether_glaze','Aether Glaze',2,0,6,0,104,'Culinary reagent'],
[81,9,'Umbral Cod Bake','Oven',5,[{tag:'Hearty Fish',amount:1},{tag:'Mushroom',amount:1},{tag:'Herb',amount:1}],'umbral_cod_bake','Umbral Cod Bake',2,108,8,11.8,146,'T9 sustain'],[84,9,'Nightfin Steak','Grill',5,[{tag:'Predator Fish',amount:1},{tag:'Aether Glaze',amount:1}],'nightfin_steak','Nightfin Steak',1,120,7.6,7.2,154,'Fast premium food'],[87,9,'Abyssal Ray Stew','Pot',6,[{tag:'Rare Delicacy',amount:1},{tag:'Umbral Ink',amount:1},{tag:'Vegetable',amount:1},{tag:'Herb',amount:1}],'abyssal_ray_stew','Abyssal Ray Stew',4,100,9.2,13,168,'Large rare meal'],[89,9,'Umbral Reduction','Prep Table',5,[{tag:'Umbral Ink',amount:1},{tag:'Refined Fish Oil',amount:1},{tag:'Herb',amount:1}],'umbral_reduction','Umbral Reduction',2,0,7,0,132,'T10 reagent'],
[91,10,'Star Sardine Platter','Oven',5,[{tag:'Small / Schooling',amount:2},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'star_sardine_platter','Star Sardine Platter',4,122,8.4,12,180,'Bulk T10 food'],[94,10,'Comet Tuna Roast','Oven',6,[{tag:'Premium Fish',amount:1},{tag:'Aether Glaze',amount:1},{tag:'Vegetable',amount:1}],'comet_tuna_roast','Comet Tuna Roast',1,145,9.2,12.8,195,'Premium direct food'],[97,10,'Celestial Sturgeon Banquet','Banquet Station',7,[{tag:'Premium Fish',amount:1},{tag:'Rare Delicacy',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1},{tag:'Aether Glaze',amount:1}],'celestial_sturgeon_banquet','Celestial Sturgeon Banquet',6,132,11.5,14.5,218,'Large endgame meal'],[98,10,'Astral Fruit Banquet','Pot',4,[{tag:'Fruit',amount:3},{tag:'Grain',amount:2},{tag:'Herb',amount:1}],'astral_fruit_banquet','Astral Fruit Banquet',4,24,13,20,58,'Endgame fruit meal'],[100,10,'Starveil Feast','Banquet Station',8,[{tag:'Mythic Delicacy',amount:1},{tag:'Star Coral',amount:1},{tag:'Umbral Reduction',amount:1},{tag:'Grain',amount:1},{tag:'Herb',amount:1}],'starveil_feast','Starveil Feast',8,165,13,16,260,'Highest baseline dish'],
];
export const COOKING_RECIPES: CookingRecipe[] = rows.map(([unlockLevel,tier,name,method,complexity,inputs,key,outputName,quantity,foodValue,prepSeconds,cookSeconds,xp,role])=>({id:`cooking.recipe.${key}`,name,unlockLevel,tier,method,complexity,inputs:inputs.map((input): CookingInput => 'anyOf' in input ? ({type:'anyOf',options:input.anyOf}) : ({type:'single',tag:input.tag,amount:input.amount})),output:key==='fish_strips'?'fishing.bait.fish_strip':key==='shell_bait'?'fishing.bait.shell':`${foodValue>0?'cooking.food.':'cooking.utility.'}${key}`,outputName,quantity,foodValue,prepSeconds,cookSeconds,xp,role}));
export const COOKING_METHOD_UNLOCK: Record<CookingMethod,number> = {'Prep Table':1,Grill:1,Pot:10,Oven:25,Smokehouse:35,'Banquet Station':75};
export type CookingKnifeEffect = { preservationPp?: number; prepTimeMultiplier?: number; fishPrepTimeMultiplier?: number; grillOvenCookMultiplier?: number; potSmokehouseCookMultiplier?: number; extraServingPp?: number };
export const COOKING_KNIVES: Array<{id:string;name:string;unlockLevel:number;power:number;prepSpeed:number;effect:string;effects:CookingKnifeEffect}> = [
 {id:'cooking.tool.worn_kitchen_knife',name:'Worn Kitchen Knife',unlockLevel:1,power:5,prepSpeed:0,effect:'None',effects:{}},
 {id:'cooking.tool.copper_kitchen_knife',name:'Copper Kitchen Knife',unlockLevel:5,power:7,prepSpeed:.04,effect:'Ingredient Preservation +2 pp',effects:{preservationPp:2}},
 {id:'cooking.tool.iron_cleaver',name:'Iron Cleaver',unlockLevel:15,power:10,prepSpeed:.08,effect:'Prep Time -3%',effects:{prepTimeMultiplier:.97}},
 {id:'cooking.tool.cobalt_chefs_knife',name:"Cobalt Chef's Knife",unlockLevel:25,power:13,prepSpeed:.12,effect:'Ingredient Preservation +3 pp',effects:{preservationPp:3}},
 {id:'cooking.tool.argent_slicer',name:'Argent Slicer',unlockLevel:35,power:17,prepSpeed:.16,effect:'Extra Serving Chance +3 pp',effects:{extraServingPp:3}},
 {id:'cooking.tool.emberite_cleaver',name:'Emberite Cleaver',unlockLevel:45,power:22,prepSpeed:.20,effect:'Grill/Oven Cook Time -4%',effects:{grillOvenCookMultiplier:.96}},
 {id:'cooking.tool.frostsilver_fillet_knife',name:'Frostsilver Fillet Knife',unlockLevel:55,power:28,prepSpeed:.24,effect:'Fish recipes Prep Time -6%',effects:{fishPrepTimeMultiplier:.94}},
 {id:'cooking.tool.stormiron_chefs_knife',name:"Stormiron Chef's Knife",unlockLevel:65,power:35,prepSpeed:.28,effect:'Pot/Smokehouse Cook Time -5%',effects:{potSmokehouseCookMultiplier:.95}},
 {id:'cooking.tool.aetherite_edge',name:'Aetherite Edge',unlockLevel:75,power:43,prepSpeed:.32,effect:'Ingredient Preservation +5 pp',effects:{preservationPp:5}},
 {id:'cooking.tool.umbral_chefs_knife',name:"Umbral Chef's Knife",unlockLevel:85,power:52,prepSpeed:.36,effect:'Extra Serving Chance +5 pp',effects:{extraServingPp:5}},
 {id:'cooking.tool.astralite_master_knife',name:'Astralite Master Knife',unlockLevel:95,power:62,prepSpeed:.40,effect:'Prep Time -6%; Extra Serving +3 pp',effects:{prepTimeMultiplier:.94,extraServingPp:3}},
];
export const PHASE1_PANTRY: Record<string,{id:string;name:string}> = Object.fromEntries(['Grain','Herb','Vegetable','Fruit','Mushroom','Game Meat'].map((name)=>[name,{id:`cooking.utility.pantry_${name.toLowerCase().split(' ').join('_')}`,name:`Field ${name}`} ]));
