import { useRef, useState } from 'react';
import type { ProfileIndex, ProfileRecord, ProfileSlotId } from '../../game/persistence/profileIndex';
import { Button, Icon, Modal } from '../../ui/primitives';

export function ProfileSelectScreen({ index, onChoose, onCreate, onRename, onDelete, onSettings, error, onRetry }: { index: ProfileIndex; onChoose: (slot: ProfileSlotId) => void; onCreate: (slot: ProfileSlotId, name: string) => void; onRename: (slot: ProfileSlotId, name: string) => void; onDelete: (slot: ProfileSlotId) => void; onSettings: () => void; error?: string; onRetry: () => void }) {
  const [creating, setCreating] = useState<ProfileSlotId | null>(null), [name, setName] = useState(''), [formError, setFormError] = useState(''), nameInput = useRef<HTMLInputElement>(null);
  const [renaming, setRenaming] = useState<ProfileSlotId | null>(null), [renameValue, setRenameValue] = useState(''), [deleting, setDeleting] = useState<ProfileRecord | null>(null);
  const submit = () => { if (!creating) return; try { onCreate(creating, name); setCreating(null); setName(''); setFormError(''); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'Could not create profile.'); requestAnimationFrame(() => nameInput.current?.focus()); } };
  return <><main className="profile-select"><a className="skip-link" href="#profile-choice">Skip to profile slots</a><div className="profile-atmosphere" aria-hidden="true"/><header className="profile-heading"><div className="brand-mark">M<span>X</span></div><div><p>THE FIRST STEPS</p><h1>MX-Idle</h1><small>A quiet frontier, ready when you are.</small></div><button className="icon-button" aria-label="Open Settings" onClick={onSettings}><Icon name="gear" size={20}/></button></header>
    {error && <section className="profile-error" role="alert"><b>Profile data needs attention</b><p>{error}</p><Button onClick={onRetry}>Retry</Button></section>}
    <section className="profile-choice" id="profile-choice" tabIndex={-1}><div className="profile-intro"><span>ADVENTURER RECORDS</span><h2>Choose a Profile</h2><p>Your progress is saved separately for each adventurer.</p></div><div className="profile-grid">{([1,2,3] as ProfileSlotId[]).map((slot) => {
      const record = index.slots[slot - 1];
      return <article className={`profile-card ${record ? 'occupied' : 'empty'}`} key={slot}>{record ? <><ProfileCard profile={record} onChoose={() => onChoose(slot)}/><div className="profile-card-management">{renaming === slot ? <><label htmlFor={`rename-slot-${slot}`}>Adventurer name</label><input id={`rename-slot-${slot}`} maxLength={24} value={renameValue} onChange={(event) => setRenameValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { onRename(slot, renameValue); setRenaming(null); } }}/><Button onClick={() => setRenaming(null)}>Cancel</Button><Button tone="copper" onClick={() => { try { onRename(slot, renameValue); setRenaming(null); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'Could not rename profile.'); } }}>Save Name</Button></> : <><Button onClick={() => { setRenameValue(record.name); setRenaming(slot); }}>Rename</Button><Button tone="danger" onClick={() => setDeleting(record)}>Delete</Button></>}</div>{formError && <p role="alert">{formError}</p>}</> : <><div className="slot-art" aria-hidden="true"><span>✧</span></div><div className="slot-copy"><small>PROFILE SLOT {slot}</small><h3>Unwritten Path</h3><p>A new journey begins here.</p></div><Button tone="copper" onClick={() => { setCreating(slot); setName(''); }}>Create Profile</Button></>}
      {creating === slot && <div className="profile-create"><label htmlFor="profile-name">Name your adventurer</label><input id="profile-name" ref={nameInput} autoComplete="off" maxLength={24} value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') submit(); }} placeholder="e.g. Adventurer"/>{formError && <p role="alert">{formError}</p>}<small>{name.trim().length}/24</small><div><Button tone="quiet" onClick={() => setCreating(null)}>Cancel</Button><Button tone="copper" onClick={submit}>Begin</Button></div></div>}</article>;
    })}</div><footer className="profile-footer"><span>Three local profiles · saved on this device</span><button className="text-action" onClick={onSettings}><Icon name="gear" size={15}/> Settings</button></footer></section>
  </main>{deleting && <Modal title="Delete Profile?" eyebrow="DANGER ZONE" onClose={() => setDeleting(null)} className="confirm-modal"><p>Delete <b>{deleting.name}</b> and all saved progress in slot {deleting.slot}?</p><div className="confirm-actions"><Button onClick={() => setDeleting(null)}>Cancel</Button><Button tone="danger" onClick={() => { onDelete(deleting.slot); setDeleting(null); }}>Delete Profile</Button></div></Modal>}</>;
}

function ProfileCard({ profile, onChoose }: { profile: ProfileRecord; onChoose: () => void }) {
  const date = profile.lastPlayedAt ? new Date(profile.lastPlayedAt).toLocaleDateString() : 'Not played yet';
  const time = profile.activePlayTimeMs < 60_000 ? '< 1m' : `${Math.floor(profile.activePlayTimeMs / 3_600_000)}h ${Math.floor(profile.activePlayTimeMs / 60_000) % 60}m`;
  const activity = profile.summary.activity === 'idle' ? 'Idle' : profile.summary.activity === 'mining' ? 'Mining · Copper Vein' : profile.summary.activity === 'smelting' ? 'Smithing · Copper Ingot' : profile.summary.activity === 'forging' ? 'Smithing · Copper Work' : profile.summary.activity === 'combat' ? 'Combat · Road Wolf' : profile.summary.activity;
  return <><div className="profile-card-top"><small>PROFILE {profile.slot}</small><span>LAST PLAYED · {date}</span></div><div className="profile-name"><div className="profile-avatar" aria-hidden="true">{profile.name.slice(0,1).toUpperCase()}</div><div><h3>{profile.name}</h3><p>{activity}</p></div></div><div className="profile-levels"><span>Mining <b>{profile.summary.miningLevel}</b></span><span>Smithing <b>{profile.summary.smithingLevel}</b></span><span>Attack <b>{profile.summary.attackLevel}</b></span><span>Defence <b>{profile.summary.defenceLevel}</b></span><span>Hitpoints <b>{profile.summary.hitpointsLevel}</b></span></div><div className="profile-card-bottom"><span>{time} active</span><span>{profile.summary.firstWolfKill ? 'First wolf defeated' : 'First wolf ahead'}</span></div><Button tone="copper" onClick={onChoose}>Continue</Button></>;
}
