import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const out = 'artifacts/qa';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 1920, height: 1080 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
const shot = async (name) => page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
const wait = (ms) => page.waitForTimeout(ms);

await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
assert.equal(await page.locator('h1').innerText(), 'Mining');
await shot('mining-ready-1920');
await page.getByRole('button', { name: /Start Mining/ }).click();
await shot('mining-active-1920');
await page.getByRole('button', { name: 'DEV' }).click();
await page.getByRole('button', { name: '×20 speed' }).click();
await wait(3300);
assert.match(await page.locator('.cycle-footer').innerText(), /Ore this session\s+\d+/);
await page.getByRole('button', { name: /Stop Mining/ }).first().click();
await page.getByRole('button', { name: /^Smithing/ }).first().click();
await page.getByRole('button', { name: '+20 Copper Ore' }).click();
await page.getByRole('button', { name: /Start Smelting/ }).click();
await shot('smithing-smelting-active-1920');
await wait(3100);
await page.getByRole('tab', { name: /^Forging/ }).click();
await page.getByRole('button', { name: 'Smithing Lv. 5' }).click();
await page.getByRole('button', { name: 'DEV' }).click();
await page.getByRole('button', { name: /Copper Sword.*4 Ingots/ }).click();
await page.getByRole('button', { name: /Begin Forging/ }).click();
await shot('smithing-forging-active-1920');
await wait(1400);
assert.equal(await page.locator('.candidate-count').count(), 0);
await page.locator('.recipe-choice').filter({ hasText: 'Copper Helm' }).click();
await page.getByRole('button', { name: /Begin Forging/ }).click();
await wait(900);
await page.getByRole('button', { name: 'Equipment', exact: true }).click();
await page.locator('.candidate-row').filter({ hasText: 'Copper Sword' }).getByRole('button', { name: 'Equip' }).click();
await page.locator('.candidate-row').filter({ hasText: 'Copper Helm' }).getByRole('button', { name: 'Equip' }).click();
await shot('equipment-1920');
await page.getByRole('button', { name: 'Combat' }).click();
assert.equal(await page.getByRole('button', { name: /Begin Combat/ }).isDisabled(), false);
await page.getByRole('button', { name: /Begin Combat/ }).click();
await shot('combat-road-wolf-1920');
await wait(1700);
await page.getByRole('button', { name: 'DEV' }).click();
await page.getByRole('button', { name: 'Away 5m' }).click();
assert.equal(await page.getByRole('dialog').count(), 1);
await shot('offline-summary-1920');
await page.getByRole('button', { name: 'Continue' }).click();
await page.setViewportSize({ width: 1366, height: 768 });
await shot('combat-1366');
await page.setViewportSize({ width: 768, height: 900 });
await shot('combat-tablet-768');
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'no tablet horizontal overflow');
await page.reload({ waitUntil: 'networkidle' });
await wait(300);
assert.equal(await page.locator('h1').innerText(), 'Broken Road', 'screen persists across reload');
await page.keyboard.press('Tab');
assert.equal(await page.evaluate(() => document.activeElement?.matches(':focus-visible')), true, 'keyboard focus is visible');
await page.getByRole('button', { name: 'Settings' }).click();
assert.equal(await page.getByRole('dialog').count(), 1);
await page.getByRole('switch', { name: 'Mute audio' }).click();
assert.equal(await page.getByRole('switch', { name: 'Mute audio' }).getAttribute('aria-checked'), 'true');
await page.getByRole('switch', { name: 'Mute audio' }).click();
await page.getByRole('slider', { name: 'Master volume' }).evaluate((el) => { el.value = '40'; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); });
await page.getByLabel('Reduced motion').selectOption('on');
await shot('settings-tablet');
await page.getByRole('button', { name: 'Close settings' }).click();
await page.getByRole('button', { name: 'Bank', exact: true }).click();
await page.locator('.bank-item .tip-wrap').first().hover();
assert.equal(await page.getByRole('tooltip').first().isVisible(), true, 'bank item tooltip opens on hover');
assert.deepEqual(errors, []);
console.log(JSON.stringify({ screenshots: out, consoleErrors: errors, page: await page.locator('h1').innerText(), saved: await page.evaluate((key) => !!localStorage.getItem(key), 'mx-idle-save-v1') }, null, 2));
await browser.close();
