import { useState } from 'react';
import { Button } from '../../ui/primitives';
import { ITEMS, COMBAT_AREAS, DUNGEONS, ENEMIES, type EnemyId, type ItemId, type SaveState } from '../../game/game';
import { FISHING_SPOTS, FISH_SPECIES, FISHING_RODS } from '../../game/content/fishing/fishingContent';
import { COOKING_KNIVES, COOKING_RECIPES, PHASE1_PANTRY } from '../../game/content/cooking/cookingContent';
import { MINING_TOOLS } from '../../game/content/mining/miningTools';

export function DevPanel({ game: g, grant, grantT1Kit, simulate, setSpeed, setLevel, setHp, resetEnemy, setEnemy, setArea, grantEquip, forceEnemyDefeat, reset, setDeposit, setStage , setForge, setPreservation,setFishingSpot,setFishingForce,setCookingRecipe,setCookingForce,setSatiety,setFoodStock,clearFoodLock,setTierProgress,setBossFirstKill,resetTierProgress,setEnemyHpPercent,setEnemyPhase,setSequenceStep,startDungeonAt }: { game: SaveState; grant: (id: ItemId, n?: number) => void; grantT1Kit: () => void; simulate: (ms: number) => void; setSpeed: (n: number) => void; setLevel: (skill: keyof SaveState['skills'], level: number) => void; setHp: (hp: number) => void; resetEnemy: () => void; setEnemy:(id:EnemyId)=>void;setArea:(id:string)=>void;grantEquip:(id:ItemId)=>void;forceEnemyDefeat:()=>void; reset: () => void; setDeposit: (id: SaveState['mining']['deposit']) => void; setStage: (stage: number) => void; setForge: (work: number, heat: number) => void; setPreservation: (enabled: boolean) => void;setFishingSpot:(id:string)=>void;setFishingForce:(species:string|null,double:boolean,find:boolean)=>void;setCookingRecipe:(id:string)=>void;setCookingForce:(preserve:boolean,extra:boolean)=>void;setSatiety:(value:number)=>void;setFoodStock:(item:ItemId,amount:number)=>void;clearFoodLock:()=>void;setTierProgress:(tier:number,unlocked:boolean)=>void;setBossFirstKill:(id:EnemyId,value:boolean)=>void;resetTierProgress:(tier:number)=>void;setEnemyHpPercent:(percent:number)=>void;setEnemyPhase:(phase:number)=>void;setSequenceStep:(step:number)=>void;startDungeonAt:(id:string,index:number)=>void }) {
  const [open, setOpen] = useState(false);
  const [devFish,setDevFish]=useState(FISH_SPECIES[0]!.id),[devRecipe,setDevRecipe]=useState(COOKING_RECIPES[0]!.id),[devFood,setDevFood]=useState(COOKING_RECIPES.find(r=>r.foodValue>0)!.output as ItemId),[devSpot,setDevSpot]=useState(FISHING_SPOTS[0]!.id),[devTier,setDevTier]=useState(1),[devEnemy,setDevEnemy]=useState<EnemyId>('road-wolf'),[devArea,setDevArea]=useState('broken-road'),[devDungeon,setDevDungeon]=useState('t1-ruined-watch'),[devBoss,setDevBoss]=useState<EnemyId>('captain-veyr'),[devEncounter,setDevEncounter]=useState(0),[devHpPercent,setDevHpPercent]=useState(50),[devPhase,setDevPhase]=useState(1),[devSequence,setDevSequence]=useState(0),[devOffering,setDevOffering]=useState<ItemId>('combat.loot.t1_beast_trophy'),[devEliteComponent,setDevEliteComponent]=useState<ItemId>('combat.loot.t1_elite_component'),[devBossComponent,setDevBossComponent]=useState<ItemId>('combat.loot.t1_boss_component'),[devGear,setDevGear]=useState<ItemId>(Object.entries(ITEMS).find(([,item])=>item.equipment?.context==='combat')?.[0] as ItemId),[devTool,setDevTool]=useState<ItemId>(MINING_TOOLS['item.mining.worn_pickaxe'].item),[devItem,setDevItem]=useState<ItemId>('item.mining.copper_ore');
  const tierEnemies=Object.values(ENEMIES).filter(enemy=>enemy.tier===devTier),tierAreas=Object.values(COMBAT_AREAS).filter(area=>area.tier===devTier),tierDungeons=Object.values(DUNGEONS).filter(dungeon=>dungeon.tier===devTier),devBosses=Object.values(ENEMIES).filter(enemy=>enemy.tier===devTier&&enemy.rank==='Boss'),offerings=Object.entries(ITEMS).filter(([,item])=>item.category==='Offerings'),eliteComponents=Object.entries(ITEMS).filter(([,item])=>item.category==='Elite Components'),bossComponents=Object.entries(ITEMS).filter(([,item])=>item.category==='Boss Components');
  const combatGear=Object.entries(ITEMS).filter(([,item])=>item.equipment?.context==='combat');
  const professionGear=Object.entries(ITEMS).filter(([,item])=>item.equipment?.context==='profession'&&['Pickaxe','Hammer','Rod','Tackle','Knife'].includes(item.equipment.slot));
  const registeredItems=Object.entries(ITEMS);

  return <div className={`dev-panel ${open ? 'open' : ''}`}><button onClick={() => setOpen(!open)} aria-expanded={open}>DEV</button>{open && <div className="dev-controls"><b>Phase 1 playtest tools</b>
    <div className="dev-row"><Button tone="quiet" onClick={() => setLevel('Mining', 5)}>Mining Lv. 5</Button><Button tone="quiet" onClick={() => setLevel('Mining', 100)}>Mining Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Smithing', 5)}>Smithing Lv. 5</Button><Button tone="quiet" onClick={() => setLevel('Smithing', 100)}>Smithing Lv. 100</Button><Button tone="quiet" onClick={() => setDeposit('mining.deposit.copper_vein')}>Copper Vein</Button><Button tone="quiet" onClick={() => setDeposit('mining.deposit.fieldstone_quarry')}>Fieldstone</Button></div>
    <div className="dev-row"><Button tone="quiet" onClick={() => setLevel('Attack', 100)}>Attack Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Defence', 100)}>Defence Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Hitpoints', 100)}>Hitpoints Lv. 100</Button><label>Tier <select aria-label="Dev Combat Tier" value={devTier} onChange={e=>{const tier=Number(e.target.value);setDevTier(tier);const nextArea=Object.values(COMBAT_AREAS).find(x=>x.tier===tier&&x.kind==='area');const nextDungeon=Object.values(DUNGEONS).find(x=>x.tier===tier);const nextEnemy=Object.values(ENEMIES).find(x=>x.tier===tier&&x.rank==='Normal');const nextBoss=Object.values(ENEMIES).find(x=>x.tier===tier&&x.rank==='Boss');if(nextArea)setDevArea(nextArea.id);if(nextDungeon)setDevDungeon(nextDungeon.id);if(nextEnemy)setDevEnemy(nextEnemy.id);if(nextBoss)setDevBoss(nextBoss.id);}}>{Array.from({length:10},(_,i)=>i+1).map(t=><option key={t} value={t}>T{t}</option>)}</select></label></div>
    <div className="dev-row"><select aria-label="Dev Combat Area" value={devArea} onChange={e=>setDevArea(e.target.value)}>{tierAreas.map(area=><option key={area.id} value={area.id}>{area.kind.toUpperCase()} · {area.name}</option>)}</select><Button tone="quiet" onClick={()=>setArea(devArea)}>Set Area</Button><select aria-label="Dev Combat enemy" value={devEnemy} onChange={e=>setDevEnemy(e.target.value)}>{tierEnemies.map(enemy=><option key={enemy.id} value={enemy.id}>{enemy.name} · {enemy.rank}</option>)}</select><Button tone="quiet" onClick={()=>setEnemy(devEnemy)}>Set Target</Button><select aria-label="Dev Combat gear" value={devGear} onChange={e=>setDevGear(e.target.value as ItemId)}>{combatGear.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grantEquip(devGear)}>Grant &amp; Equip</Button><Button tone="quiet" onClick={forceEnemyDefeat}>Force Enemy Defeat</Button></div>
    <div className="dev-row"><select aria-label="Dev Dungeon" value={devDungeon} onChange={e=>setDevDungeon(e.target.value)}>{tierDungeons.map(dungeon=><option key={dungeon.id} value={dungeon.id}>{dungeon.name}</option>)}</select><label>Encounter <select aria-label="Dev Dungeon Encounter" value={devEncounter} onChange={e=>setDevEncounter(Number(e.target.value))}>{[0,1,2,3].map((index)=><option key={index} value={index}>{index+1} · {ENEMIES[tierDungeons[0]!.encounters[index]!]!.name}</option>)}</select></label><Button tone="quiet" onClick={()=>startDungeonAt(devDungeon,devEncounter)}>Start Dungeon at encounter</Button></div>
    <div className="dev-row"><Button tone="quiet" onClick={()=>setTierProgress(devTier,true)}>Unlock Tier</Button><Button tone="quiet" onClick={()=>setTierProgress(devTier,false)}>Lock Tier</Button><select aria-label="Dev Boss progression" value={devBoss} onChange={e=>setDevBoss(e.target.value)}>{devBosses.map(boss=><option key={boss.id} value={boss.id}>{boss.name}</option>)}</select><Button tone="quiet" onClick={()=>setBossFirstKill(devBoss,true)}>Set Boss First Kill</Button><Button tone="quiet" onClick={()=>resetTierProgress(devTier)}>Reset Tier Progress</Button></div>
    <div className="dev-row"><label>Enemy HP % <input aria-label="Dev Enemy HP Percent" type="number" min="0" max="100" value={devHpPercent} onChange={e=>setDevHpPercent(Number(e.target.value))}/></label><Button tone="quiet" onClick={()=>setEnemyHpPercent(devHpPercent)}>Set HP</Button><label>Boss phase <select aria-label="Dev Boss Phase" value={devPhase} onChange={e=>setDevPhase(Number(e.target.value))}>{[0,...(ENEMIES[devEnemy]?.phases??[]).map((_,i)=>i+1)].map((phase)=><option key={phase} value={phase}>{phase===0?'Phase 1':`Phase ${phase+1}`}</option>)}</select></label><Button tone="quiet" onClick={()=>setEnemyPhase(devPhase)}>Set Phase</Button><label>Sequence step <input aria-label="Dev Sequence Step" type="number" min="0" value={devSequence} onChange={e=>setDevSequence(Number(e.target.value))}/></label><Button tone="quiet" onClick={()=>setSequenceStep(devSequence)}>Set Step</Button></div>
    <div className="dev-row"><select aria-label="Dev Force Offering" value={devOffering} onChange={e=>setDevOffering(e.target.value as ItemId)}>{offerings.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devOffering)}>Grant Offering</Button><select aria-label="Dev Force Elite Component" value={devEliteComponent} onChange={e=>setDevEliteComponent(e.target.value as ItemId)}>{eliteComponents.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devEliteComponent)}>Grant Elite Component</Button><select aria-label="Dev Force Boss Component" value={devBossComponent} onChange={e=>setDevBossComponent(e.target.value as ItemId)}>{bossComponents.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devBossComponent)}>Grant Boss Component</Button></div>
    <div className="dev-row"><select aria-label="Dev profession gear" value={devTool} onChange={e=>setDevTool(e.target.value as ItemId)}>{professionGear.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grantEquip(devTool)}>Grant &amp; Equip Tool</Button><select aria-label="Dev grant item" value={devItem} onChange={e=>setDevItem(e.target.value as ItemId)}>{registeredItems.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devItem,10)}>Grant ×10</Button></div>
    <div className="dev-row"><Button tone="quiet" onClick={() => setLevel('Fishing', 100)}>Fishing Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Cooking', 100)}>Cooking Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Fishing', 1)}>Fishing Lv. 1</Button><Button tone="quiet" onClick={() => setLevel('Cooking', 1)}>Cooking Lv. 1</Button></div>
    <div className="dev-row"><select aria-label="Dev Fishing Spot" value={devSpot} onChange={e=>setDevSpot(e.target.value)}>{FISHING_SPOTS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>setFishingSpot(devSpot)}>Select Spot</Button><select aria-label="Dev Fish" value={devFish} onChange={e=>setDevFish(e.target.value)}>{FISH_SPECIES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devFish as ItemId,20)}>Grant Fish</Button><Button tone="quiet" onClick={()=>setFishingForce(devFish,true,true)}>Force Catch + Double + Find</Button></div>
    <div className="dev-row">{FISHING_RODS.map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId)}>Grant {x.name}</Button>)}</div>
    <div className="dev-row"><select aria-label="Dev Cooking Recipe" value={devRecipe} onChange={e=>setDevRecipe(e.target.value)}>{COOKING_RECIPES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>setCookingRecipe(devRecipe)}>Select Recipe</Button><Button tone="quiet" onClick={()=>setCookingForce(true,true)}>Force Preservation + Serving</Button></div>
    <div className="dev-row">{Object.values(PHASE1_PANTRY).map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId,25)}>Grant {x.name}</Button>)}{COOKING_KNIVES.map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId)}>Grant {x.name}</Button>)}</div>
    <div className="dev-row"><select aria-label="Dev Combat Food" value={devFood} onChange={e=>setDevFood(e.target.value as ItemId)}>{COOKING_RECIPES.filter(r=>r.foodValue>0).map(x=><option key={x.output} value={x.output}>{x.outputName}</option>)}</select><Button tone="quiet" onClick={()=>setFoodStock(devFood,100)}>Set Food ×100</Button><Button tone="quiet" onClick={()=>setSatiety(90)}>Satiety 90</Button><Button tone="quiet" onClick={()=>setSatiety(100)}>Satiety 100</Button><Button tone="quiet" onClick={clearFoodLock}>Clear Food Lock</Button></div>
    <div className="dev-row">{[0, 1, 2, 3, 4].map((stage) => <Button tone="quiet" key={stage} onClick={() => setStage(stage)}>Stage {stage + 1}</Button>)}</div>
    <div className="dev-row">{(['item.mining.copper_ore', 'item.smithing.copper_ingot', 'item.mining.copper_pickaxe', 'item.smithing.copper_smithing_hammer'] as ItemId[]).map((id) => <Button tone="quiet" key={id} onClick={() => grant(id, id.endsWith('copper_ore') || id.endsWith('copper_ingot') ? 20 : 1)}>Grant {ITEMS[id].name}</Button>)}</div>
    <div className="dev-row"><Button tone="quiet" onClick={grantT1Kit}>Grant T1 field kit</Button><Button tone="quiet" onClick={() => setForge(0, 100)}>Reset Work / Heat</Button><Button tone="quiet" onClick={() => setForge(g.smithing.work || 30, 20)}>Set Work 30 / Heat 20</Button><Button tone="quiet" onClick={() => setPreservation(!g.smithing.forcePreservation)}>{g.smithing.forcePreservation ? 'Preservation forced' : 'Force preservation'}</Button></div>
    <div className="dev-row">{[1, 5, 20].map((x) => <Button tone={x === 1 ? 'steel' : 'quiet'} key={x} onClick={() => setSpeed(x)}>×{x} speed</Button>)}</div>
    <div className="dev-row"><Button tone="quiet" onClick={() => setHp(1000)}>Full HP</Button><Button tone="quiet" onClick={resetEnemy}>Reset Enemy</Button><Button tone="quiet" onClick={clearFoodLock}>Clear Food Lock / Stun</Button><Button tone="quiet" onClick={() => simulate(300000)}>Away 5m</Button><Button tone="quiet" onClick={() => simulate(3600000)}>Away 1h</Button></div>
    <Button tone="danger" onClick={reset}>Reset save</Button>
  </div>}</div>;
}
