import { useState } from 'react';
import { Button } from '../../ui/primitives';
import { ITEMS, type ItemId, type SaveState } from '../../game/game';
import { FISHING_SPOTS, FISH_SPECIES, FISHING_RODS } from '../../game/content/fishing/fishingContent';
import { COOKING_KNIVES, COOKING_RECIPES, PHASE1_PANTRY } from '../../game/content/cooking/cookingContent';

export function DevPanel({ game: g, grant, grantT1Kit, simulate, setSpeed, setLevel, setHp, resetWolf, reset, unlockElite, setDeposit, setStage , setForge, setPreservation,setFishingSpot,setFishingForce,setCookingRecipe,setCookingForce,setSatiety,setFoodStock,clearFoodLock }: { game: SaveState; grant: (id: ItemId, n?: number) => void; grantT1Kit: () => void; simulate: (ms: number) => void; setSpeed: (n: number) => void; setLevel: (skill: keyof SaveState['skills'], level: number) => void; setHp: (hp: number) => void; resetWolf: () => void; reset: () => void; unlockElite: () => void; setDeposit: (id: SaveState['mining']['deposit']) => void; setStage: (stage: number) => void; setForge: (work: number, heat: number) => void; setPreservation: (enabled: boolean) => void;setFishingSpot:(id:string)=>void;setFishingForce:(species:string|null,double:boolean,find:boolean)=>void;setCookingRecipe:(id:string)=>void;setCookingForce:(preserve:boolean,extra:boolean)=>void;setSatiety:(value:number)=>void;setFoodStock:(item:ItemId,amount:number)=>void;clearFoodLock:()=>void }) {
  const [open, setOpen] = useState(false);
  const [devFish,setDevFish]=useState(FISH_SPECIES[0]!.id),[devRecipe,setDevRecipe]=useState(COOKING_RECIPES[0]!.id),[devFood,setDevFood]=useState(COOKING_RECIPES.find(r=>r.foodValue>0)!.output as ItemId),[devSpot,setDevSpot]=useState(FISHING_SPOTS[0]!.id);

  return <div className={`dev-panel ${open ? 'open' : ''}`}><button onClick={() => setOpen(!open)} aria-expanded={open}>DEV</button>{open && <div className="dev-controls"><b>Phase 1 playtest tools</b>
    <div className="dev-row"><Button tone="quiet" onClick={() => setLevel('Mining', 5)}>Mining Lv. 5</Button><Button tone="quiet" onClick={() => setLevel('Mining', 100)}>Mining Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Smithing', 5)}>Smithing Lv. 5</Button><Button tone="quiet" onClick={() => setLevel('Smithing', 100)}>Smithing Lv. 100</Button><Button tone="quiet" onClick={() => setDeposit('mining.deposit.copper_vein')}>Copper Vein</Button><Button tone="quiet" onClick={() => setDeposit('mining.deposit.fieldstone_quarry')}>Fieldstone</Button></div>
    <div className="dev-row"><Button tone="quiet" onClick={() => setLevel('Fishing', 100)}>Fishing Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Cooking', 100)}>Cooking Lv. 100</Button><Button tone="quiet" onClick={() => setLevel('Fishing', 1)}>Fishing Lv. 1</Button><Button tone="quiet" onClick={() => setLevel('Cooking', 1)}>Cooking Lv. 1</Button></div>
    <div className="dev-row"><select aria-label="Dev Fishing Spot" value={devSpot} onChange={e=>setDevSpot(e.target.value)}>{FISHING_SPOTS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>setFishingSpot(devSpot)}>Select Spot</Button><select aria-label="Dev Fish" value={devFish} onChange={e=>setDevFish(e.target.value)}>{FISH_SPECIES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>grant(devFish as ItemId,20)}>Grant Fish</Button><Button tone="quiet" onClick={()=>setFishingForce(devFish,true,true)}>Force Catch + Double + Find</Button></div>
    <div className="dev-row">{FISHING_RODS.map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId)}>Grant {x.name}</Button>)}</div>
    <div className="dev-row"><select aria-label="Dev Cooking Recipe" value={devRecipe} onChange={e=>setDevRecipe(e.target.value)}>{COOKING_RECIPES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button tone="quiet" onClick={()=>setCookingRecipe(devRecipe)}>Select Recipe</Button><Button tone="quiet" onClick={()=>setCookingForce(true,true)}>Force Preservation + Serving</Button></div>
    <div className="dev-row">{Object.values(PHASE1_PANTRY).map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId,25)}>Grant {x.name}</Button>)}{COOKING_KNIVES.map(x=><Button tone="quiet" key={x.id} onClick={()=>grant(x.id as ItemId)}>Grant {x.name}</Button>)}</div>
    <div className="dev-row"><select aria-label="Dev Combat Food" value={devFood} onChange={e=>setDevFood(e.target.value as ItemId)}>{COOKING_RECIPES.filter(r=>r.foodValue>0).map(x=><option key={x.output} value={x.output}>{x.outputName}</option>)}</select><Button tone="quiet" onClick={()=>setFoodStock(devFood,100)}>Set Food ×100</Button><Button tone="quiet" onClick={()=>setSatiety(90)}>Satiety 90</Button><Button tone="quiet" onClick={()=>setSatiety(100)}>Satiety 100</Button><Button tone="quiet" onClick={clearFoodLock}>Clear Food Lock</Button></div>
    <div className="dev-row">{[0, 1, 2, 3, 4].map((stage) => <Button tone="quiet" key={stage} onClick={() => setStage(stage)}>Stage {stage + 1}</Button>)}</div>
    <div className="dev-row">{(['item.mining.copper_ore', 'item.smithing.copper_ingot', 'item.mining.copper_pickaxe', 'item.smithing.copper_smithing_hammer'] as ItemId[]).map((id) => <Button tone="quiet" key={id} onClick={() => grant(id, id.endsWith('copper_ore') || id.endsWith('copper_ingot') ? 20 : 1)}>Grant {ITEMS[id].name}</Button>)}</div>
    <div className="dev-row"><Button tone="quiet" onClick={grantT1Kit}>Grant T1 field kit</Button><Button tone="quiet" onClick={() => setForge(0, 100)}>Reset Work / Heat</Button><Button tone="quiet" onClick={() => setForge(g.smithing.work || 30, 20)}>Set Work 30 / Heat 20</Button><Button tone="quiet" onClick={() => setPreservation(!g.smithing.forcePreservation)}>{g.smithing.forcePreservation ? 'Preservation forced' : 'Force preservation'}</Button></div>
    <div className="dev-row">{[1, 5, 20].map((x) => <Button tone={x === 1 ? 'steel' : 'quiet'} key={x} onClick={() => setSpeed(x)}>×{x} speed</Button>)}</div>
    <div className="dev-row"><Button tone="quiet" onClick={() => setHp(100)}>Full HP</Button><Button tone="quiet" onClick={resetWolf}>Reset Enemy</Button><Button tone="quiet" onClick={unlockElite}>Unlock Ironjaw</Button><Button tone="quiet" onClick={() => simulate(300000)}>Away 5m</Button><Button tone="quiet" onClick={() => simulate(3600000)}>Away 1h</Button></div>
    <Button tone="danger" onClick={reset}>Reset save</Button>
  </div>}</div>;
}
