export type FishRarity = 'Common' | 'Uncommon' | 'Rare' | 'Very Rare';
export type WaterTag = 'Surface' | 'Midwater' | 'Bottom';
export type FishDefinition = { id: string; name: string; spotId: string; tier: number; unlockLevel: number; rarity: FishRarity; weight: number; water: WaterTag; predator: boolean; preferredBait: string; quantity: number; fight: number; xp: number; cookingClass: string };
export type FishingSpot = { id: string; name: string; tier: number; unlockLevel: number; rod: string; baseBiteMs: number; findId: string; findName: string; findChance: number };

export const FISHING_SPOTS: FishingSpot[] = [
  ['meadow_brook','Meadow Brook',1,'Old Handline',3200,'river_weed','River Weed',.04],['reedmere_pond','Reedmere Pond',11,'Reed Rod',3400,'freshwater_mussel','Freshwater Mussel',.04],['silverrun_river','Silverrun River',21,'Alder Rod',3600,'crayfish','Crayfish',.04],['brackwater_estuary','Brackwater Estuary',31,'Ironwood Rod',3800,'brine_kelp','Brine Kelp',.04],['embercoast','Embercoast',41,'Silverpine Rod',4000,'ember_coral','Ember Coral',.035],['frostmere_lake','Frostmere Lake',51,'Emberwood Rod',4200,'frost_pearl','Frost Pearl',.035],['stormreach_shoals','Stormreach Shoals',61,'Frostbark Rod',4400,'stormshell','Stormshell',.03],['aetherdeep_basin','Aetherdeep Basin',71,'Stormwillow Rod',4600,'aether_pearl','Aether Pearl',.025],['umbral_trench','Umbral Trench',81,'Aetherwood Rod',4800,'umbral_ink','Umbral Ink',.025],['astral_expanse','Astral Expanse',91,'Umbralwood Rod',5000,'star_coral','Star Coral',.02],
].map(([key,name,tier,rod,baseBiteMs,find,findName,findChance]) => ({ id:`fishing.spot.${key}`, name:String(name), tier:Number(tier), unlockLevel:Number(tier), rod:String(rod), baseBiteMs:Number(baseBiteMs), findId:`fishing.find.${find}`, findName:String(findName), findChance:Number(findChance) }));

const raw: Array<[number,string,string,number,string,FishRarity,number,WaterTag,boolean,string,number,number,number,string]> = [
[1,'meadow_brook','brook_minnow',1,'Brook Minnow','Common',46,'Surface',false,'worm',2,6,6,'Small / Schooling'],[1,'meadow_brook','river_perch',3,'River Perch','Uncommon',30,'Midwater',false,'insect',1,8,8,'Basic Fish'],[1,'meadow_brook','mudfin',6,'Mudfin','Rare',18,'Bottom',false,'worm',1,10,11,'Hearty Fish'],[1,'meadow_brook','glassscale_trout',9,'Glassscale Trout','Very Rare',6,'Midwater',true,'insect',1,14,16,'Delicate Fish'],
[2,'reedmere_pond','reed_carp',11,'Reed Carp','Common',46,'Bottom',false,'worm',1,10,9,'Hearty Fish'],[2,'reedmere_pond','marsh_bream',13,'Marsh Bream','Uncommon',30,'Midwater',false,'insect',1,12,12,'Basic Fish'],[2,'reedmere_pond','blueback_pike',16,'Blueback Pike','Rare',18,'Midwater',true,'fish_strip',1,16,16,'Predator Fish'],[2,'reedmere_pond','moonbelly_eel',19,'Moonbelly Eel','Very Rare',6,'Bottom',true,'shell',1,20,23,'Oily Fish'],
[3,'silverrun_river','silver_trout',21,'Silver Trout','Common',46,'Surface',false,'insect',1,14,14,'Delicate Fish'],[3,'silverrun_river','river_salmon',23,'River Salmon','Uncommon',30,'Midwater',false,'insect',1,17,19,'Oily Fish'],[3,'silverrun_river','speckled_pike',26,'Speckled Pike','Rare',18,'Midwater',true,'fish_strip',1,22,25,'Predator Fish'],[3,'silverrun_river','crystal_darter',29,'Crystal Darter','Very Rare',6,'Bottom',false,'shell',1,29,36,'Rare Delicacy'],
[4,'brackwater_estuary','brine_mullet',31,'Brine Mullet','Common',46,'Surface',false,'worm',2,18,21,'Basic Fish'],[4,'brackwater_estuary','tide_bass',33,'Tide Bass','Uncommon',30,'Midwater',true,'fish_strip',1,23,28,'Hearty Fish'],[4,'brackwater_estuary','marsh_eel',36,'Marsh Eel','Rare',18,'Bottom',true,'shell',1,30,38,'Oily Fish'],[4,'brackwater_estuary','pearlscale',39,'Pearlscale','Very Rare',6,'Bottom',false,'shell',1,39,55,'Rare Delicacy'],
[5,'embercoast','cinder_sardine',41,'Cinder Sardine','Common',46,'Surface',false,'insect',2,24,30,'Small / Schooling'],[5,'embercoast','ashscale_snapper',43,'Ashscale Snapper','Uncommon',30,'Midwater',true,'fish_strip',1,30,40,'Hearty Fish'],[5,'embercoast','emberfin_tuna',46,'Emberfin Tuna','Rare',18,'Midwater',true,'fish_strip',1,39,54,'Oily Fish'],[5,'embercoast','flare_ray',49,'Flare Ray','Very Rare',6,'Bottom',false,'shell',1,51,78,'Rare Delicacy'],
[6,'frostmere_lake','ice_perch',51,'Ice Perch','Common',46,'Surface',false,'insect',1,30,42,'Basic Fish'],[6,'frostmere_lake','frost_salmon',53,'Frost Salmon','Uncommon',30,'Midwater',false,'insect',1,38,57,'Oily Fish'],[6,'frostmere_lake','snow_pike',56,'Snow Pike','Rare',18,'Midwater',true,'fish_strip',1,49,76,'Predator Fish'],[6,'frostmere_lake','glacial_sturgeon',59,'Glacial Sturgeon','Very Rare',6,'Bottom',false,'shell',1,65,109,'Premium Fish'],
[7,'stormreach_shoals','storm_mackerel',61,'Storm Mackerel','Common',46,'Surface',false,'insect',2,38,57,'Small / Schooling'],[7,'stormreach_shoals','thunderfin_bream',63,'Thunderfin Bream','Uncommon',30,'Midwater',false,'worm',1,47,77,'Hearty Fish'],[7,'stormreach_shoals','razor_barracuda',66,'Razor Barracuda','Rare',18,'Midwater',true,'fish_strip',1,61,103,'Predator Fish'],[7,'stormreach_shoals','tempest_ray',69,'Tempest Ray','Very Rare',6,'Bottom',false,'shell',1,80,148,'Rare Delicacy'],
[8,'aetherdeep_basin','aether_carp',71,'Aether Carp','Common',46,'Surface',false,'luminous',1,46,75,'Premium Fish'],[8,'aetherdeep_basin','prism_eel',73,'Prism Eel','Uncommon',30,'Bottom',true,'shell',1,57,101,'Oily Fish'],[8,'aetherdeep_basin','aether_tuna',76,'Aether Tuna','Rare',18,'Midwater',true,'fish_strip',1,74,135,'Premium Fish'],[8,'aetherdeep_basin','skyglass_sturgeon',79,'Skyglass Sturgeon','Very Rare',6,'Bottom',false,'luminous',1,97,195,'Rare Delicacy'],
[9,'umbral_trench','gloom_cod',81,'Gloom Cod','Common',46,'Bottom',false,'shell',1,54,97,'Hearty Fish'],[9,'umbral_trench','shade_eel',83,'Shade Eel','Uncommon',30,'Bottom',true,'shell',1,68,131,'Oily Fish'],[9,'umbral_trench','nightfin_shark',86,'Nightfin Shark','Rare',18,'Midwater',true,'fish_strip',1,88,175,'Predator Fish'],[9,'umbral_trench','abyssal_ray',89,'Abyssal Ray','Very Rare',6,'Bottom',false,'luminous',1,116,252,'Rare Delicacy'],
[10,'astral_expanse','star_sardine',91,'Star Sardine','Common',46,'Surface',false,'luminous',2,64,124,'Small / Schooling'],[10,'astral_expanse','comet_tuna',93,'Comet Tuna','Uncommon',30,'Midwater',true,'fish_strip',1,80,167,'Premium Fish'],[10,'astral_expanse','celestial_sturgeon',96,'Celestial Sturgeon','Rare',18,'Bottom',false,'luminous',1,104,223,'Premium Fish'],[10,'astral_expanse','starveil_marlin',99,'Starveil Marlin','Very Rare',6,'Midwater',true,'luminous',1,136,322,'Mythic Delicacy'],
];
export const FISH_SPECIES: FishDefinition[] = raw.map(([tier,spot,key,unlockLevel,name,rarity,weight,water,predator,preferredBait,quantity,fight,xp,cookingClass]) => ({ id:`fishing.fish.${key}`, name, spotId:`fishing.spot.${spot}`, tier, unlockLevel, rarity, weight, water, predator, preferredBait, quantity, fight, xp, cookingClass }));

export type FishingRod = { id: string; name: string; unlockLevel: number; power: number; biteSpeed: number; effect: string; bridge: boolean };
export const FISHING_RODS: FishingRod[] = [
 ['old_handline','Old Handline',1,5,0,'None'],['reed_rod','Reed Rod',5,7,.04,'Bait preservation +3 pp'],['alder_rod','Alder Rod',15,10,.08,'Landing time -3%'],['ironwood_rod','Ironwood Rod',25,13,.12,'Bait preservation +5 pp'],['silverpine_rod','Silverpine Rod',35,17,.16,'Rare/Very Rare weight +5%'],['emberwood_rod','Emberwood Rod',45,22,.20,'Double Catch +3 pp'],['frostbark_rod','Frostbark Rod',55,28,.24,'Landing time -6%'],['stormwillow_rod','Stormwillow Rod',65,35,.28,'Aquatic Find +10%'],['aetherwood_rod','Aetherwood Rod',75,43,.32,'Rare/Very Rare weight +8%'],['umbralwood_rod','Umbralwood Rod',85,52,.36,'Bait preservation +8 pp'],['starwood_rod','Starwood Rod',95,62,.40,'Preferred Species +15%; Double Catch +5 pp'],
].map(([key,name,unlockLevel,power,biteSpeed,effect],index) => ({ id:`fishing.tool.${key}`, name:String(name), unlockLevel:Number(unlockLevel), power:Number(power), biteSpeed:Number(biteSpeed), effect:String(effect), bridge:index>0 }));
export const FISHING_TACKLE = [
 {id:'fishing.tackle.cork_float',name:'Cork Float',level:5,effect:'Surface weight ×1.45; bite time -5%'},{id:'fishing.tackle.weighted_sinker',name:'Weighted Sinker',level:15,effect:'Bottom weight ×1.60; bite time +5%'},{id:'fishing.tackle.spinner_lure',name:'Spinner Lure',level:25,effect:'Predator weight ×1.60; predator landing -5%'},{id:'fishing.tackle.fine_hook',name:'Fine Hook',level:35,effect:'Rare+ weight ×1.25; bite time +3%'},{id:'fishing.tackle.double_hook',name:'Double Hook',level:45,effect:'Double Catch +10 pp; landing +10%'},{id:'fishing.tackle.deepwater_rig',name:'Deepwater Rig',level:55,effect:'Bottom weight ×1.80; Very Rare ×1.10; Surface ×0.75'},{id:'fishing.tackle.barbled_master_hook',name:'Barbless Master Hook',level:65,effect:'Mastery XP +12%; bait preservation +10 pp'},{id:'fishing.tackle.aether_spinner',name:'Aether Spinner',level:75,effect:'Predator ×1.40; Rare+ ×1.20; bite -6%'},{id:'fishing.tackle.umbral_sinker',name:'Umbral Sinker',level:85,effect:'Bottom ×1.50; Rare+ ×1.25; landing -8%'},{id:'fishing.tackle.astral_lure',name:'Astral Lure',level:95,effect:'Preferred Species ×1.35; Very Rare ×1.10'},
];
