import React from 'react';
import ReactDOM from 'react-dom/client';
import { AppBootstrap } from './app/AppBootstrap';
import { applyAppSettings, loadAppSettings } from './game/persistence/settingsStorage';
import './styles/tokens.css';
import './styles/global.css';
import './ui/primitives.css';
import './features/professions/mining/mining.css';
import './features/professions/profession-screens.css';
import './features/combat/combat.css';
import './features/onboarding/onboarding.css';
import './ui/overlays/overlays.css';
import './features/settings/settings.css';
import './features/devtools/devtools.css';
import './styles/responsive.css';
import './ui/game/gameplay-layout.css';
import './ui/game/control-language.css';
import './features/profiles/profiles.css';
import './ui/game-v2/game-v2.css';
import './features/equipment/equipment-v2.css';
import './features/bank/bank-v2.css';
import './features/professions/smithing/smithing-v2.css';
import './features/professions/cooking/cooking-v2.css';
import './features/professions/mining/mining-v2.css';
import './features/professions/fishing/fishing-v2.css';
import './features/combat/combat-v2.css';
import './styles/generation2-shell.css';

const initialSettings = loadAppSettings();
applyAppSettings(initialSettings);

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppBootstrap initialSettings={initialSettings} /></React.StrictMode>);
