import { useMemo, useState } from 'react';
import { COMBAT_AREAS, ENEMIES, activeSequence, ITEMS, MELEE_WEAPONS, getCombatHitChance, getPlayerAccuracy, getPlayerAttackInterval, getPlayerEvasion, getPlayerMaxHit, getPlayerResistances, getWeaponSpecial, enemyUnlocked, areaUnlocked, maxHitpoints, type DamageType, type EnemyId, type ItemId, type SaveState } from '../../game/game';
import { COOKING_RECIPES } from '../../game/content/cooking/cookingContent';
import { Badge, Bar, Button, Panel, Tip, Icon } from '../../ui/primitives';
import { ItemMark, ItemTip } from '../../ui/game/ItemDisplay';
import { ActionProgress } from '../../ui/game/ActionProgress';
import { ScreenHeading, Stat } from '../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime } from '../../ui/game/formatters';

type CombatSlotSetter = (index: number, item: ItemId | null) => void;
export function CombatScreen({ game: g, start, stop, stance, target, setArea, queueSpecial, setSpecialMode, setFoodSlot, setFoodReserve, eat, setAutoEat, speedMultiplier = 1 }: {
  game: SaveState; start: () => void; stop: () => void; speedMultiplier?: number; stance: (s: DamageType) => void; target: (id: EnemyId) => void; setArea: (id: string) => void;
  queueSpecial: () => void; setSpecialMode: (mode: 'Auto' | 'Manual' | 'Off') => void; setFoodSlot: CombatSlotSetter; setFoodReserve: (index:number,reserve:number)=>void; eat:(index:number)=>void; setAutoEat:(enabled:boolean,threshold:number)=>void;
}) {
  const [foodOpenSlot, setFoodOpenSlot] = useState<number | null>(null), [foodQuery, setFoodQuery] = useState('');
  const c = g.combat, active = g.activity === 'combat', areas = Object.values(COMBAT_AREAS), area = COMBAT_AREAS[c.areaId] ?? areas[0]!, enemy = ENEMIES[c.targetId];
  const sequence = activeSequence(enemy, c.enemyHp), action = sequence[c.sequenceIndex % sequence.length] ?? sequence[0]!;
  const weapon = g.equipped.weapon ? MELEE_WEAPONS[g.equipped.weapon as keyof typeof MELEE_WEAPONS] : undefined;
  const special = getWeaponSpecial(g), playerResistances = getPlayerResistances(g), accuracy = getPlayerAccuracy(g), hit = getCombatHitChance(accuracy, enemy.evasion), canBegin = Boolean(weapon && g.skills.Attack.level >= weapon.attackLevel);
  const targetList = area.enemies.map((id) => ENEMIES[id]).filter(Boolean);
  const ownedFood = useMemo(() => COOKING_RECIPES.filter((recipe) => recipe.foodValue > 0 && (g.bank[recipe.output as ItemId] ?? 0) > 0 && recipe.outputName.toLowerCase().includes(foodQuery.toLowerCase())), [g.bank, foodQuery]);
  const loot = enemy.loot[0], lootName = loot ? ITEMS[loot.item]?.name ?? 'Reward' : 'No item drops';
  const groups: Array<{label:string;types:DamageType[]}> = [
    { label:'MELEE', types:['Slash','Stab','Crush'] }, { label:'RANGED', types:['Pierce','Puncture'] }, { label:'MAGIC', types:['Air','Fire','Water','Earth'] },
  ];
  return <div className="screen combat-screen">
    <ScreenHeading eyebrow={`${area.name.toUpperCase()} · TIER ${area.tier}`} title={area.name} sub="Read the encounter, prepare your loadout, and watch attack rhythms for openings." accent="combat"><Badge tone={active ? 'live' : 'level-badge'}>{active ? 'IN COMBAT' : enemy.rank.toUpperCase()}</Badge></ScreenHeading>
    <div className="combat-layout">
      <div className="combat-main">
        <Panel className="target-panel" title={`${area.name} Encounters`} action={<label className="area-picker-label">Area <select aria-label="Combat area" value={area.id} disabled={active} onChange={(event)=>setArea(event.target.value)}>{areas.map((item)=><option key={item.id} value={item.id} disabled={!areaUnlocked(g,item.id)}>{item.name} · T{item.tier}{!areaUnlocked(g,item.id)?' · Locked':''}</option>)}</select></label>}>
          <div className="target-list">{targetList.map((item)=>{const locked=!enemyUnlocked(g,item.id),selected=c.targetId===item.id;return <button key={item.id} type="button" className={`enemy-choice ${selected?'selected':''} ${locked?'locked':''}`} disabled={locked||active} aria-pressed={selected} onClick={()=>target(item.id)}><span className="enemy-mark"><Icon name="combat" size={19}/></span><span><b>{item.name}</b><small>{locked?'Encounter requirement not met':`${item.rank} · ${item.style} · ${item.sequence[0]?.type??'Attack'}`}</small></span><span className="enemy-kills">{c.defeated[item.id]??0} K</span></button>})}</div>
          <div className="enemy-card selected-enemy"><div className="enemy-portrait"><Tip content={<><strong>{enemy.name}</strong><span>Tier {enemy.tier} · {enemy.rank} · {enemy.kind}</span><small>{enemy.maxHp} HP · {enemy.style} · {sequence.map((entry)=>entry.name).join(' / ')}</small></>}><div className="enemy-large-mark"><Icon name="combat" size={36}/></div></Tip></div><div><span className="screen-overline">TIER {enemy.tier} · {enemy.rank.toUpperCase()} · {enemy.kind.toUpperCase()}</span><h3>{enemy.name}</h3><small>{area.name} · {enemy.style}</small></div><Badge>{enemy.maxHp} HP</Badge></div>
          <div className="target-stats"><Stat label="Class" value={enemy.rank}/><Stat label="Style" value={enemy.style}/><Stat label="Incoming" value={action.type}/><Stat label="Weakness" value={Object.entries(enemy.resistances).sort((a,b)=>a[1]-b[1])[0]?.[0]??'—'}/></div>
          <div className="resist-panel"><div className="resist-head"><span>ENEMY RESISTANCES</span><small>damage reduction by type</small></div>{groups.map((group)=><div className="resist-group" key={group.label}><span className="damage-group">{group.label}</span><div>{group.types.map((type)=><Resist key={type} type={type} value={enemy.resistances[type]} stance={weapon?.style}/>)}</div></div>)}</div>
          <div className="advantage-note">Your {weapon?.style??'weapon'} meets {enemy.resistances[weapon?.style??'Slash']}% resistance.</div>
        </Panel>
        <Panel className={`battle-panel ${active?'battle-active':''}`} title="Encounter" action={<Badge tone={active?'live':''}>{active?'LIVE':c.runState==='ended'?'ENDED':'READY'}</Badge>}>
          <div className="battle-scene"><div className="scene-moon"/><div className="scene-trees"><i/><i/><i/><i/><i/></div><div className="scene-road"/><div className="scene-fog"/><div className="battle-figure player-figure"><div className="figure-head"/><div className="figure-body"/><div className="figure-weapon"/></div><div className={`battle-foe ${active?'foe-alert':''} ${c.enemyHp===0?'foe-fallen':''}`}><div className="enemy-glyph"><Icon name="combat" size={76}/></div></div><div className="scene-groundline"/><div className="stage-caption"><span>ENCOUNTER {c.encounterIndex+1}</span><b>{enemy.name.toUpperCase()}</b></div><div className="floating-damage" key={c.log[0]}>{c.log[0]?.match(/for (\d+)/)?.[1]??''}</div></div>
          <div className="battle-health"><Health label="YOU" value={c.playerHp} max={maxHitpoints(g.skills.Hitpoints.level)} accent="health"/><Health label={enemy.name.toUpperCase()} value={c.enemyHp} max={enemy.maxHp} accent="enemy"/></div>
          <div className="action-timers"><div className="timer-unit"><span>YOUR NEXT STRIKE</span><b>{active?formatActionTime(c.playerTimer):`${(getPlayerAttackInterval(g)/1000).toFixed(2)}s`}</b><ActionProgress active={active} remainingMs={c.playerTimer} durationMs={getPlayerAttackInterval(g)} phaseKey={c.playerActionSerial} speedMultiplier={speedMultiplier} label="Player combat progress" tone="xp"/></div><div className="timer-unit"><span>ENEMY ACTION</span><b>{active?`${action.name} · ${formatActionTime(c.enemyTimer)}`:sequence.map((entry)=>entry.name).join(' → ')}</b><ActionProgress active={active} remainingMs={c.enemyTimer} durationMs={enemy.intervalMs*(action.intervalMultiplier??1)} phaseKey={c.enemyActionSerial} speedMultiplier={speedMultiplier} label="Enemy combat progress" tone="danger"/></div></div>
          <div className="combat-readiness"><span>Weapon <b>{weapon?.name??'None'}</b></span><span>Off-hand <b>{g.equipped.offhand?ITEMS[g.equipped.offhand]?.name??'Unknown':'None'}</b></span><span>Hit chance <b>{(hit*100).toFixed(0)}%</b></span><span>Max hit <b>{getPlayerMaxHit(g)}</b></span><span>Evasion <b>{getPlayerEvasion(g)}</b></span><span>Attack <b>{g.skills.Attack.level}</b></span></div>
          <div className="player-resistance-grid" aria-label="Player resistances">{groups.flatMap((group)=>group.types).map((type)=><span key={type}>{type}<b>{playerResistances[type]}%</b></span>)}</div>
          <div className="stance-control"><div><span className="tiny-label">ATTACK STYLE · {weapon?.style??c.stance.toUpperCase()}</span><small>Damage is reduced by the matching resistance type.</small></div><div className="segmented"><button className="selected" type="button" aria-pressed="true" onClick={()=>stance(weapon?.style??c.stance)}>{weapon?.style??c.stance}<small>{enemy.resistances[weapon?.style??c.stance]}% resist</small></button></div></div>
          <div className="special-control"><div><span className="tiny-label">SPECIAL · STAMINA {Math.floor(c.stamina)} / 100</span><Bar value={c.stamina} max={100} accent="xp"/><small>{special?`${special.name} · ${special.cost} stamina · ${special.type}`:'No weapon special'}{special?' · resolves after a basic strike':''}</small></div><label>Mode <select value={c.specialMode} onChange={(event)=>setSpecialMode(event.target.value as 'Auto'|'Manual'|'Off')}><option>Auto</option><option>Manual</option><option>Off</option></select></label><Button tone="quiet" onClick={queueSpecial} disabled={!special||c.queuedSpecial||c.stamina<(special?.cost??Infinity)}>Queue Special{c.queuedSpecial?' · Queued':''}</Button></div>
          <FoodControls game={g} setFoodSlot={setFoodSlot} setFoodReserve={setFoodReserve} eat={eat} setAutoEat={setAutoEat} foodOpenSlot={foodOpenSlot} setFoodOpenSlot={setFoodOpenSlot} foodQuery={foodQuery} setFoodQuery={setFoodQuery} ownedFood={ownedFood}/>
          <div className="battle-footer"><div className="readiness-mini"><span className={`pulse-dot ${active?'pulsing':''}`}/><span>{c.statuses.length?c.statuses.map((status)=>`${status.type} ${Math.ceil(status.remainingMs/1000)}s`).join(' · '):active?`${(hit*100).toFixed(0)}% hit chance · ${c.statuses.length} active effects`:canBegin?'Ready to enter this encounter':'Equip a usable weapon to enter'}</span></div><Button tone="copper" onClick={active?stop:start} disabled={!active&&!canBegin}>{active?'Leave Encounter':c.runState==='ended'?'Begin Again':'Begin Combat'}<span>{active?'Ⅱ':'▶'}</span></Button></div>
        </Panel>
      </div>
      <Panel className="combat-intel" title="Battle Record"><div className="sequence-card"><span className="tiny-label">{enemy.name.toUpperCase()} SEQUENCE</span><div className="sequence-flow">{sequence.map((entry,i)=><div key={`${entry.name}-${i}`} className={i===c.sequenceIndex&&active?'upcoming-action':''}><b>{String(i+1).padStart(2,'0')}</b><span>{entry.name}</span></div>)}</div><small>{action.name} · {action.multiplier.toFixed(2)}× {action.type}{action.status?` · ${action.status.type}`:''}</small></div><div className="stat-rows"><Stat label="Kills this session" value={fmt(c.kills)}/><Stat label="Gold earned" value={fmt(c.gold)} accent="gold-text"/><Stat label="Encounter count" value={fmt(c.defeated[enemy.id]??0)}/><Stat label="XP earned" value={fmt(c.xp)} accent="xp-text"/></div><div className="log-panel"><div className="log-heading"><span>COMBAT LOG</span><small>{active?'LIVE':'RECENT'}</small></div><div className="log-lines">{c.log.length?c.log.slice(0,5).map((line,i)=><div key={`${i}-${line}`} className={i===0?'latest':''}>{line}</div>):<div className="log-empty">This area is quiet.</div>}</div></div>{loot&&<div className="loot-preview"><ItemTip id={loot.item}><ItemMark id={loot.item}/></ItemTip><div><b>{lootName}</b><small>{loot.guaranteed?'Guaranteed drop':`${Math.round(loot.chance*100)}% chance · ${loot.min}-${loot.max} per drop`}{enemy.offering?` · Offering ${ITEMS[enemy.offering]?.offeringValue??0}`:''}</small></div><span>{enemy.gold} <Icon name="gold" size={14}/></span></div>}</Panel>
    </div>
  </div>;
}

function Health({label,value,max,accent}:{label:string;value:number;max:number;accent:string}){return <div className="health-unit"><div className="health-caption"><span><i className={`health-dot ${label==='YOU'?'player-dot':'enemy-dot'}`}/>{label}</span><b>{Math.max(0,Math.ceil(value))} <small>/ {max}</small></b></div><Bar value={value} max={max} accent={accent}/></div>}
function FoodControls({game:g,setFoodSlot,setFoodReserve,eat,setAutoEat,foodOpenSlot,setFoodOpenSlot,foodQuery,setFoodQuery,ownedFood}:{game:SaveState;setFoodSlot:CombatSlotSetter;setFoodReserve:(index:number,reserve:number)=>void;eat:(index:number)=>void;setAutoEat:(enabled:boolean,threshold:number)=>void;foodOpenSlot:number|null;setFoodOpenSlot:(slot:number|null)=>void;foodQuery:string;setFoodQuery:(value:string)=>void;ownedFood:typeof COOKING_RECIPES}){
 return <div className="food-sustain-panel"><div className="food-head"><b>Food &amp; Satiety</b><strong>{Math.floor(g.food.satiety)} / 100</strong></div><div className="food-satiety"><Bar value={g.food.satiety} max={100} accent={g.food.satiety>=90?'danger':'xp'} label={`Satiety ${Math.floor(g.food.satiety)} of 100`}/><span>{g.food.satiety>=90?'OVEREAT RISK':g.food.satiety>=70?'HIGH SATIETY':'−1 / sec'}</span></div><div className="food-slots">{g.food.slots.map((slot,index)=>{const item=slot.item,amount=item?g.bank[item]??0:0;return <div className={`food-slot ${g.food.activePriority===index?'priority':''}`} key={index}><b>{index+1}</b><div className="food-picker"><button type="button" className="food-picker-trigger" aria-expanded={foodOpenSlot===index} onClick={()=>{setFoodOpenSlot(foodOpenSlot===index?null:index);setFoodQuery('');}}>{item?ITEMS[item]?.name??'Food':'Choose food'} <span>⌄</span></button>{foodOpenSlot===index&&<div className="food-picker-menu"><label className="sr-only" htmlFor={`food-search-${index}`}>Search owned food</label><input id={`food-search-${index}`} autoFocus value={foodQuery} onChange={(event)=>setFoodQuery(event.target.value)} placeholder="Search owned food"/><button type="button" className="food-picker-clear" onClick={()=>{setFoodSlot(index,null);setFoodOpenSlot(null);}}>Clear slot</button>{ownedFood.map((recipe)=><button type="button" className="food-option" key={recipe.output} onClick={()=>{setFoodSlot(index,recipe.output as ItemId);setFoodOpenSlot(null);}}><b>{recipe.outputName}</b><small>Heal {recipe.foodValue*10} · Satiety 20 · ×{g.bank[recipe.output as ItemId]??0}</small></button>)}{ownedFood.length===0&&<small className="empty-copy">No owned food matches.</small>}</div>}</div><span>{item?`${amount}× · ${ITEMS[item]?.name??'Food'}`:'Choose Food'}</span><label className="food-reserve">Keep <input type="number" min="0" max={amount} value={slot.reserve} disabled={g.activity==='combat'} aria-label={`Food reserve for slot ${index+1}`} onChange={(event)=>setFoodReserve(index,Number(event.target.value))}/></label><Button tone="quiet" disabled={!item||amount<=slot.reserve} onClick={()=>eat(index)}>Eat</Button></div>})}</div><div className="food-settings"><label><input type="checkbox" checked={g.food.autoEat} onChange={(event)=>setAutoEat(event.target.checked,g.food.threshold)}/> Auto Eat</label><label>Eat at HP % <input type="number" min="1" max="99" value={g.food.threshold} onChange={(event)=>setAutoEat(g.food.autoEat,Math.max(1,Math.min(99,Number(event.target.value)||1)))}/></label><span>{g.food.foodLockMs>0?`FOOD LOCK ${Math.ceil(g.food.foodLockMs/1000)}s`:g.food.stunMs>0?`OVEREAT · ${Math.ceil(g.food.stunMs/1000)}s STUN`:g.food.feedback}</span></div></div>
}
export function Resist({type,value,stance}:{type:string;value:number;stance?:string}){return <div className={`resist-cell ${value<0?'weak':''} ${value>=18?'high-resist':''} ${type===stance?'chosen-type':''}`}><Tip content={<><strong>{type} Resistance</strong><small>{value>0?`Reduces ${type} damage by ${value}%.`:value<0?`Increases ${type} damage taken by ${Math.abs(value)}%.`:`No change to ${type} damage.`}</small></>}><span>{type}</span></Tip><b>{value>0?'+':''}{value}%</b></div>}
