import { Badge, Bar, Button, Icon, Panel, Tip } from '../../ui/primitives';
import { ItemMark, ItemTip } from '../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../ui/game/ScreenPrimitives';
import { fmt, timeText } from '../../ui/game/formatters';
import { hitChance, maxHitpoints, PROVISIONAL_FIRST_SLICE_COMBAT_VALUES, type SaveState } from '../../game/game';

export function CombatScreen({ game: g, start, stop, stance }: { game: SaveState; start: () => void; stop: () => void; stance: (s: 'Slash' | 'Stab') => void }) {
 const active = g.activity === 'combat', c = g.combat, hit = hitChance(100 + 6 * g.skills.Attack.level + (g.equipped.weapon === 'sword' ? 84 : 0), PROVISIONAL_FIRST_SLICE_COMBAT_VALUES.wolfMeleeEvasion);
 return <div className="screen combat-screen"><ScreenHeading eyebrow="BROKEN ROAD · TIER 1" title="Broken Road" sub="A bramble-lined trade road. Something watches from the verge." accent="combat"><Badge tone={active ? 'live' : 'level-badge'}>{active ? 'IN COMBAT' : 'ROAD WOLF'}</Badge></ScreenHeading><div className="combat-layout"><Panel className="target-panel" title="Roadside Threat"><div className="enemy-card"><div className="wolf-avatar"><Tip content={<><strong>Road Wolf</strong><span>Normal · Beast</span><small>70 HP · Melee · Bite / Bite / Rending Fang</small></>}><WolfArt/></Tip></div><div><span className="screen-overline">NORMAL · BEAST</span><h3>Road Wolf</h3><small>Broken Road · Common</small></div><Badge>LV. 1</Badge></div><div className="threat-copy">A lean hunter with an old scar across its muzzle. It watches your hands before it moves.</div><div className="target-stats"><Stat label="Hitpoints" value={`${Math.max(0, c.wolfHp)} / 70`} /><Stat label="Style" value="Melee" /><Stat label="Basic damage" value="Stab" /><Stat label="Melee evasion" value="120" /></div><div className="resist-panel"><div className="resist-head"><span>RESISTANCE</span><small>damage reduced</small></div><div className="resist-group"><span className="damage-group">MELEE</span><div>{[['Slash',12],['Stab',18],['Crush',14]].map(([t,v])=><Resist key={t} type={String(t)} value={Number(v)} stance={c.stance}/>)}</div></div><div className="resist-group"><span className="damage-group">RANGED</span><div>{[['Pierce',24],['Puncture',20]].map(([t,v])=><Resist key={t} type={String(t)} value={Number(v)}/>)}</div></div><div className="resist-group"><span className="damage-group">MAGIC</span><div>{[['Air',0],['Fire',-5],['Water',8],['Earth',-8]].map(([t,v])=><Resist key={t} type={String(t)} value={Number(v)}/>)}</div></div></div><div className="advantage-note">{c.stance === 'Slash' ? 'Slash is currently more effective than Stab.' : 'Stab resistance is higher; Slash is more effective.'}</div></Panel>
 <Panel className={`battle-panel ${active ? 'battle-active' : ''}`} title="The roadside" action={<Badge tone={active ? 'live' : ''}>{active ? 'LIVE' : 'WAITING'}</Badge>}><div className="battle-scene"><div className="scene-moon"/><div className="scene-trees"><i/><i/><i/><i/><i/></div><div className="scene-road"/><div className="scene-fog"/><div className="battle-figure player-figure"><div className="figure-head"/><div className="figure-body"/><div className="figure-weapon"/></div><div className={`battle-wolf ${active ? 'wolf-alert' : ''} ${c.wolfHp === 0 ? 'wolf-fallen' : ''}`}><WolfArt/></div><div className="scene-groundline"/><div className="stage-caption"><span>THE BROKEN ROAD</span><b>WESTERN VERGE</b></div><div className="floating-damage" key={c.log[0]}>{c.log[0]?.match(/for (\d+)/)?.[1] ?? ''}</div></div>
 <div className="battle-health"><div className="health-unit"><div className="health-caption"><span><i className="health-dot player-dot"/>YOU</span><b>{Math.max(0, Math.ceil(c.playerHp))} <small>/ {maxHitpoints(g.skills.Hitpoints.level)}</small></b></div><Bar value={c.playerHp} max={maxHitpoints(g.skills.Hitpoints.level)} accent="health" /></div><div className="health-unit"><div className="health-caption"><span><i className="health-dot wolf-dot"/>ROAD WOLF</span><b>{c.wolfHp || '—'} <small>/ 70</small></b></div><Bar value={c.wolfHp} max={70} accent="enemy" /></div></div>
 <div className="action-timers"><div className="timer-unit"><span>YOUR NEXT STRIKE</span><b>{active ? timeText(c.playerTimer) : '2.40s'}</b><Bar value={active ? 2400 - c.playerTimer : 0} max={2400} accent="xp"/></div><div className="timer-unit"><span>WOLF ACTION</span><b>{active ? c.seq === 2 ? 'Rending Fang · ' : 'Bite · ' : 'Sequence'}{active ? timeText(c.enemyTimer) : 'Bite → Bite → Fang'}</b><Bar value={active ? 3000 - c.enemyTimer : 0} max={3000} accent="danger"/></div></div>
 <div className="stance-control"><div><span className="tiny-label">SWORD STANCE</span><small>Applies on your next action. Damage type changes the resistance check.</small></div><div className="segmented"><button className={c.stance === 'Slash' ? 'selected' : ''} onClick={() => stance('Slash')}>Slash <small>12% resist</small></button><button className={c.stance === 'Stab' ? 'selected' : ''} onClick={() => stance('Stab')}>Stab <small>18% resist</small></button></div></div>
 <div className="battle-footer"><div className="readiness-mini"><span className={`pulse-dot ${active ? 'pulsing' : ''}`}/><span>{active ? c.bleed ? `Bleed · ${c.bleed} damage over ${timeText(c.bleedTimer)}` : `Hit chance ${(hit * 100).toFixed(0)}% · Next action` : 'Equip Copper Sword + one armor piece to enter'}</span></div><Button tone="copper" onClick={active ? stop : start} disabled={!active && (g.equipped.weapon !== 'sword' || !(g.equipped.head || g.equipped.armor || g.equipped.hands || g.equipped.feet))}>{active ? 'Leave Combat' : 'Begin Combat'}<span>{active ? 'Ⅱ' : '▶'}</span></Button></div>
 </Panel><Panel className="combat-intel" title="Battle Record"><div className="sequence-card"><span className="tiny-label">WOLF SEQUENCE</span><div className="sequence-flow">{['Bite','Bite','Rending Fang'].map((name,i)=><div key={i} className={i === c.seq && active ? 'upcoming-action' : ''}><b>0{i + 1}</b><span>{name}</span></div>)}</div><small>Rending Fang · 1.25× Stab · Bleed 10% over 6s</small></div><div className="stat-rows"><Stat label="Kills this session" value={fmt(c.kills)}/><Stat label="Gold earned" value={fmt(c.gold)} accent="gold-text"/><Stat label="Beast Trophy" value={fmt(c.trophies)}/><Stat label="XP earned" value={fmt(c.xp)} accent="xp-text"/></div><div className="log-panel"><div className="log-heading"><span>COMBAT LOG</span><small>{active ? 'LIVE' : 'RECENT'}</small></div><div className="log-lines">{c.log.length ? c.log.slice(0,5).map((line,i)=><div key={`${i}-${line}`} className={i===0?'latest':''}>{line}</div>) : <div className="log-empty">The road is quiet.</div>}</div></div><div className="loot-preview"><ItemTip id="trophy"><ItemMark id="trophy"/></ItemTip><div><b>Beast Trophy</b><small>First kill reward · Offering Value 5</small></div><span>+8 <Icon name="gold" size={14}/></span></div></Panel></div></div>;
}

export function Resist({ type, value, stance }: { type: string; value: number; stance?: string }) { return <div className={`resist-cell ${value < 0 ? 'weak' : value >= 18 ? 'high-resist' : ''} ${type === stance ? 'chosen-type' : ''}`}><Tip content={<><strong>{type} Resistance</strong><small>{value > 0 ? `Reduces ${type} damage by ${value}%.` : value < 0 ? `Increases ${type} damage taken by ${Math.abs(value)}%.` : `No change to ${type} damage.`}</small></>}><span>{type}</span></Tip><b>{value > 0 ? '+' : ''}{value}%</b></div>; }

export function WolfArt() { return <svg viewBox="0 0 240 150" className="wolf-art" aria-label="Road Wolf silhouette" role="img"><defs><linearGradient id="wolfcoat" x1="0" x2="1" y1="0" y2="1"><stop stopColor="#888779"/><stop offset=".52" stopColor="#4c504c"/><stop offset="1" stopColor="#252c2b"/></linearGradient></defs><path d="M23 103c7-18 20-25 38-27l22-18 31 2 19-19 23 10 16-15 5 25 21 8 12 20-16 11-4 28h-18l-5-24-18 9-21 1-15-5-12 17H99l6-27-31-4-18 9-11 22H28l5-23z" fill="url(#wolfcoat)" stroke="#a3a195" strokeWidth="3"/><path d="m128 61 4-25 20 15m24-2 15-23 3 31m-88 25 29-6 20 5 12 18m-50-7 4 25m56-40 15 2" fill="none" stroke="#272d2b" strokeWidth="7" strokeLinecap="round"/><path d="M182 60 203 72l-16 10-14-8z" fill="#6d6253"/><circle cx="185" cy="65" r="2.4" fill="#d78c50"/><path d="m173 72 12 4m-57 8 11 14" stroke="#c07a4a" strokeWidth="3" opacity=".7"/><path d="M12 128h210" stroke="#c8ae82" strokeWidth="2" opacity=".26"/></svg>; }
