import { Badge, Bar, Button, Icon, Panel, Tip } from '../../ui/primitives';
import { ItemMark, ItemTip } from '../../ui/game/ItemDisplay';
import { ScreenHeading, Stat } from '../../ui/game/ScreenPrimitives';
import { fmt, formatActionTime } from '../../ui/game/formatters';
import { ENEMIES, NORMAL_ENEMIES, RESISTANCES } from '../../game/content/combat/t1Enemies';
import { MELEE_WEAPONS } from '../../game/content/combat/meleeWeapons';
import { hitChance, maxHitpoints, type DamageType, type EnemyId, type SaveState } from '../../game/game';
import { ActionProgress } from '../../ui/game/ActionProgress';
import { COOKING_RECIPES } from '../../game/content/cooking/cookingContent';
import { ITEMS } from '../../game/content/items/itemRegistry';
import type { ItemId } from '../../game/types/gameTypes';

export function CombatScreen({ game: g, start, stop, stance, target, queueSpecial, setSpecialMode, setFoodSlot, eat, setAutoEat, speedMultiplier = 1 }: { game: SaveState; start: () => void; stop: () => void; speedMultiplier?: number; stance: (s: DamageType) => void; target: (id: EnemyId) => void; queueSpecial: () => void; setSpecialMode: (mode: 'Auto' | 'Manual' | 'Off') => void; setFoodSlot:(index:number,item:ItemId|null)=>void; eat:(index:number)=>void; setAutoEat:(enabled:boolean,threshold:number)=>void }) {
 const active = g.activity === 'combat', c = g.combat, enemy = ENEMIES[c.targetId], action = enemy.sequence[c.sequenceIndex % enemy.sequence.length]!, weapon = g.equipped.weapon && g.equipped.weapon in MELEE_WEAPONS ? MELEE_WEAPONS[g.equipped.weapon as keyof typeof MELEE_WEAPONS] : null, weaponAccuracy = 100 + 6 * g.skills.Attack.level + (weapon?.accuracyBonus ?? 0), hit = hitChance(weaponAccuracy, enemy.evasion), playerStyle = weapon?.style ?? c.stance, selectableStyles: readonly DamageType[] = weapon?.id === 'combat.weapon.melee.copper_sword' ? ['Slash','Stab'] : [playerStyle as DamageType];
 const unlocked = (id: EnemyId) => id !== 'ironjaw-boar' || NORMAL_ENEMIES.every((normal) => (c.defeated[normal] ?? 0) > 0);
 return <div className="screen combat-screen"><ScreenHeading eyebrow="BROKEN ROAD · TIER 1" title="Broken Road" sub="Choose a threat, read its rhythm, and prepare for the road ahead." accent="combat"><Badge tone={active ? 'live' : 'level-badge'}>{active ? 'IN COMBAT' : enemy.rank.toUpperCase()}</Badge></ScreenHeading>
  <div className="combat-layout">
   <Panel className="target-panel" title="Roadside Threats"><div className="target-list">{([...NORMAL_ENEMIES, 'ironjaw-boar'] as EnemyId[]).map((id) => { const item = ENEMIES[id], locked = !unlocked(id), selected = c.targetId === id; return <button key={id} className={`enemy-choice ${selected ? 'selected' : ''} ${locked ? 'locked' : ''}`} onClick={() => !locked && !active && target(id)} disabled={locked || active} aria-pressed={selected}><span className={`enemy-mark enemy-${id}`}><Icon name={'combat'} size={19}/></span><span><b>{item.name}</b><small>{locked ? 'Defeat each road threat to reveal' : `${item.rank} · ${item.style} · ${item.sequence[0]!.type}`}</small></span><span className="enemy-kills">{c.defeated[id] ?? 0} K</span></button>; })}</div><div className="enemy-card selected-enemy"><div className="enemy-portrait"><Tip content={<><strong>{enemy.name}</strong><span>{enemy.rank} · {enemy.kind}</span><small>{enemy.hp} HP · {enemy.style} · {enemy.sequence.map((entry) => entry.name).join(' / ')}</small></>}><div className="enemy-large-mark"><Icon name="combat" size={36}/></div></Tip></div><div><span className="screen-overline">{enemy.rank.toUpperCase()} · {enemy.kind.toUpperCase()}</span><h3>{enemy.name}</h3><small>Broken Road · {enemy.style}</small></div><Badge>{enemy.hp} HP</Badge></div><div className="target-stats"><Stat label="Class" value={enemy.rank}/><Stat label="Style" value={enemy.style}/><Stat label="Incoming" value={action.type}/><Stat label="Weakness" value={Object.entries(enemy.resistance).sort((a,b) => a[1]-b[1])[0]?.[0] ?? '—'}/></div><div className="resist-panel"><div className="resist-head"><span>RESISTANCE</span><small>damage reduced</small></div>{(['MELEE','RANGED','MAGIC'] as const).map((group) => <div className="resist-group" key={group}><span className="damage-group">{group}</span><div>{(group === 'MELEE' ? ['Slash','Stab','Crush'] : group === 'RANGED' ? ['Pierce','Puncture'] : ['Air','Fire','Water','Earth']).map((type) => { const value = enemy.resistance[type as DamageType] ?? RESISTANCES[type as DamageType]; return <Resist key={type} type={type} value={value} stance={playerStyle}/>; })}</div></div>)}</div><div className="advantage-note">Your {playerStyle} attacks meet {enemy.resistance[playerStyle as DamageType] ?? 0}% resistance.</div></Panel>
   <Panel className={`battle-panel ${active ? 'battle-active' : ''}`} title="Encounter" action={<Badge tone={active ? 'live' : ''}>{active ? 'LIVE' : 'WAITING'}</Badge>}><div className="battle-scene"><div className="scene-moon"/><div className="scene-trees"><i/><i/><i/><i/><i/></div><div className="scene-road"/><div className="scene-fog"/><div className="battle-figure player-figure"><div className="figure-head"/><div className="figure-body"/><div className="figure-weapon"/></div><div className={`battle-foe ${active ? 'foe-alert' : ''} ${c.enemyHp === 0 ? 'foe-fallen' : ''}`}><EnemyGlyph id={enemy.id}/></div><div className="scene-groundline"/><div className="stage-caption"><span>CURRENT ENCOUNTER</span><b>{enemy.name.toUpperCase()}</b></div><div className="floating-damage" key={c.log[0]}>{c.log[0]?.match(/for (\d+)/)?.[1] ?? ''}</div></div>
    <div className="battle-health"><div className="health-unit"><div className="health-caption"><span><i className="health-dot player-dot"/>YOU</span><b>{Math.max(0, Math.ceil(c.playerHp))} <small>/ {maxHitpoints(g.skills.Hitpoints.level)}</small></b></div><Bar value={c.playerHp} max={maxHitpoints(g.skills.Hitpoints.level)} accent="health" /></div><div className="health-unit"><div className="health-caption"><span><i className="health-dot enemy-dot"/>{enemy.name.toUpperCase()}</span><b>{c.enemyHp || '—'} <small>/ {enemy.hp}</small></b></div><Bar value={c.enemyHp} max={enemy.hp} accent="enemy" /></div></div>
     <div className="action-timers"><div className="timer-unit"><span>YOUR NEXT STRIKE</span><b>{active ? formatActionTime(c.playerTimer) : `${(g.equipped.weapon === 'combat.weapon.melee.copper_battle_axe' ? 2.8 : g.equipped.weapon === 'combat.weapon.melee.copper_mace' ? 2.7 : 2.4).toFixed(2)}s`}</b><ActionProgress active={active} remainingMs={c.playerTimer} durationMs={(g.equipped.weapon === 'combat.weapon.melee.copper_battle_axe' ? 2800 : g.equipped.weapon === 'combat.weapon.melee.copper_mace' ? 2700 : 2400) + (g.equipped.offhand === 'combat.offhand.melee.copper_shield' ? 100 : 0)} phaseKey={c.playerActionSerial} speedMultiplier={speedMultiplier} label="Player combat progress" tone="xp"/></div><div className="timer-unit"><span>ENEMY ACTION</span><b>{active ? `${action.name} · ${formatActionTime(c.enemyTimer)}` : enemy.sequence.map((x) => x.name).join(' → ')}</b><ActionProgress active={active} remainingMs={c.enemyTimer} durationMs={enemy.intervalMs * (action.intervalMultiplier ?? 1)} phaseKey={c.enemyActionSerial} speedMultiplier={speedMultiplier} label="Enemy combat progress" tone="danger"/></div></div>
     <div className="stance-control"><div><span className="tiny-label">{g.equipped.weapon === 'combat.weapon.melee.copper_battle_axe' ? 'BATTLE AXE · SLASH' : g.equipped.weapon === 'combat.weapon.melee.copper_mace' ? 'MACE · CRUSH' : 'SWORD STANCE'}</span><small>Changes the resistance used on your next basic strike.</small></div><div className="segmented">{selectableStyles.map((style) => <button key={style} className={c.stance === style ? 'selected' : ''} onClick={() => stance(style)}>{style}<small>{enemy.resistance[style] ?? 0}% resist</small></button>)}</div></div>
     <div className="special-control"><div><span className="tiny-label">SPECIAL · STAMINA {Math.floor(c.stamina)} / 100</span><Bar value={c.stamina} max={100} accent="xp"/><small>{g.equipped.weapon === 'combat.weapon.melee.copper_battle_axe' ? "Executioner's Chop · 50" : g.equipped.weapon === 'combat.weapon.melee.copper_mace' ? 'Concussive Blow · 45' : 'Precision Lunge · 35'} stamina · resolves after a basic strike</small></div><label>Mode <select value={c.specialMode} onChange={(event) => setSpecialMode(event.target.value as 'Auto'|'Manual'|'Off')}><option>Auto</option><option>Manual</option><option>Off</option></select></label><Button tone="quiet" onClick={queueSpecial} disabled={c.queuedSpecial || c.stamina < (g.equipped.weapon === 'combat.weapon.melee.copper_battle_axe' ? 50 : g.equipped.weapon === 'combat.weapon.melee.copper_mace' ? 45 : 35)}>Queue Special{c.queuedSpecial ? ' · Queued' : ''}</Button></div>
     <div className="food-sustain-panel"><div className="food-head"><b>Food &amp; Satiety</b><strong>{Math.floor(g.food.satiety)} / 100</strong></div><div className="food-satiety"><Bar value={g.food.satiety} max={100} accent={g.food.satiety>=90?'danger':'xp'} label={`Satiety ${Math.floor(g.food.satiety)} of 100`}/><span>{g.food.satiety>=90?'OVEREAT RISK':g.food.satiety>=70?'HIGH SATIETY':'-1 / sec'}</span></div><div className="food-slots">{g.food.slots.map((slot,index)=>{const item=slot.item,amount=item?g.bank[item]??0:0;return <div className={`food-slot ${g.food.activePriority===index?'priority':''}`} key={index}><b>{index+1}</b><select aria-label={`Food slot ${index+1}`} value={item??''} onChange={event=>setFoodSlot(index,(event.target.value||null) as ItemId|null)}><option value="">Empty slot</option>{COOKING_RECIPES.filter(x=>x.foodValue>0).map(recipe=><option key={recipe.output} value={recipe.output}>{recipe.outputName}</option>)}</select><span>{item?`${amount}� � ${ITEMS[item]?.name??'Food'}`:'Choose Food'}</span><Button tone="quiet" disabled={!item||amount<=slot.reserve} onClick={()=>eat(index)}>Eat</Button></div>})}</div><div className="food-settings"><label><input type="checkbox" checked={g.food.autoEat} onChange={event=>setAutoEat(event.target.checked,g.food.threshold)}/> Auto Eat</label><label>Eat at HP % <input type="number" min="1" max="95" value={g.food.threshold} onChange={event=>setAutoEat(g.food.autoEat,Math.max(1,Math.min(95,Number(event.target.value)||1)))}/></label><span>{g.food.foodLockMs>0?`FOOD LOCK ${Math.ceil(g.food.foodLockMs/1000)}s`:g.food.stunMs>0?`OVEREAT � ${Math.ceil(g.food.stunMs/1000)}s STUN`:g.food.feedback}</span></div></div>     <div className="battle-footer"><div className="readiness-mini"><span className={`pulse-dot ${active ? 'pulsing' : ''}`}/><span>{c.statuses.length ? c.statuses.map((status) => `${status.type} ${Math.ceil(status.remainingMs / 1000)}s`).join(' · ') : active ? `Hit chance ${(hit * 100).toFixed(0)}% · ${c.statuses.length} active effects` : 'Equip a melee weapon and one armor piece to enter'}</span></div><Button tone="copper" onClick={active ? stop : start} disabled={!active && (!['combat.weapon.melee.copper_sword','combat.weapon.melee.copper_battle_axe','combat.weapon.melee.copper_mace'].includes(g.equipped.weapon ?? '') || !(g.equipped.head || g.equipped.armor || g.equipped.hands || g.equipped.feet))}>{active ? 'Leave Combat' : 'Begin Combat'}<span>{active ? 'Ⅱ' : '▶'}</span></Button></div>
   </Panel>
    <Panel className="combat-intel" title="Battle Record"><div className="sequence-card"><span className="tiny-label">{enemy.name.toUpperCase()} SEQUENCE</span><div className="sequence-flow">{enemy.sequence.map((entry,i)=><div key={`${entry.name}-${i}`} className={i === c.sequenceIndex && active ? 'upcoming-action' : ''}><b>0{i + 1}</b><span>{entry.name}</span></div>)}</div><small>{action.name} · {action.multiplier.toFixed(2)}× {action.type}{action.status ? ` · ${action.status.type}` : ''}</small></div><div className="stat-rows"><Stat label="Kills this session" value={fmt(c.kills)}/><Stat label="Gold earned" value={fmt(c.gold)} accent="gold-text"/><Stat label="Beast Trophy" value={fmt(c.trophies)}/><Stat label="XP earned" value={fmt(c.xp)} accent="xp-text"/></div><div className="log-panel"><div className="log-heading"><span>COMBAT LOG</span><small>{active ? 'LIVE' : 'RECENT'}</small></div><div className="log-lines">{c.log.length ? c.log.slice(0,5).map((line,i)=><div key={`${i}-${line}`} className={i===0?'latest':''}>{line}</div>) : <div className="log-empty">The road is quiet.</div>}</div></div><div className="loot-preview"><ItemTip id="combat.loot.beast_trophy"><ItemMark id="combat.loot.beast_trophy"/></ItemTip><div><b>Beast Trophy</b><small>First kill reward · Offering Value 5</small></div><span>+{enemy.gold} <Icon name="gold" size={14}/></span></div></Panel>
  </div></div>;
}

function EnemyGlyph({ id }: { id: EnemyId }) { return <div className={`enemy-glyph enemy-glyph-${id}`} aria-label={ENEMIES[id].name}><Icon name={id === 'hedge-spark' ? 'spark' : id === 'ragged-poacher' ? 'bow' : 'combat'} size={76}/></div>; }
export function Resist({ type, value, stance }: { type: string; value: number; stance?: string }) { return <div className={`resist-cell ${value < 0 ? 'weak' : value >= 18 ? 'high-resist' : ''} ${type === stance ? 'chosen-type' : ''}`}><Tip content={<><strong>{type} Resistance</strong><small>{value > 0 ? `Reduces ${type} damage by ${value}%.` : value < 0 ? `Increases ${type} damage taken by ${Math.abs(value)}%.` : `No change to ${type} damage.`}</small></>}><span>{type}</span></Tip><b>{value > 0 ? '+' : ''}{value}%</b></div>; }
